### ISSUE TITLE
VERSION environment variable set can cause troubles

### ISSUE THREAD

**Issue by mildred** [containers/toolbox#261] opened 2019-09-16 12:56 UTC
On the Dockerfile, the VERSION environment variable is set, and this can cause problems depending on what is running in the toolbox.

For example, Rails, when executed with `rails db:migrate` will interpret this VERSION to signify something that was not intended, and causing failures.

The fedora version is not as useful in the container, and we always have /etc/os-release. I believe the environment should be as close to a non containerized system as possible. I'd suggest to remove VERSION from the Dockerfile, or unset it later on.

**Comment by debarshiray** [comment] 2019-10-29 20:33
Yes, I don't disagree.

The `VERSION` only exists in the Dockerfile because the [Fedora guidelines](https://docs.fedoraproject.org/en-US/containers/guidelines/creation/) mandate it.

**Comment by debarshiray** [comment] 2020-01-10 18:18
Duplicate of https://github.com/containers/toolbox/issues/188

**Closed by debarshiray** 2020-01-10 18:18 UTC
