### ISSUE TITLE
toolbox cannot create container storage

### ISSUE THREAD

**Issue by rhjostone** [containers/toolbox#1128] opened 2022-09-25 04:47 UTC
**Describe the bug**

Output of `toolbox -vvv create --image registry.fedoraproject.org/fedora-toolbox:36`:

```
DEBU[0000] setting container name fedora-toolbox-36     
DEBU[0000] Loading seccomp profile from "/usr/share/containers/seccomp.json" 
INFO[0000] Sysctl net.ipv4.ping_group_range=0 0 ignored in containers.conf, since Network Namespace set to host 
DEBU[0000] Adding mount /sys                            
DEBU[0000] Adding mount /proc                           
DEBU[0000] Allocated lock 0 for container 6db688456ece41a460264ea5b533b1af61e6551b619082f69f456868d9f3a549 
DEBU[0000] parsed reference into "[overlay@/home/jostone/.local/share/containers/storage+/run/user/117340]@2110dbbc33d288a81b2c6f8658130f7c6dc46704d32eb13bb5b30f6e24ee6125" 
DEBU[0000] exporting opaque data as blob "sha256:2110dbbc33d288a81b2c6f8658130f7c6dc46704d32eb13bb5b30f6e24ee6125" 
DEBU[0000] Cached value indicated that idmapped mounts for overlay are not supported 
DEBU[0000] Check for idmapped mounts support            
DEBU[0000] overlay: mount_data=lowerdir=/home/jostone/.local/share/containers/storage/overlay/l/HNE5Q4LGADXLMHA564RDNDKC3V:/home/jostone/.local/share/containers/storage/overlay/l/WR5RX5SFJGLJNOMJFTTHMZXBN7,upperdir=/home/jostone/.local/share/containers/storage/overlay/5f00910e9759e6563627c6c748182b4a6167aa424bc77036e914927ec704bd29/diff,workdir=/home/jostone/.local/share/containers/storage/overlay/5f00910e9759e6563627c6c748182b4a6167aa424bc77036e914927ec704bd29/work, 
DEBU[0000] Failed to create container fedora-toolbox-36(6db688456ece41a460264ea5b533b1af61e6551b619082f69f456868d9f3a549): creating an ID-mapped copy of layer "343167cc2fbb0fdecd837ac6e0a007db69329f36f6c23a3ba9fac58a3713ff3f": error during chown: link usr/bin/perl usr/bin/perl5.34.1: no such file or directory: exit status 1 
Error: error creating container storage: creating an ID-mapped copy of layer "343167cc2fbb0fdecd837ac6e0a007db69329f36f6c23a3ba9fac58a3713ff3f": error during chown: link usr/bin/perl usr/bin/perl5.34.1: no such file or directory: exit status 1
Error: failed to create container fedora-toolbox-36
```

**Steps how to reproduce the behaviour**
1. Run `toolbox -vvv create --image registry.fedoraproject.org/fedora-toolbox:36`
2. Confirm pulling container image from registry if it hasn't already been pulled
3. View log output

**Expected behaviour**
Toolbox creates a new toolbox container which can then be entered with `toolbox enter`

**Actual behaviour**
Toolbox fails to create a container

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.3`

**Toolbox package info (`rpm -q toolbox`)**
 `toolbox-0.0.99.3-6.fc36.x86_64`

**Output of `podman version`**
```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 10:42:17 2022
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`toolbox-0.0.99.3-6.fc36.x86_64`

**Info about your OS**
`Fedora Linux 36.20220924.0 (Silverblue)`

**Additional context**

This issue is happening on a fresh Silverblue install which has files migrated from an older install.

UID was originally 1000 on Silverblue, but remapped UID to reflect the old system.

```
[jostone@fedora ~]$ cat /etc/subgid /etc/subuid
jostone:231072:65536
jostone:231072:65536
[jostone@fedora ~]$ toolbox list -i
IMAGE ID      IMAGE NAME                                    CREATED
2110dbbc33d2  registry.fedoraproject.org/fedora-toolbox:36  7 weeks ago
```

**Comment by debarshiray** [comment] 2022-10-24 19:56
>  toolbox-0.0.18-2.fc32.noarch

Are you really using a toolbox RPM from Fedora 32 on Fedora 36?  :)

If so, I would suggest using the toolbox RPM that comes with Fedora 36.

**Comment by gordonmessmer** [comment] 2022-10-24 21:18
There are a couple of errors or likely errors in the report (mismatch between toolbox --version and rpm -q toolbox, and toolbox package version reported where podman version is requested), but I'm seeing the same problem as the reporter, on Fedora 36, with toolbox-0.0.99.3-6.fc36.x86_64

**Comment by debarshiray** [comment] 2022-10-27 13:40
@gordonmessmer I see.  Did you also make changes to your `/etc/subuid` and `/etc/subgid`?

> UID was originally 1000 on Silverblue, but remapped UID to reflect the old
> system.

I see that you only have one line in your `/etc/subuid` and `/etc/subgid`, so I am wondering why you changed the mapping.

What was the mapping on the *old system*?  Did you copy over some images and containers from the old system?

Does the problem go away if you delete all containers and images, and re-create everything from scratch?  Or if you use something like `podman system reset`?

**Comment by gordonmessmer** [comment] 2022-10-27 18:31
```
$ id
uid=556600005(gordon) gid=556600005(gordon) groups=556600005(gordon),10(wheel),135(mock) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

$ grep gordon /etc/sub?id
/etc/subgid:gordon:100000:65536
/etc/subuid:gordon:100000:65536
```

`podman system reset` did resolve the problem on my system.

I *might* be able to restore a backup if tracking down the cause of the problem would be of interest.

**Comment by rhjostone** [comment] 2022-11-02 18:23
@debarshiray 

> > toolbox-0.0.18-2.fc32.noarch
> 
> Are you really using a toolbox RPM from Fedora 32 on Fedora 36? :)
> 
> If so, I would suggest using the toolbox RPM that comes with Fedora 36.

Oh, that was actually a remnant of the original bug report template:

https://github.com/containers/toolbox/issues/new?assignees=&labels=1.+Bug&template=bug-report.md&title=

The actual version is this:

```
$ rpm -q toolbox 
toolbox-0.0.99.3-6.fc36.x86_64
```

I was able to fix this issue on my own using `podman system reset` though.

**Comment by debarshiray** [comment] 2022-11-21 12:20
@gordonmessmer @rhjostone Thanks a lot for your persistence and eagerness to help debug this issue!

Let's close this one for the time being.  We can revisit it later if it pops up again.

**Closed by debarshiray** 2022-11-21 12:20 UTC
Labels: 1. Bug
