### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by bkoropoff** [containers/toolbox#1181] opened 2022-11-29 00:53 UTC
**Describe the bug**

There have been several important fixes in git since the last release in 2021.  I hit https://github.com/containers/toolbox/issues/157 in particular on Fedora Silverblue 37.

**Comment by debarshiray** [comment] 2022-11-29 01:18
Duplicate of https://github.com/containers/toolbox/issues/1088

**Closed by debarshiray** 2022-11-29 01:18 UTC
Labels: 1. Bug
