### ISSUE TITLE
Podman commands inside toolbox

### ISSUE THREAD

**Issue by BobyMCbobs** [containers/toolbox#680] opened 2021-01-25 02:08 UTC
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to `podman` commands inside toolbox.

**Describe the solution you'd like**
Podman pass through or access to managing Podman containers as the host user.

**Describe alternatives you've considered**
Not living inside of a `toolbox` container.

**Additional context**
I like having a contained mutable environment, however it is useful for one of my workflows to be able to bring up containers outside of a toolbox container.

I understand there may be some extra things around getting this to work - such as through `podman service` or `flatpak --host /bin/bash`, etc...

**Comment by debarshiray** [comment] 2021-02-10 18:19
Yes, this is a duplicate of https://github.com/containers/toolbox/issues/145

**Closed** 2021-02-10 18:19 UTC
Labels: feature request
