### ISSUE TITLE
Copy terminfo from host into toolbox container

### ISSUE THREAD

**Issue by nivekuil** [containers/toolbox#1048] opened 2022-05-10 00:22 UTC
**Is your feature request related to a problem? Please describe.**
Basically https://github.com/containers/toolbox/issues/505

**Describe the solution you'd like**
The related issue was resolved by adding a warning. Could toolbox solve this problem for the user by mounting/copying the terminfo directories from the host into the toolbox container when it's created?

**Additional context**
Kitty can install the terminfo automatically and an organization might provision host machines with particular terminfo settings. Adding this feature would make using toolbox more convenient in these cases.

**Comment by debarshiray** [comment] 2022-09-10 07:28
I wouldn't want to overwrite the terminfo entries in the host, because that will prevent a developer from playing with the terminfo definitions across multiple environments.  eg., if someone working on terminal emulators wants to look at the definitions across different distributions.

In theory, if the system administrator set up some specific terminfo definitions on the host, then we should replicate them inside the container.  The question is, are there any well-defined locations for system administrators that doesn't involve looking at `TERMINFO` or `TERMINFO_DIRS`?  Locations like `/usr/share/terminfo` and `/lib/terminfo` are for the OS, not the sysadmin.

**Comment by debarshiray** [comment] 2022-09-10 07:31
Do you have a real-world use case?  Is it about using Alacritty and having to install the terminfo definition separately in the container?  Or do you have a real example of an organization provisioning machines with custom definitions?

The entire filesystem hierarchy from the host is available inside the container's `/run/host`.  A user could pick and choose anything they want for bind mounting.  However, that needs to be done after every boot, which is a bit annoying.

So, you can script something into your shell start-up scripts.  In the future, we might make it possible to extend the list of bind mounts through our configuration files.

**Comment by sangsatori** [comment] 2022-09-30 22:00
My workaround for lack of terminfo for [Kitty](https://github.com/kovidgoyal/kitty) within my toolbox container was to just run

```sh
sudo ln -s  /run/host/usr/share/terminfo/x/xterm-kitty /usr/share/terminfo/x/xterm-kitty
```

once and leave the rest as-is.

I suppose alternatively something like this could also be done.

```sh
# in ~/.bashrc
# check whether we're in a toolbox container
if [ -f /run/.toolboxenv ]; then
  # override $TERMINFO and $TERMINFO_DIRS here
fi
```

**Comment by debarshiray** [comment] 2022-10-25 18:54
Yes, a symbolic link can be better than bind mounts because they persist, as long as you don't run into oddities caused by symlinks.  :)

Hacking something into the shell's start-up scripts is also another option, yes.

**Comment by debarshiray** [comment] 2022-10-25 19:04
I am inclined to leave it as it is for the time being with the error adding in https://github.com/containers/toolbox/issues/505

> In theory, if the system administrator set up some specific terminfo
> definitions on the host, then we should replicate them inside the
> container. The question is, are there any well-defined locations for
> system administrators that doesn't involve looking at TERMINFO or
> TERMINFO_DIRS? Locations like /usr/share/terminfo and /lib/terminfo
> are for the OS, not the sysadmin.

I suppose we could bring in all the terminfo entries from the host into the container at some private Toolbx specific location and add it to `TERMINFO_DIRS`.  As per `terminfo(5)`, `TERMINFO_DIRS` is read before the compiled-in and system locations.

I just don't know what can of worms this will open, if we do it unconditionally, and doing it conditionally will add a lot of complexity to the code.  :/

**Comment by debarshiray** [comment] 2022-10-25 19:10
I am tentatively closing this, until this becomes a bigger problem.  Thanks for stopping by!

**Closed by debarshiray** 2022-10-25 19:10 UTC
Labels: 1. Feature request, 2. CLI
