### ISSUE TITLE
No new release since Dec 2021

### ISSUE THREAD

**Issue by infra-monkey** [containers/toolbox#1229] opened 2023-02-04 09:57 UTC
This project is very active and has a lot of commits , fixes and enhancements that are not available in the distros.
Latest release 0.99.3 is from Dec 2021.

I am personally very interested in having https://github.com/containers/toolbox/pull/1219 available in Fedora.
I am sure that a lot of folks would love to get the goodies you cooked up too :)

Will there be a new release soon that users can envoy?

**Comment by debarshiray** [comment] 2023-02-09 15:23
Duplicate of https://github.com/containers/toolbox/issues/1088

**Comment by debarshiray** [comment] 2023-02-09 15:24
Soon, soon.  :)

There's always that one other thing to wrap up, but very soon now.

**Closed by debarshiray** 2023-02-09 15:24 UTC
Labels: 1. Feature request
