### ISSUE TITLE
Cannot use the host's Docker socket

### ISSUE THREAD

**Issue by hholst80** [containers/toolbox#430] opened 2020-05-05 12:31 UTC
I have docker running on host and I want to interact with Docker engine using the /var/run/docker.sock connection. Inside the toolbox I can see it under /var/run/host/run/docker.sock with permissions 660:660 and nobody.nobody as owner. How can I configure toolbox such that I can access the socket from within a toolbox?

**Comment by debarshiray** [comment] 2020-05-13 14:01
I believe the socket at `/var/run/docker.sock` on the host is owned by a UID:GID pair that's not you. Since Toolbox runs as your UID:GID pair, only your UID:GID from the host is propagated into the container's user namespace. It means that anything from the host that's not owned by you gets `nobody:nobody` as the owner inside the container.

I don't know of a generic way to solve this, but you can locally hack past this by giving *others* access to the Docker socket. ie., `666` as the permission.

**Comment by hholst80** [comment] 2020-05-17 15:17
It is strange that I cannot access /var/run/host/run/docker.sock as root either. That should imply that root in the toolbox isn't mapped to my host user?

**Comment by debarshiray** [comment] 2020-07-28 22:56
Like I said before, only your UID:GID from the host is propagated into the Toolbox container. `root` inside the container isn't the same thing as `root` on the host.

What's the output of `ls -l /var/run/docker.sock` ?

**Comment by hholst80** [comment] 2020-08-02 12:48
And what is propagated to the outside? If I access a file as root or any other user inside the container what user will that correspond to outside the container?

If I explicitly set the user uid and gid to the user creating the toolbox I can access the /var/run/host/var/run/docker.sock as the regular user and as root inside the container, so they both map to the outside user. 

As a workaround I'm using tcp/ip instead to access the docker engine.

**Comment by debarshiray** [comment] 2020-08-04 19:51
> And what is propagated to the outside? If I access a file as root or any other user
> inside the container what user will that correspond to outside the container?

Root inside the container will correspond to some non-zero UID on the host based on the exact UID mapping of the user namespace on your system. You can look at `/proc/self/uid_map` for the full story, or just `touch` a file inside the container and check its ownership on the host.

**Comment by hholst80** [comment] 2020-08-05 07:42
In the end of the day I think this needs a more complete solution to allow host groups to be resolved for containers so that whatever I had access to do outside the container still is true inside the container. The current solution makes toolboxes less useful as an environment for any kind of tooling that requires access to server sockets like mongo, mysql or docker.

A toolbox environment should not be more limited than the host it should only expand what I can do to the toolbox environment. Well inside the toolbox env, the host should neither be more nor less accessible than outside. It should be transparent to the user that it is running inside a container when accessing the socket.

Reasonable?

**Comment by debarshiray** [comment] 2020-08-05 14:45
I guess one way to solve this would be run a *rootful* Toolbox container (ie., `sudo toolbox ...`), as opposed to a *rootless* one. That would map the actual UID 0 on the host into the container.

For various, somewhat silly, reasons `sudo toolbox ...` doesn't work at the moment, but it's on our list of things to fix.

**Comment by debarshiray** [comment] 2020-08-05 16:08
I learnt about the `run.oci.keep_original_groups` annotation from @mheon that can help with this. You can use it with `podman create` or `podman run` as:
```
$ podman run --annotation run.oci.keep_original_groups=1 --env TERM=$TERM --it --rm --userns=keep-id ...
```

Does it let you use the Docker socket from a rootless Podman container? I'd still like to see the outputs of:
```
$ ls -l /var/run/docker.sock
...
$ id
...
```

See the `crun(1)` manual for more details on what that annotation does.

**Comment by hholst80** [comment] 2020-08-06 07:30
> I'd still like to see the outputs of:

```
[om@puff ~]$ ls -l /var/run/docker.sock
srw-rw----. 1 root docker 0  5 aug 15.00 /var/run/docker.sock
[om@puff ~]$ ls -l /var/run/docker.sock -n
srw-rw----. 1 0 998 0  5 aug 15.00 /var/run/docker.sock
[om@puff ~]$ id
uid=1001(om) gid=1001(om) groups=1001(om),10(wheel),998(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[om@puff ~]$ 
```

**Comment by hholst80** [comment] 2020-08-06 07:33
> I learnt about the `run.oci.keep_original_groups` annotation from @mheon that can help with this.

How can that be integrated with the toolbox workflow?

**Comment by debarshiray** [comment] 2020-08-06 13:25
> > I learnt about the `run.oci.keep_original_groups` annotation from @mheon
> > that can help with this.
> 
> How can that be integrated with the toolbox workflow?

It depends on whether we can add annotations retroactively to existing OCI containers. If not, then we'd add it to Toolbox's `podman create ...` invocation, which will be picked up by newly created Toolbox containers.

However, before doing that, I was hoping to find out if the annotation actually works for you. See the sample Podman command above.

**Comment by debarshiray** [comment] 2020-08-19 12:51
I finally got around to playing with this.

My apologies. This wasn't the minimum set of flags needed to get it work:
> ```
> $ podman run --annotation run.oci.keep_original_groups=1 --env TERM=$TERM --it --rm --userns=keep-id ...
> ```

I had to disable SELinux inside the container with `--security-opt label=disable`, which is something Toolbox already does, to get it to work.

So, this works:
```
$ podman run --annotation run.oci.keep_original_groups=1 --env TERM=$TERM -it --rm --security-opt label=disable --volume /run:/run/host/run:rslave registry.fedoraproject.org/f31/fedora-toolbox:31 /bin/bash
# sudo dnf -y install moby-engine
...
...
# docker --host unix:///run/host/run/docker.sock version
...
...
```

**Comment by debarshiray** [comment] 2020-08-19 15:49
Somehow the `run.oci.keep_original_groups=1` annotation isn't having the intended effect when fitted into Toolbox: https://github.com/containers/podman/issues/7375

Needs more investigation.

**Comment by debarshiray** [comment] 2020-08-20 15:15
> Somehow the `run.oci.keep_original_groups=1` annotation isn't
> having the intended effect when fitted into
> Toolbox: [containers/podman#7375](https://github.com/containers/podman/issues/7375)
> 
> Needs more investigation.

So, that was due to https://github.com/containers/crun/issues/394 and is fixed in `crun-0.14`.

**Comment by debarshiray** [comment] 2020-08-20 15:26
Unfortunately, using `run.oci.keep_original_groups=1` retains the groups from the host, but overrides the user's membership in the `wheel` group inside the container. That means that you can access the Docker socket, but you can't use `sudo` anymore. That's not ideal.

**Comment by debarshiray** [comment] 2020-08-20 15:34
@giuseppe suggested in `#podman` on Freenode that we could create a socket owned by the user on the host, bind mount it inside the container, proxy the bytes to and from the Docker socket on the host.

**Comment by debarshiray** [comment] 2023-09-28 07:38
We are beginning to accumulate too many issues coming out of the same underlying cause.  Let's consolidate on https://github.com/containers/toolbox/issues/1348 because it already collects all the related issues together.

**Comment by debarshiray** [comment] 2023-09-28 07:39
Duplicate of https://github.com/containers/toolbox/issues/1348

**Closed by debarshiray** 2023-09-28 07:39 UTC
Labels: 5. Help Wanted, 1. Feature request
