### ISSUE TITLE
Container doesn't start because conmon failed to write to /proc/self/oom_score_adj: Permission denied

### ISSUE THREAD

**Issue by fchpr** [containers/toolbox#488] opened 2020-07-03 17:52 UTC
Host: `Linux archlinux 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux`

I'm running `toolbox` with an unprivileged user, `podman` itself works fine and rootless, `subuid` and `subgid` are yet configured.

I disabled `cgroups` v1 adding `systemd.unified_cgroup_hierarchy=1` and `cgroup_no_v1="all"`  kernel boot parameters.

Also solved a warning by getting `kata-runtime` installed from AUR.

Using the following `/etc/containers/container.conf`:
```
[engine]
cgroup_manager = "cgroupfs"
events_logger = "file
```

The command: `toolbox enter -vvv` throws:
```
DEBU Running as real user ID 1001                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user fch 
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Toolbox config directory is /home/fch/.config/toolbox 
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called version.PersistentPreRunE(podman --log-level debug version --format json) 
DEBU[0000] Found deprecated file /home/fch/.config/containers/containers.conf, please remove. Use /home/fch/.config/containers/containers.conf to override defaults. 
DEBU[0000] Reading configuration file "/home/fch/.config/containers/libpod.conf" 
DEBU[0000] Ignoring libpod.conf EventsLogger setting "/home/fch/.config/containers/containers.conf". Use "journald" if you want to change this setting and remove libpod.conf files. 
DEBU[0000] Reading configuration file "/etc/containers/containers.conf" 
DEBU[0000] Merged system config "/etc/containers/containers.conf": &{{[] [] containers-default-0.14.3 [] private enabled [CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] [] []  [] [] [] false [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] false false false  private k8s-file -1 slirp4netns false 2048 private /usr/share/containers/seccomp.json 65536k private host 65536} {true cgroupfs [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] ctrl-p,ctrl-q true /run/user/1001/libpod/tmp/events/events.log file [/usr/share/containers/oci/hooks.d] docker:// /pause k8s.gcr.io/pause:3.2 /usr/libexec/podman/catatonit shm   false 2048 /usr/bin/crun map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] missing false   [] [crun runc] [crun] [kata kata-runtime kata-qemu kata-fc] {false false false false false false} /etc/containers/policy.json false 3 /home/fch/.local/share/containers/storage/libpod 10 /run/user/1001/libpod/tmp /home/fch/.local/share/containers/storage/volumes} {[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman /etc/cni/net.d/}} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/fch/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/fch/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1001/containers     
DEBU[0000] Using static dir /home/fch/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1001/libpod/tmp      
DEBU[0000] Using volume path /home/fch/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] Initializing event backend file              
DEBU[0000] using runtime "/usr/bin/crun"                
DEBU[0000] using runtime "/usr/bin/kata-runtime"        
DEBU[0000] using runtime "/usr/bin/runc"                
DEBU[0000] using runtime "/usr/bin/crun"                
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Called version.PersistentPostRunE(podman --log-level debug version --format json) 
DEBU Current Podman version is 2.0.1              
DEBU Old Podman version is 2.0.1                  
DEBU Migration not needed: Podman version 2.0.1 is unchanged 
DEBU Resolving container and image names          
DEBU Container: ''                                
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'fedora-toolbox-30'               
DEBU Image: 'fedora-toolbox:30'                   
DEBU Release: '30'                                
DEBU Checking if container fedora-toolbox-30 exists 
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called exists.PersistentPreRunE(podman --log-level debug container exists fedora-toolbox-30) 
DEBU[0000] Found deprecated file /home/fch/.config/containers/containers.conf, please remove. Use /home/fch/.config/containers/containers.conf to override defaults. 
DEBU[0000] Reading configuration file "/home/fch/.config/containers/libpod.conf" 
DEBU[0000] Ignoring libpod.conf EventsLogger setting "/home/fch/.config/containers/containers.conf". Use "journald" if you want to change this setting and remove libpod.conf files. 
DEBU[0000] Reading configuration file "/etc/containers/containers.conf" 
DEBU[0000] Merged system config "/etc/containers/containers.conf": &{{[] [] containers-default-0.14.3 [] private enabled [CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] [] []  [] [] [] false [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] false false false  private k8s-file -1 slirp4netns false 2048 private /usr/share/containers/seccomp.json 65536k private host 65536} {true cgroupfs [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] ctrl-p,ctrl-q true /run/user/1001/libpod/tmp/events/events.log file [/usr/share/containers/oci/hooks.d] docker:// /pause k8s.gcr.io/pause:3.2 /usr/libexec/podman/catatonit shm   false 2048 /usr/bin/crun map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] missing false   [] [crun runc] [crun] [kata kata-runtime kata-qemu kata-fc] {false false false false false false} /etc/containers/policy.json false 3 /home/fch/.local/share/containers/storage/libpod 10 /run/user/1001/libpod/tmp /home/fch/.local/share/containers/storage/volumes} {[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman /etc/cni/net.d/}} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/fch/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/fch/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1001/containers     
DEBU[0000] Using static dir /home/fch/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1001/libpod/tmp      
DEBU[0000] Using volume path /home/fch/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] Initializing event backend file              
DEBU[0000] using runtime "/usr/bin/crun"                
DEBU[0000] using runtime "/usr/bin/kata-runtime"        
DEBU[0000] using runtime "/usr/bin/runc"                
DEBU[0000] using runtime "/usr/bin/crun"                
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Called exists.PersistentPostRunE(podman --log-level debug container exists fedora-toolbox-30) 
DEBU Calling org.freedesktop.Flatpak.SessionHelper.RequestSession 
DEBU Starting container fedora-toolbox-30         
Error: failed to start container fedora-toolbox-30
```

**Comment by HarryMichal** [comment] 2020-07-03 19:38
Hi @fchpr! Could you share the output of `podman logs fedora-toolbox-30`?? The problem is with the container not starting due to some error during the initialization. The command should tell us more why it failed.

**Comment by fchpr** [comment] 2020-07-03 20:01
> Hi @fchpr! Could you share the output of `podman logs fedora-toolbox-30`?? The problem is with the container not starting due to some error during the initialization. The command should tell us more why it failed.

Thank you very much for such quick response! The mentioned command returns nothing...

So instead I runned: `podman --log-level debug start fedora-toolbox-30` which returns:
```
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called start.PersistentPreRunE(podman --log-level debug start fedora-toolbox-30) 
DEBU[0000] Found deprecated file /home/fch/.config/containers/containers.conf, please remove. Use /home/fch/.config/containers/containers.conf to override defaults. 
DEBU[0000] Reading configuration file "/home/fch/.config/containers/libpod.conf" 
DEBU[0000] Ignoring libpod.conf EventsLogger setting "/home/fch/.config/containers/containers.conf". Use "journald" if you want to change this setting and remove libpod.conf files. 
DEBU[0000] Reading configuration file "/etc/containers/containers.conf" 
DEBU[0000] Merged system config "/etc/containers/containers.conf": &{{[] [] containers-default-0.14.3 [] private enabled [CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] [] []  [] [] [] false [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] false false false  private k8s-file -1 slirp4netns false 2048 private /usr/share/containers/seccomp.json 65536k private host 65536} {true cgroupfs [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] ctrl-p,ctrl-q true /run/user/1001/libpod/tmp/events/events.log file [/usr/share/containers/oci/hooks.d] docker:// /pause k8s.gcr.io/pause:3.2 /usr/libexec/podman/catatonit shm   false 2048 /usr/bin/crun map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] missing false   [] [crun runc] [crun] [kata kata-runtime kata-qemu kata-fc] {false false false false false false} /etc/containers/policy.json false 3 /home/fch/.local/share/containers/storage/libpod 10 /run/user/1001/libpod/tmp /home/fch/.local/share/containers/storage/volumes} {[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman /etc/cni/net.d/}} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/fch/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/fch/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1001/containers     
DEBU[0000] Using static dir /home/fch/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1001/libpod/tmp      
DEBU[0000] Using volume path /home/fch/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] Initializing event backend file              
DEBU[0000] using runtime "/usr/bin/kata-runtime"        
DEBU[0000] using runtime "/usr/bin/runc"                
DEBU[0000] using runtime "/usr/bin/crun"                
DEBU[0000] using runtime "/usr/bin/crun"                
INFO[0000] Setting parallel job count to 13             
DEBU[0000] mounted container "e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe" at "/home/fch/.local/share/containers/storage/vfs/dir/0d1ac11acd5037025c8100d4be763344707731d90dd63cc3bb6739d5ad6503fa" 
DEBU[0000] Created root filesystem for container e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe at /home/fch/.local/share/containers/storage/vfs/dir/0d1ac11acd5037025c8100d4be763344707731d90dd63cc3bb6739d5ad6503fa 
DEBU[0000] /etc/system-fips does not exist on host, not mounting FIPS mode secret 
DEBU[0000] Setting CGroup path for container e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe to /libpod_parent/libpod-e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe 
DEBU[0000] set root propagation to "rslave"             
DEBU[0000] reading hooks from /usr/share/containers/oci/hooks.d 
DEBU[0000] Created OCI spec for container e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe at /home/fch/.local/share/containers/storage/vfs-containers/e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe/userdata/config.json 
DEBU[0000] /usr/bin/conmon messages will be logged to syslog 
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe -u e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe -r /usr/bin/crun -b /home/fch/.local/share/containers/storage/vfs-containers/e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe/userdata -p /run/user/1001/containers/vfs-containers/e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe/userdata/pidfile -n fedora-toolbox-30 --exit-dir /run/user/1001/libpod/tmp/exits --socket-dir-path /run/user/1001/libpod/tmp/socket -l k8s-file:/home/fch/.local/share/containers/storage/vfs-containers/e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe/userdata/ctr.log --log-level debug --syslog --conmon-pidfile /run/user/1001/containers/vfs-containers/e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/fch/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1001/containers --exit-command-arg --log-level --exit-command-arg error --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /run/user/1001/libpod/tmp --exit-command-arg --runtime --exit-command-arg /usr/bin/crun --exit-command-arg --storage-driver --exit-command-arg vfs --exit-command-arg --events-backend --exit-command-arg file --exit-command-arg container --exit-command-arg cleanup --exit-command-arg e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe]"
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Received: -1                                 
DEBU[0000] Cleaning up container e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe 
DEBU[0000] Network is already cleaned up, skipping...   
DEBU[0000] unmounted container "e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe" 
Error: unable to start container "e6fcdfd225f3b60c490e88e07ac4c0bf7529cb85dda604cd4c3a88d519a93cbe": make `/home/fch/.local/share/containers/storage/vfs/dir/0d1ac11acd5037025c8100d4be763344707731d90dd63cc3bb6739d5ad6503fa` private: Permission denied: OCI runtime permission denied error
```

**Comment by Bearbobs** [comment] 2020-09-06 07:21
same issue. I'm facing

**Comment by debarshiray** [comment] 2021-11-16 01:00
This looks like a (old?) Podman bug.  Are you still facing this?

**Comment by debarshiray** [comment] 2022-10-14 01:41
It's been almost a year.  Closing.

Please feel free to re-open if you have reason to believe otherwise.

**Closed by debarshiray** 2022-10-14 01:41 UTC
Labels: 1. Bug
