### ISSUE TITLE
Containers have "running" states, but no "stop" command

### ISSUE THREAD

**Issue by hadess** [containers/toolbox#645] opened 2020-12-10 10:24 UTC
If containers have a running state, and a run command, I'd expect a way "stop" them to make them non-running. I'd expect `toolbox rm` to tell me what to do in that case.
```sh
$ rpm -q toolbox
toolbox-0.0.97-1.fc33.x86_64
$ toolbox list
IMAGE ID      IMAGE NAME                                        CREATED
1e7672b5e517  registry.fedoraproject.org/f32/fedora-toolbox:32  5 weeks ago
7f6c60b1df02  registry.fedoraproject.org/f34/fedora-toolbox:34  2 months ago

CONTAINER ID  CONTAINER NAME     CREATED         STATUS   IMAGE NAME
42e68b6bb7db  fedora-toolbox-34  12 minutes ago  running  registry.fedoraproject.org/f34/fedora-toolbox:34
$ toolbox rm 42e68b6bb7db
Error: container 42e68b6bb7db is running
$ toolbox stop 42e68b6bb7db
Error: unknown command "stop" for "toolbox"
Run 'toolbox --help' for usage.
```

**Comment by hadess** [comment] 2020-12-10 15:00
`podman stop <id>` works. toolbox should probably offer to stop the container when asking to remove it.

**Comment by debarshiray** [comment] 2020-12-18 16:39
There's a `--force` flag to imitate Podman itself.

But, yeah, I agree that we need a way to automatically stop the containers. This is a duplicate of https://github.com/containers/toolbox/issues/114

**Closed by debarshiray** 2020-12-18 16:39 UTC
Labels: bug
