### ISSUE TITLE
Mock broke due to explicitly passing a source to 'mount -o remount' (regression in Mock commit 163b24e77c8fe0f2)

### ISSUE THREAD

**Issue by YaLTeR** [containers/toolbox#761] opened 2021-05-10 08:43 UTC
**Describe the bug**
```
└─ fedpkg --release f34 mockbuild

setting SOURCE_DATE_EPOCH=1618272000
Wrote: /var/home/yalter/source/pkg/gnome-shell/gnome-shell-40.0-3.1.fc34.src.rpm
INFO: mock.py version 2.10 starting (python version = 3.9.4, NVR = mock-2.10-1.fc34)...
Start(bootstrap): init plugins
INFO: selinux disabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
INFO: Start(/var/home/yalter/source/pkg/gnome-shell/gnome-shell-40.0-3.1.fc34.src.rpm)  Config(fedora-34-x86_64)
Start: clean chroot
Finish: clean chroot
Start(bootstrap): chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start(bootstrap): cleaning package manager metadata
Finish(bootstrap): cleaning package manager metadata
INFO: enabled HW Info plugin
Mock Version: 2.10
INFO: Mock Version: 2.10
Finish(bootstrap): chroot init
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
Start: unpacking root cache
Finish: unpacking root cache
INFO: enabled package manager cache
Start: cleaning package manager metadata
Finish: cleaning package manager metadata
INFO: enabled HW Info plugin
Mock Version: 2.10
INFO: Mock Version: 2.10
ERROR: Exception(/var/home/yalter/source/pkg/gnome-shell/gnome-shell-40.0-3.1.fc34.src.rpm) Config(fedora-34-x86_64) 0 minutes 4 seconds
INFO: Results and/or logs in: /var/home/yalter/source/pkg/gnome-shell/results_gnome-shell/40.0/3.1.fc34
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Finish: clean chroot
ERROR: Command failed: 
 # /bin/mount -n -o remount,private,rbind /var/lib/mock/fedora-34-x86_64/root /var/lib/mock/fedora-34-x86_64-bootstrap/root/var/lib/mock/fedora-34-x86_64/root

Could not execute mockbuild: Failed to execute command.
```

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.1

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.1-1.fc34.x86_64`

**Output of `podman version`**
```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16
Built:        Thu Apr 22 16:11:28 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-3.1.2-1.fc34.x86_64`

**Info about your OS**
Fedora Silverblue 34.20210506.0 (the one before toolbox broke)

**Additional context**
I'm fairly certain it used to work before on this F34 toolbox. I haven't used it in a while but today it doesn't work, I'm not sure if it's host updates or toolbox updates that caused it.

**Comment by anthr76** [comment] 2021-05-12 11:35
Semi related: https://github.com/containers/toolbox/issues/741

**Comment by shdwchn10** [comment] 2021-07-02 05:46
I can also reproduce this issue

**Comment by HarryMichal** [comment] 2021-07-07 11:30
Hi @YaLTeR! Thank you for opening the issue. I can also reproduce this behaviour.

In the past this worked for sure as I did all my packaging work inside of a toolbox. Will investigate.

**Comment by HarryMichal** [comment] 2021-07-08 11:58
I spent some time investigating and culprit is not the entry-point, nor `/tmp` being a bind mount to `/run/host/tmp`.

**Comment by cheese** [comment] 2021-07-24 10:24
We also talk about this on the mock side: https://github.com/rpm-software-management/mock/issues/715

mock  2.10 introduced using a remount to apply the mount options. But remount is not alllowed in a Toolbox container:

Host environment `rpm-ostree status -bv`:

```
State: idle
AutomaticUpdates: disabled
BootedDeployment:
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210723.0 (2021-07-23T00:50:17Z)
                BaseCommit: 8d9e776df873411268bc5a317e55dced9bc16d97cac5e1919616dce1f18bdab2
                            ├─ repo-0 (2021-04-23T10:47:57Z)
                            ├─ repo-1 (2021-07-23T00:16:29Z)
                            └─ repo-2 (2021-07-23T00:19:18Z)
                    Commit: a3e60b48ba38be3f5ed01b81112bb734118d2f59168386a7cff2490a6916c303
                            ├─ fedora-cisco-openh264 (2021-02-23T00:49:00Z)
                            ├─ updates (2021-07-24T02:08:24Z)
                            ├─ fedora (2021-04-23T10:47:57Z)
                            └─ updates-archive (2021-07-24T02:46:54Z)
                    Staged: no
                 StateRoot: fedora
              GPGSignature: 1 signature
                            Signature made Fri 23 Jul 2021 08:50:23 AM CST using RSA key ID 1161AE6945719A39
                            Good signature from "Fedora <fedora-34-primary@fedoraproject.org>"
      ReplacedBasePackages: mutter 40.3-1.fc34 -> 40.3-2.fc34
           LayeredPackages: adobe-source-han-sans-cn-fonts adobe-source-han-serif-cn-fonts fcitx5-anthy fcitx5-autostart fcitx5-chinese-addons fcitx5-gtk2 fcitx5-gtk3 fcitx5-qt-module kcm-fcitx5 langpacks-en libvirt-daemon-kvm
                            mozilla-openh264 strace virt-manager
```

Simplified reproducing commands:

```
[cheese@xxx ~]$ toolbox create test-mount
Created container: test-mount: | 
Enter with: toolbox enter test-mount
[cheese@xxx ~]$ toolbox enter test-mount
⬢[cheese@toolbox ~]$ sudo mkdir /var/lib/m
⬢[cheese@toolbox ~]$ sudo mount -n -o bind /usr/local /var/lib/m
⬢[cheese@toolbox ~]$ sudo mount -n -o remount,ro,bind /usr/local /var/lib/m
mount: /var/lib/m: permission denied.
```

**Comment by cheese** [comment] 2021-07-24 14:18
I filed a bug to Fedora util-linux [1] and created a pr[2] to mock to work around the issue. So this seems not the fault of Toolbox.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1985628
[2] https://github.com/rpm-software-management/mock/pull/759

**Comment by felipeborges** [comment] 2021-11-22 15:17
My mockbuilds were failing with

```
ERROR: Command failed: 
 # /bin/mount -n -o remount,private,rbind /var/lib/mock/fedora-rawhide-x86_64/root /var/lib/mock/fedora-rawhide-x86_64-bootstrap/root/var/lib/mock/fedora-rawhide-x86_64/root

Could not execute mockbuild: Failed to execute command.
```

But after upgrading from mock-2.12 to mock-2.15 the issue is resolved and mockbuilds seem to work as expected.

**Comment by debarshiray** [comment] 2021-11-23 15:26
Duplicate of https://github.com/rpm-software-management/mock/issues/715

**Comment by debarshiray** [comment] 2021-11-23 15:27
Thanks for chasing this down, @cheese!

**Closed** 2021-11-23 15:29 UTC
Labels: 1. Regression, 2. Container Realm
