### ISSUE TITLE
`toolbox run` allows setting environment variables

### ISSUE THREAD

**Issue by owenthereal** [containers/toolbox#593] opened 2020-10-23 21:35 UTC
**Is your feature request related to a problem? Please describe.**

It would be nice that `toolbox run` allows setting environment variables so that it's available in the container, similar to `podman exec --env`. My use case is that I am running a command that behaves differently based on an environment variable and currently there is no way to feed that into the container.

**Describe the solution you'd like**

It would be nice to add a `--env` flag for `toolbox run`:

`toolbox run --env FOO=BAR CMD`

**Describe alternatives you've considered**

N/A

**Additional context**
Add any other context or screenshots about the feature request here. If a different tool has the functionality you're requesting, share it here.

**Comment by debarshiray** [comment] 2020-12-21 10:33
Duplicate of https://github.com/containers/toolbox/issues/618

**Closed by debarshiray** 2020-12-21 10:33 UTC
Labels: feature request
