### ISSUE TITLE
toolbox not inheriting shell on enter

### ISSUE THREAD

**Issue by mybigman** [containers/toolbox#475] opened 2020-06-20 13:16 UTC
Toolbox container continues to use bash shell even though I have set it to use fish shell.

I have to manually invoke the fish.

```
> cat /etc/os-release 
NAME=Fedora
VERSION="32.20200603.0 (IoT Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32.20200603.0 (IoT Edition)"
```

```
> rpm-ostree db diff
ostree diff commit from: rollback deployment (f2608adc929eb69bb52f186264a8b7822320909039a9d4f0c91d93510572ea22)
ostree diff commit to:   booted deployment (740b3da6776d33a3a0e0b87a3c44ec414effbbb311c5bfd4e9a29fc11b204d86)
Added:
  flatpak-session-helper-1.6.3-1.fc32.x86_64
  toolbox-0.0.18-2.fc32.noarch
```

**Comment by debarshiray** [comment] 2020-07-23 16:17
Do you have `fish` installed inside your toolbox container?

What did you mean by *set it to use fish shell*? Is the `SHELL` environment variable on the host set to `fish`?

**Comment by debarshiray** [comment] 2020-07-24 14:33
This seems to work as it's supposed to. I tested with `zsh`

I am closing the issue, but please do leave a comment and let us know if you still cannot get it to work.

**Comment by debarshiray** [comment] 2020-07-24 14:36
Duplicate of #https://github.com/containers/toolbox/issues/18

**Closed by debarshiray** 2020-07-24 14:36 UTC
Labels: bug

**Comment by HarryMichal** [comment] 2020-07-24 14:53
Even though Toolbox should behave correctly, the fact this issue was opened is in my opinion enough prove to add some kind of a warning that says the default shell is not available and the fallback option (`/bin/bash`) will be used instead. Might be worth opening a separate issue and marking it as a good-first-issue.

**Comment by debarshiray** [comment] 2020-07-24 15:51
Yes, that sounds like a good idea.
