### ISSUE TITLE
OpenShift Prow onboarding: Create OWNERS file to use

### ISSUE THREAD

**Issue by cgwalters** [containers/toolbox#301] opened 2019-10-14 15:54 UTC
The CoreOS group is [increasingly using OpenShift Prow](https://github.com/coreos/fedora-coreos-tracker/issues/263).

If you wish to use the OpenShift Prow instance, please [create an `OWNERS` file](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md) in this repository to indicate agreement.  

[Here's an example](https://github.com/containers/libpod/blob/master/OWNERS) from this Github organization.

If you do not wish to have this repository onboarded to OpenShift Prow, simply close this issue.

**Comment by cgwalters** [comment] 2019-10-14 15:56
For background on this, I think having a "merge bot" is really useful, and Prow is a fine instance of it.  The OpenShift CI cluster also can indirectly sponsor projects with CI resources via using its Prow instance.

**Comment by debarshiray** [comment] 2019-10-14 19:00
Yes, sure. I added an `OWNERS` file in https://github.com/containers/toolbox/pull/302

Two things came to my mind.

@HarryMichal did a bunch of work adding continuous integration tests using [Zuul](https://zuul-ci.org/) to test Toolbox changes against Podman and vice versa in https://github.com/containers/toolbox/pull/250 They have fallen off our radar due to the ongoing chaos caused by Cgroups v2, but we should finalize them soon. How are they affected by OpenShift Prow?

Should we synchronize the contents of `OWNERS` with the current roles assigned in the project settings? The project settings have evolved in a somewhat ad hoc and organic way. eg., some of the admins are only there to allow moving issues to other components in the *containers* organization. Maybe we should clean that up by having one of us be an admin in the *containers* organization?

**Comment by HarryMichal** [comment] 2019-10-24 20:44
> For background on this, I think having a "merge bot" is really useful, and Prow is a fine instance of it. The OpenShift CI cluster also can indirectly sponsor projects with CI resources via using its Prow instance.

I'm a bit against having a `merge bot`. Using merge bot could lead to some unnecessary commit junk. I think our current strategy of handling PRs is quite alright (as in speed) even though it's done manually. And if we split the responsiblity in the future then it'll be even more fine.

**Comment by cgwalters** [comment] 2019-10-25 14:13
The argument for a merge bot is multiple.  In Project Atomic CI we used Homu, see
https://github.com/servo/homu#why-is-it-needed

It's not quite about speed so much as automating rules around merging.

**Comment by debarshiray** [comment] 2020-01-25 14:32
Ping.

Where do we stand on this? Shall we merge https://github.com/containers/toolbox/pull/302 ?

**Comment by HarryMichal** [comment] 2020-12-18 17:10
I'm closing this as we never got to merge this before. I kinda understand the motivation behind this but I don't think it to be very beneficial.

**Closed by HarryMichal** 2020-12-18 17:10 UTC
Labels: enhancement
