### ISSUE TITLE
Feature request: add `sqlite` to the fedora image

### ISSUE THREAD

**Issue by 1player** [containers/toolbox#1238] opened 2023-02-16 10:33 UTC
**Is your feature request related to a problem? Please describe.**

Tab completion of `dnf install` commands fails on a stock fedora-toolbox image because SQLite is not installed. 

Pressing `dnf install<TAB>` prints the following error: 

```
cm_dnf_query_db:2: command not found: sqlite3
```

Installing the `sqlite` package fixes it and restores tab completion.

**Describe the solution you'd like**

Include `sqlite` in the generated fedora-toolbox image.

**Additional context**

Tested in a container created with `distrobox create fedora37 --image registry.fedoraproject.org/fedora-toolbox:37`

**Comment by debarshiray** [comment] 2023-03-01 20:30
Interesting.

The goal with the `fedora-toolbox` images is to offer a similar command line user experience to that on Fedora Silverblue and Workstation.  A quick test on a fresh new Fedora 37 Workstation VM says that `sqlite` isn't installed by default.

I also can't reproduce the error by TABing on the command line.  On the host:
```
# dnf check-update
...
# dnf install z<TAB><TAB>
Display all 298 possibilities? (y or n)
```

... and inside a Toolbx container:
```
# dnf check-update
...
# dnf install z<TAB><TAB>
```

**Comment by debarshiray** [comment] 2023-03-01 20:31
If you can reliably reproduce the error, and think that `sqlite` really should be part of the default Fedora Silverblue and Workstation installation, then I'd suggest [pursuing](https://pagure.io/fedora-workstation/) that first.

**Comment by debarshiray** [comment] 2023-04-01 11:43
Interesting, this time I got suggestions from DNF inside a Toolbx container:
```
⬢# dnf install z
Display all 323 possibilities? (y or n)
```

... but still no error involving `sqlite3`.

**Comment by debarshiray** [comment] 2023-04-01 11:43
Also ...

> Tested in a container created with distrobox create

... cool!  :)

**Comment by debarshiray** [comment] 2023-06-28 09:00
Closing.

**Closed by debarshiray** 2023-06-28 09:00 UTC
Labels: 1. Feature request
