### ISSUE TITLE
Separate home directories for each toolbox

### ISSUE THREAD

**Issue by hunger** [containers/toolbox#1044] opened 2022-05-05 18:23 UTC
I already have a container based development workflow (using manually created systemd.nspawn containers) but would like to switch over to a properly maintained solution like toolbox.

I have several customers that I need to keep separate from each other. In my current workflow I have a root-owned folder in ~/.local/share/machines, with sub-folders owned by my user.

When I start my development container, it checks for ~/.local/share/machine/<CONTAINER_NAME> and if that exists, then it bind-mounts that as my home directory into the container. It also bind-mounts the  ~/Download folder into all container images, so that I can (ab-)use that to transfer data between different containers;-) That way I can have private keys and whatever other customer related information separate from each other and not even available to programs that can access my home directory (as they can not enter ~/-local/share/machines as that is only accessible by root:-)

If there is no folder with the same name as the container in ~/.local/share/machines, then I mount the normal /home/USERNAME (much less sophisticated than what toolboox does!)

Would a similar setup be possible somehow using toolbox? I did not find anything in the manual pages, so I think this can be considered a feature request;-)

**Comment by nodefourtytwo** [comment] 2022-06-13 09:32
If you wrote a script for your workflow, would you care sharing it?

**Comment by hunger** [comment] 2022-06-17 18:49
I doubt it is useful anywhere but in my specific setup: I generate container filesystems from a configuration file and the same file also generates systemd-nspawn settings and a start script.

My setup is strictly less useful than toolbox: I have to restart my containers whenever the network changes:-/

**Comment by jonleivent** [comment] 2022-07-26 17:11
Would using bubblewrap outside toolbox to do the bind mounting work for you?  Something like:
```
bwrap --bind $HOME/.local/share/machine/<CONTAINER_NAME> $HOME toolbox enter ...
```
Actually, since the toolboxes are themselves stored in the home dir, I think under .config/toolbox and .local/share/containers, you'd have your choice of either starting out with those within your container -- meaning, you created the toolbox with:
```
bwrap --bind $HOME/.local/share/machine/<CONTAINER_NAME> $HOME toolbox create ...
```
Or, first bind mounting your own .config/toolbox and .local/share/containers into your container with initial --bind options to that bwrap toolbox enter call.  I'd probably choose the create-toolbox-within-bwrap case because I don't have a clue what sharing those toolbox folders across multiple users would do - so one per container seems safest.

I also have container-based systems I'm in the process of testing out with toolbox.  I'm not sure bwrap and toolbox work together, but I might try something like this myself.

**Comment by jonleivent** [comment] 2022-07-26 19:12
Oh - sorry - those bwrap calls should all have `--dev-bind / /` first.  I keep forgetting that.

**Comment by idkman2021** [comment] 2022-09-06 09:44
https://github.com/containers/toolbox/issues/348 so in this thread there seems to be a programming code that you can add into your ".bashrc" before "unset rc" line, and it will work. Although I don't know if using this approach has any disadvantages.

**Comment by debarshiray** [comment] 2022-10-27 17:54
Duplicate of https://github.com/containers/toolbox/issues/183

**Comment by debarshiray** [comment] 2022-10-27 18:03
Yes, this is something that has come up before several times.  Unfortunately, doing this properly is going to be a lot of work.

Various people have come up with various hacks that work for their specific use-case.  eg., some folks run `toolbox` with a overriden `HOME`.

I am going to close this issue so that the list of open issues doesn't balloon out of control, and continues to roughly reflect the items that are on the current to-do list. However, it will still be around for future reference.

**Closed** 2022-10-27 18:03 UTC

**Comment by mjlbach** [comment] 2023-03-25 23:17
Hey @debarshiray, I'm interested in working on this. I don't think this is a duplicate of #183, for example there are many local configuration files that are useful to have unique across different containers (apart from any security concerns).

**Comment by ErrorNoInternet** [comment] 2023-04-23 12:48
Any updates on this? I create .spec files for COPR in a toolbox (some build packages are conflicting with my host packages). However, a bunch of programs I use within the container keep creating cache files in my home directory, which is really annoying. rpmbuild also creates a `rpmbuild` directory in my home directory (I know its possible to use a different directory, but sometimes I forget to do that). I would love to be able to set a custom home directory, or automatically use a different home directory for each container (with an option to just share the user's home directory, of course).

**Comment by debarshiray** [comment] 2023-06-28 17:16
> Any updates on this? I create .spec files for COPR in a toolbox (some build packages are conflicting with my host packages). However, a bunch of programs I use within the container keep creating cache files in my home directory, which is really annoying. rpmbuild also creates a `rpmbuild` directory in my home directory (I know its possible to use a different directory, but sometimes I forget to do that). I would love to be able to set a custom home directory, or automatically use a different home directory for each container (with an option to just share the user's home directory, of course).

What if you temporarily overrode `HOME` when using the Toolbx container?
```
$ HOME=/path/to/custom/home toolbox create
...
```

**Comment by ErrorNoInternet** [comment] 2023-06-29 07:47
Yes, that's my current solution but I have to manually do it every time for `toolbox enter`, and I sometimes forget.
Some apps still use /home/<username> instead of $HOME though.

**Comment by ffimnsr** [comment] 2023-10-26 01:47
I think it's simple to create a wrapper script for the problem above. It is not the best design but that works great for me.

**Comment by juhp** [comment] 2023-10-30 10:45
Doesn't seem to work for me (only seems to duplicate the podman/toolbox configs now):

```shellsession
$ mkdir -p toolbox39
$ HOME=~/toolbox39 toolbox list
$ HOME=~/toolbox39 toolbox enter
:
⬢[petersen@toolbox ~]$ echo $HOME
/home/petersen
```

```shellsession
$ distrobox create -H ~/toolbox39
$ distrobox enter
[distrobox petersen]$ echo $HOME
/home/petersen/toolbox39
```

I feel this highly requested feature could be implemented and polished incrementally:
it doesn't have to be perfect out of the door IMHO.

**Comment by debarshiray** [comment] 2024-02-01 19:50
It looks like Go's [os/user](https://pkg.go.dev/os/user) isn't respecting the `HOME` environment variable:

```Go
package main

import (
	"fmt"
	"os/user"
)

func main() {
	user, _ := user.Current()
	fmt.Printf("%s\n", user.HomeDir)
}
```

```ShellSession
$ HOME=/tmp go run user.go 
/home/rishi
```

**Comment by christiansam** [comment] 2024-03-10 18:53
- please mention the info to override the $HOME env-variable, 
- along with a general note - that actions inside a toolbox's bind-mounted paths , e.g. \~/.dot-directories like *~/.cache/fontconfig/* - might cause sideeffects for the user in the host env.
somewhere at: https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/

**Comment by SolarLune** [comment] 2024-08-18 17:51
> It looks like Go's [os/user](https://pkg.go.dev/os/user) isn't respecting the `HOME` environment variable:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"os/user"
> )
> 
> func main() {
> 	user, _ := user.Current()
> 	fmt.Printf("%s\n", user.HomeDir)
> }
> ```
> 
> ```
> $ HOME=/tmp go run user.go 
> /home/rishi
> ```

`user.Current()` gives the current user with what I'm assuming is their canonical home directory.  `os.UserHomeDir()` gives the home directory as it's been set or overridden. 

Replacing `user.HomeDir` at https://github.com/containers/toolbox/blob/b684b190d1d931434d0d7d63c841973101dfb928/src/cmd/run.go#L440 and https://github.com/containers/toolbox/blob/b684b190d1d931434d0d7d63c841973101dfb928/src/cmd/create.go#L306 with `os.UserHomeDir()` might resolve the issue?

**Comment by debarshiray** [comment] 2024-10-10 14:48
> > It looks like Go's [os/user](https://pkg.go.dev/os/user) isn't respecting the `HOME` environment variable:
> 
> `user.Current()` gives the current user information with their uisual home directory. `os.UserHomeDir()` gives the current user's home directory as it's been set or overridden.

Bingo!  That might be it.  I have filed a new issue to track this: https://github.com/containers/toolbox/issues/1564

Do you want to submit a pull request for it?
