### ISSUE TITLE
Validation of custom images

### ISSUE THREAD

**Issue by mfocko** [containers/toolbox#902] opened 2021-10-24 14:54 UTC
**Is your feature request related to a problem? Please describe.**
Feature is mainly related to creating custom images for `toolbox`. Recently I've been trying to create openSUSE Tumbleweed toolbox image, I just copied latest Fedora files and adjusted it for openSUSE (mostly going through the specfiles in Fedora dist-git and looking for the same package in openSUSE). There is just basic description of what should the toolbox image be able to do (e.g. provide some binaries, configs, etc.).

In the end I ended up with an issue that no `sudo` group was present, which I had to debug either via `podman start --attach toolbox` or `toolbox -v enter toolbox` and then missing `libcap` (resolved same way).

The process is pretty slow, because you have to fix the issues one by one.

**Describe the solution you'd like**
It would be ideal to have a script that can be run from inside the container, e.g.

     host$ podman run -ti ‹my-custom-toolbox-image›
    # download the script from GitHub
    image$ bash ./check-image.sh

which would check the requirements and output anything that is not satisfied (or just everything). Something like

    [FAIL] `sudo` group exists.
    [FAIL] `capsh` executable is in $PATH.
    [PASS] `bash` executable is in $PATH.

**Describe alternatives you've considered**
1. Could be potentially included in toolbox as a command, something like `toolbox validate ‹my-custom-toolbox-image›`
2. Clearly describe the requirements on image, but that might loop back to the current state over time.

**Comment by Jmennius** [comment] 2021-10-31 15:04
Looks related to #385 (there are useful answers) but in that case I was only worrying about documentation.

**Comment by debarshiray** [comment] 2021-11-17 00:03
Yes, let's keep the discussion consolidated at https://github.com/containers/toolbox/issues/385

**Comment by debarshiray** [comment] 2021-11-17 00:03
Duplicate of https://github.com/containers/toolbox/issues/385

**Comment by debarshiray** [comment] 2021-11-17 00:03
Thanks for working on the openSUSE Tumbleweed images! :)

**Closed by debarshiray** 2021-11-17 00:03 UTC
Labels: 1. Feature request
