### ISSUE TITLE
There's no f39 toolbox, so running `toolbox enter` on Rawhide fails now F38 has branched

### ISSUE THREAD

**Issue by AdamWill** [containers/toolbox#1233] opened 2023-02-10 18:45 UTC
**Describe the bug**
Fedora 38 has branched from Rawhide. There's no 'f39' toolbox container, apparently, so running `toolbox enter` on Rawhide fails now.

**Steps how to reproduce the behaviour**
1. Install Fedora Rawhide and toolbox
2. Run `toolbox enter`

**Expected behaviour**
It should work.

**Actual behaviour**
It fails.

**Screenshots**
![toolbox](https://user-images.githubusercontent.com/916551/218172629-108504dd-2c6e-4c01-b2ce-286b1a6811a7.png)

**Info about your OS**
Fedora Rawhide (must be since the F38 branch happened)

**Comment by AdamWill** [comment] 2023-02-10 18:47
@nirik mentions https://pagure.io/releng/issue/11271 , though that seems to be about f38.

**Comment by travier** [comment] 2023-02-10 19:11
The container is built from https://src.fedoraproject.org/container/fedora-toolbox

**Comment by debarshiray** [comment] 2023-02-10 20:40
> @nirik mentions https://pagure.io/releng/issue/11271 , though
> that seems to be about f38.

I suppose that's part of the same problem.  Fedora's OCI image infrastructure tends to be a bit ... flaky.  :)

One visible problem is that there's `registry.fedoraproject.org/fedora:39` base image at the moment.  We need that before building the layered image.

**Comment by debarshiray** [comment] 2023-02-10 20:41
I add the fedora-toolbox image definition for Fedora 39 in https://github.com/containers/toolbox/pull/1236 but right now it's useless:
```
[rishi@topinka toolbox]$ podman build --squash --tag localhost/fedora-toolbox:39 ./images/fedora/f39/
STEP 1/19: FROM registry.fedoraproject.org/fedora:39
Trying to pull registry.fedoraproject.org/fedora:39...
Error: creating build container: initializing source docker://registry.fedoraproject.org/fedora:39: reading manifest 39 in registry.fedoraproject.org/fedora: manifest unknown
```

**Comment by nirik** [comment] 2023-02-10 21:26
I've updated the registry... it's not showing up yet for me, but I am hoping it will here in a few. 
Failing that it should update properly tonight.

**Comment by debarshiray** [comment] 2023-02-10 21:39
Thanks, @nirik   Anyway, I am going to close this now.

As @travier mentioned, the `fedora-toolbox` image needs to be built from [src.fedoraproject.org/container/fedora-toolbox](https://src.fedoraproject.org/container/fedora-toolbox).  I have already added the image definition for the Fedora 39 image to this upstream repository, and right now it's just a copy of the F38 image.  So, there's not much left to do here, other than adding F39 to our list of upstream CI builds.

**Closed** 2023-02-10 21:39 UTC
Labels: 1. Bug

**Comment by debarshiray** [comment] 2023-02-13 12:31
> @nirik mentions https://pagure.io/releng/issue/11271 , though that seems to be about f38.

The problem is that [container/fedora-toolbox](https://src.fedoraproject.org/container/fedora-toolbox) doesn't have a `f38` branch at the moment.  It means that we can't build separate `f38` and `f39` images.

But, yes, `registry.fedoraproject.org/fedora:39` does exist now.  So, that's progress.  Thanks, @nirik  :)

**Comment by AdamWill** [comment] 2023-02-13 22:52
so there's now an f38 branch; it seems to have been created empty, which is not right, but does this at leat mean we can build an f39 container now?

**Comment by debarshiray** [comment] 2023-02-15 23:02
`registry.fedoraproject.org/fedora-toolbox:39` [exists](https://koji.fedoraproject.org/koji/buildinfo?buildID=2150984) since Tuesday, and I also [rebuilt](https://koji.fedoraproject.org/koji/buildinfo?buildID=2150972) the the F38 image to pick up the post-branching changes.

**Comment by AdamWill** [comment] 2023-08-09 22:25
Same go-around for F40 :( we need to add this to branching SOPs, I guess. There is no f40 toolbox container, and there is not yet any mention of f40 at https://registry.fedoraproject.org/repo/fedora/tags/ so I think that needs fixing before we can get one.

**Comment by nirik** [comment] 2023-08-09 23:53
The web interface does not reflect the state of the actual registry. ;) The thing that makes that is horrible and broken, so it's not updating much. I tried to update it manually now and it's now not showing any tags. ;( 

Anyhow, both toolbox and the base containers are there... just something is weird with the arch detection... 

ie, if you pull fedora:40-x86_64 it works fine, or fedora-toolbox:40-x86_64, but not fedora:40 or fedora-toolbox:40...

**Comment by AdamWill** [comment] 2023-08-10 00:04
oh, that's weird. I was just running `toolbox -y enter` on a Rawhide system (well, openQA is doing that), which fails. `toolbox -r 39 -y enter` works.

**Comment by nirik** [comment] 2023-08-10 01:34
ok, I re-ran the sync (and also made a fedora-toolbox repo on quay.io, it wasn't there) and now it seems working?

**Comment by AdamWill** [comment] 2023-08-10 01:44
thanks, I'll take the workaround out and retest once things settle down a bit (huge backlog of tests running ATM).

**Comment by AdamWill** [comment] 2023-08-10 18:26
yeah, it's good now.

**Comment by juhp** [comment] 2023-08-12 05:46
Both fedora-toolbox:39 and 40 working for me from the Fedora registry.
