### ISSUE TITLE
Allow for custom location of home directory on the host

### ISSUE THREAD

**Issue by JayDoubleu** [containers/toolbox#887] opened 2021-09-27 06:43 UTC
Currently toolbox will default to your home directory. Because of this I cannot use toolbox for other purposes (isolated, work projects etc). I love the automatic integration with X as well as automatically mounting `/dev` for me however I believe having option to specify custom $HOME path for container would be a very useful feature. 

I would like to be able to specify custom $HOME path for each toolbox container on the host so that there is no conflicting config files for cloud environments such as Azure or AWS, python modules etc. Ideally if we would have something like .toolboxrc file in which we could define custom configurations for tagged containers and allow tagging when using `toolbox create command`?.

I am aware that I could create podman containers with CMDlines from toolbox however I believe it would be more convenient to have this functionality within toolbox itself.

**Comment by juhp** [comment] 2021-10-15 04:54
You could try looking at [podenv](https://github.com/podenv/podenv), though it is a more general tool than toolbox.
I do have a [copr](copr.fedorainfracloud.org/coprs/petersen/podenv) repo if you are on Fedora.

**Comment by debarshiray** [comment] 2021-11-15 15:24
Yes, this keeps [coming up](https://github.com/containers/toolbox/issues/183) from time to time.

Unfortunately, I am afraid that it's not very high on our list of priorities at the moment.

**Comment by debarshiray** [comment] 2021-11-15 15:24
Duplicate of https://github.com/containers/toolbox/issues/183

**Closed** 2022-08-05 22:29 UTC
Labels: 1. Feature request
