### ISSUE TITLE
Failed to start container

### ISSUE THREAD

**Issue by ptomato** [containers/toolbox#769] opened 2021-05-15 20:41 UTC
**Describe the bug**
Toolbox fails to start after an upgrade and a reboot. This seems to be a different error than both #669 and #687.

**Steps how to reproduce the behaviour**
1. `toolbox enter`

**Expected behaviour**
Toolbox environment should start as normal.

**Actual behaviour**
```
$ toolbox enter -v --log-level=debug
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user ptomato 
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Toolbox config directory is /var/home/ptomato/.config/toolbox 
DEBU Current Podman version is 3.2.0-rc1          
DEBU Creating runtime directory /run/user/1000/toolbox 
DEBU Old Podman version is 3.2.0-rc1              
DEBU Migration not needed: Podman version 3.2.0-rc1 is unchanged 
DEBU Resolving container and image names          
DEBU Container: ''                                
DEBU Distribution: ''                             
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'fedora-toolbox-34'               
DEBU Image: 'fedora-toolbox:34'                   
DEBU Release: '34'                                
DEBU Checking if container fedora-toolbox-34 exists 
DEBU Inspecting mounts of container fedora-toolbox-34 
DEBU Starting container fedora-toolbox-34         
Error: failed to start container fedora-toolbox-34
```

**Screenshots**
N/A

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.1`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.1-1.fc34.x86_64`

**Output of `podman version`**
```
Version:      3.2.0-rc1
API Version:  3.2.0-rc1
Go Version:   go1.16.3
Built:        Wed May  5 14:03:46 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-3.2.0-0.1.rc1.fc34.x86_64`

**Info about your OS**
Fedora Silverblue 34, freshly updated as of a couple of days ago

**Additional context**

```
$ toolbox list -i
IMAGE ID      IMAGE NAME                                        CREATED
95dc9d4b0f27  registry.fedoraproject.org/f33/fedora-toolbox:33  8 months ago
9c649cf455d4  registry.fedoraproject.org/fedora-toolbox:34      2 weeks ago
```

Downgrading to the previous ostree state fixed the problem. Additionally, after upgrading to the latest state as of a few minutes ago, the problem remained fixed. It looks like in the newest update podman was intentionally _downgraded_ with an epoch bump from 2:3.2.0 to 3:3.1.2, so maybe this is a known and fixed problem; if so, feel free to just close this.

Here's a list of packages upgraded from the working state into the broken state (note, it's the list I got from `rpm-ostree rollback`, so you have to read it in reverse):
<details>

```
Upgraded:
  firefox 88.0.1-1.fc34 -> 88.0-8.fc34
Downgraded:
  chromium 90.0.4430.93-1.fc34 -> 89.0.4389.90-3.fc34
  chromium-common 90.0.4430.93-1.fc34 -> 89.0.4389.90-3.fc34
  containers-common 4:1-16.fc34 -> 4:1-15.fc34
  evince-djvu 40.1-2.fc34 -> 40.1-1.fc34
  evince-libs 40.1-2.fc34 -> 40.1-1.fc34
  evince-thumbnailer 40.1-2.fc34 -> 40.1-1.fc34
  gjs 1.68.1-1.fc34 -> 1.68.0-5.fc34
  glibc 2.33-8.fc34 -> 2.33-5.fc34
  glibc-all-langpacks 2.33-8.fc34 -> 2.33-5.fc34
  glibc-common 2.33-8.fc34 -> 2.33-5.fc34
  glibc-devel 2.33-8.fc34 -> 2.33-5.fc34
  glibc-doc 2.33-8.fc34 -> 2.33-5.fc34
  glibc-headers-x86 2.33-8.fc34 -> 2.33-5.fc34
  gnome-remote-desktop 40.1-1.fc34 -> 40.0-2.fc34
  gnome-terminal 3.38.3-1.fc34 -> 3.38.1-3.fc34
  gnome-terminal-nautilus 3.38.3-1.fc34 -> 3.38.1-3.fc34
  gobject-introspection 1.68.0-3.fc34 -> 1.68.0-1.fc34
  ibus-typing-booster 2.11.4-1.fc34 -> 2.11.2-4.fc34
  kernel 5.11.19-300.fc34 -> 5.11.17-300.fc34
  kernel-core 5.11.19-300.fc34 -> 5.11.17-300.fc34
  kernel-devel 5.11.19-300.fc34 -> 5.11.17-300.fc34
  kernel-headers 5.11.19-300.fc34 -> 5.11.16-300.fc34
  kernel-modules 5.11.19-300.fc34 -> 5.11.17-300.fc34
  kernel-modules-extra 5.11.19-300.fc34 -> 5.11.17-300.fc34
  kernel-tools 5.11.19-300.fc34 -> 5.11.16-300.fc34
  kernel-tools-libs 5.11.19-300.fc34 -> 5.11.16-300.fc34
  less 581.2-1.fc34 -> 575-2.fc34
  libdrm 2.4.105-1.fc34 -> 2.4.103-2.fc34
  libxml2 2.9.10-12.fc34 -> 2.9.10-10.fc34
  nautilus 40.1-2.fc34 -> 40.1-1.fc34
  nautilus-extensions 40.1-2.fc34 -> 40.1-1.fc34
  pipewire 0.3.27-2.fc34 -> 0.3.27-1.fc34
  pipewire-alsa 0.3.27-2.fc34 -> 0.3.27-1.fc34
  pipewire-gstreamer 0.3.27-2.fc34 -> 0.3.27-1.fc34
  pipewire-jack-audio-connection-kit 0.3.27-2.fc34 -> 0.3.27-1.fc34
  pipewire-libs 0.3.27-2.fc34 -> 0.3.27-1.fc34
  pipewire-pulseaudio 0.3.27-2.fc34 -> 0.3.27-1.fc34
  pipewire-utils 0.3.27-2.fc34 -> 0.3.27-1.fc34
  podman 2:3.2.0-0.1.rc1.fc34 -> 2:3.1.2-1.fc34
  podman-plugins 2:3.2.0-0.1.rc1.fc34 -> 2:3.1.2-1.fc34
  python3-libxml2 2.9.10-12.fc34 -> 2.9.10-10.fc34
  selinux-policy 34.6-1.fc34 -> 34.5-1.fc34
  selinux-policy-targeted 34.6-1.fc34 -> 34.5-1.fc34
  systemd 248.2-1.fc34 -> 248-2.fc34
  systemd-libs 248.2-1.fc34 -> 248-2.fc34
  systemd-networkd 248.2-1.fc34 -> 248-2.fc34
  systemd-oomd-defaults 248.2-1.fc34 -> 248-2.fc34
  systemd-pam 248.2-1.fc34 -> 248-2.fc34
  systemd-rpm-macros 248.2-1.fc34 -> 248-2.fc34
  systemd-udev 248.2-1.fc34 -> 248-2.fc34
  vim-minimal 2:8.2.2846-1.fc34 -> 2:8.2.2825-1.fc34
  virtualbox-guest-additions 6.1.22-1.fc34 -> 6.1.20-1.fc34
  vte-profile 0.64.1-1.fc34 -> 0.62.3-2.fc34
  vte291 0.64.1-1.fc34 -> 0.62.3-2.fc34
  webkit2gtk3 2.32.1-1.fc34 -> 2.32.0-2.fc34
  webkit2gtk3-jsc 2.32.1-1.fc34 -> 2.32.0-2.fc34
  zchunk-libs 1.1.11-1.fc34 -> 1.1.9-2.fc34
Added:
  pipewire0.2-libs-0.2.7-5.fc34.x86_64
```

</details>

And here's a list of packages that upgraded from the broken state into the newly working state:
<details>

```
Upgraded:
  fedora-chromium-config 1.1-9.fc34 -> 1.1-10.fc34
  glib2 2.68.1-1.fc34 -> 2.68.2-1.fc34
  gnome-classic-session 40.0-1.fc34 -> 40.1-1.fc34
  gnome-shell 40.0-6.fc34 -> 40.1-1.fc34
  gnome-shell-extension-apps-menu 40.0-1.fc34 -> 40.1-1.fc34
  gnome-shell-extension-common 40.0-1.fc34 -> 40.1-1.fc34
  gnome-shell-extension-launch-new-instance 40.0-1.fc34 -> 40.1-1.fc34
  gnome-shell-extension-places-menu 40.0-1.fc34 -> 40.1-1.fc34
  gnome-shell-extension-user-theme 40.0-1.fc34 -> 40.1-1.fc34
  gnome-shell-extension-window-list 40.0-1.fc34 -> 40.1-1.fc34
  iwl100-firmware 39.31.5.1-119.fc34 -> 39.31.5.1-120.fc34
  iwl1000-firmware 1:39.31.5.1-119.fc34 -> 1:39.31.5.1-120.fc34
  iwl105-firmware 18.168.6.1-119.fc34 -> 18.168.6.1-120.fc34
  iwl135-firmware 18.168.6.1-119.fc34 -> 18.168.6.1-120.fc34
  iwl2000-firmware 18.168.6.1-119.fc34 -> 18.168.6.1-120.fc34
  iwl2030-firmware 18.168.6.1-119.fc34 -> 18.168.6.1-120.fc34
  iwl3160-firmware 1:25.30.13.0-119.fc34 -> 1:25.30.13.0-120.fc34
  iwl3945-firmware 15.32.2.9-119.fc34 -> 15.32.2.9-120.fc34
  iwl4965-firmware 228.61.2.24-119.fc34 -> 228.61.2.24-120.fc34
  iwl5000-firmware 8.83.5.1_1-119.fc34 -> 8.83.5.1_1-120.fc34
  iwl5150-firmware 8.24.2.2-119.fc34 -> 8.24.2.2-120.fc34
  iwl6000-firmware 9.221.4.1-119.fc34 -> 9.221.4.1-120.fc34
  iwl6000g2a-firmware 18.168.6.1-119.fc34 -> 18.168.6.1-120.fc34
  iwl6000g2b-firmware 18.168.6.1-119.fc34 -> 18.168.6.1-120.fc34
  iwl6050-firmware 41.28.5.1-119.fc34 -> 41.28.5.1-120.fc34
  iwl7260-firmware 1:25.30.13.0-119.fc34 -> 1:25.30.13.0-120.fc34
  libertas-sd8686-firmware 20210315-119.fc34 -> 20210511-120.fc34
  libertas-sd8787-firmware 20210315-119.fc34 -> 20210511-120.fc34
  libertas-usb8388-firmware 2:20210315-119.fc34 -> 2:20210511-120.fc34
  linux-firmware 20210315-119.fc34 -> 20210511-120.fc34
  linux-firmware-whence 20210315-119.fc34 -> 20210511-120.fc34
  mutter 40.0-5.fc34 -> 40.1-1.fc34
  podman 2:3.2.0-0.1.rc1.fc34 -> 3:3.1.2-3.fc34
  podman-plugins 2:3.2.0-0.1.rc1.fc34 -> 3:3.1.2-3.fc34
  python-unversioned-command 3.9.4-1.fc34 -> 3.9.5-1.fc34
  python3 3.9.4-1.fc34 -> 3.9.5-1.fc34
  python3-libs 3.9.4-1.fc34 -> 3.9.5-1.fc34
  xhost 1.0.7-2.fc34 -> 1.0.8-1.fc34
  xmodmap 1.0.9-2.fc34 -> 1.0.10-1.fc34
  xrdb 1.1.1-2.fc34 -> 1.2.0-1.fc34
Added:
  cpp-11.1.1-1.fc34.x86_64
  evince-previewer-40.1-2.fc34.x86_64
  libmpc-1.2.1-2.fc34.x86_64
```

</details>

Podman info:
<details>

```
$ podman info
host:
  arch: amd64
  buildahVersion: 1.20.2-dev
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: localhost-localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.19-300.fc34.x86_64
  linkmode: dynamic
  memFree: 5317320704
  memTotal: 16444547072
  ociRuntime:
    name: crun
    package: crun-0.19.1-2.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 16919814144
  swapTotal: 16919814144
  uptime: 26h 48m 57.74s (Approximately 1.08 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/ptomato/.config/containers/storage.conf
  containerStore:
    number: 61
    paused: 0
    running: 0
    stopped: 61
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/ptomato/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 15
  runRoot: /run/user/1000/containers
  volumePath: /var/home/ptomato/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.0-rc1
  Built: 1620248626
  BuiltTime: Wed May  5 14:03:46 2021
  GitCommit: ""
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.2.0-rc1
```

</details>

**Comment by HarryMichal** [comment] 2021-05-21 18:45
Duplicate of #760

**Closed by HarryMichal** 2021-05-21 18:45 UTC
Labels: 1. Bug
