### ISSUE TITLE
Make programs in base system accessible in toolbox containers

### ISSUE THREAD

**Issue by Yiannis128** [containers/toolbox#1342] opened 2023-07-25 12:27 UTC
**Is your feature request related to a problem? Please describe.**

Commands and programs from base system are not available in toolbox containers. For example, installing python3-pip on base system, does not make it accessible to the toolbox container. This means that each container needs to have it separatley installed, which is counterintuitive as it's the same package and wastes storage.

**Describe the solution you'd like**

Would be nice if all the programs in /bin and /usr/bin were accessible by toolbox containers such that programs in the base system are available.

**Describe alternatives you've considered**

Installing common packages in each container.

**Additional context**

Could be an optional feature, for example, `toolbox create -p` to propagate the programs into the toolbox. Or `toolbox enter -p` for only the session.

**Comment by debarshiray** [comment] 2023-07-27 09:39
Yes, I understand the frustration with not having the same programs available across all containers and the host.

The problem is that the runtime ABI (ie., the dynamic loader, the shared libraries, etc.) can be different across the host and each container because all of those can be from different operating systems.  A Fedora 38 binary from the host is not meant to run on a Fedora 37 or Ubuntu 22.04 container.

Having said that, the host's entire `/` is available inside the container at `/run/host`, and you can identify a Toolbx container by the presence of `/run/.toolboxenv`.  You can leverage this by suitably setting up `PATH` in your shell's start-up scripts.

**Comment by debarshiray** [comment] 2023-09-28 04:55
> I understand, it would be a nice feature, but the workaround
> described is sufficient 😀.

Okay!

One can imagine setting up the default Toolbx container on supported host operating systems to have all the host executables and shared libraries available from `/run/host/usr`.  Unfortunately, it's not that easy to get it right in the general case.  It might even be impossible.

The first thing would be to chain the package database inside the container to the host.  Otherwise, people will be confused by why the contents of the package database don't match with the executables and libraries present in the container.  ie., `rpm --query emacs` versus `command -v emacs`.  I don't know if it's possible for all package managers.

Then you realize that the binaries in `/run/host/usr` have been compiled to pick up their configuration files from `/etc`, not `/run/host/etc`.  Since the paths are baked into the binaries, there's no way to change that other than recompiling.  If you don't, then the binaries from `/run/host/usr` will read the files from `/etc`, and there's no guarantee that a binary from a different version of a package is meant to work with the configuration file from another version.

It quickly turns into a hornet's nest.  :)

So, I would rather let users adjust their paths for their specific use-cases.

**Comment by debarshiray** [comment] 2023-09-28 04:56
> I will leave this issue open, you can close it if nothing else about this
> topic is to be discussed.

Okay, closing.

I am happy to see you playing with Toolbx, and thanks for stopping by.

**Closed by debarshiray** 2023-09-28 04:56 UTC
Labels: 1. Feature request
