### ISSUE TITLE
toolbox run does not work when no tty is attached

### ISSUE THREAD

**Issue by tosmi** [containers/toolbox#157] opened 2019-05-13 18:43 UTC
the current implementation of run() always uses the flags `--interactive` and `--tty` for podman exec. i'm using toolbox run mostly from `dmenu`, so there is no tty attached. Maybe `--tty` and `--interactive` should only be used when enterning a container. 

will create a pull request asap.

thanks
toni

**Comment by debarshiray** [comment] 2019-05-23 17:28
You need `--interactive --tty` in `toolbox run` if you want to run a terminal text editor, for example. Maybe `toolbox run` should grow a flag for this?

**Comment by tosmi** [comment] 2019-05-25 08:37
yep maybe. i'll try to come up with something next week. didn't find the time for anything the last week...
i mostly use `toolbox run` to start my containerized apps within X11 (e.g. vlc, firefox, emacs...). 

i suppose the default should be to use a tty and optionally disable allocating a tty, so `--no-tty`?

thanks
toni

**Comment by tosmi** [comment] 2019-05-28 19:38
so #179 should fix this and works for me. 

thanks
toni

**Comment by ibotty** [comment] 2019-07-16 08:35
Any reason why this is not acted upon?  Should it be determined whether there actually is a tty and automatically disable interactive and tty forward?

**Comment by tosmi** [comment] 2019-07-17 13:18
it would be great if this could be merged

thanks

**Comment by HarryMichal** [comment] 2020-03-16 13:42
Hey @tosmi! I just added your PR (#179) in the rewritten version of Toolbox (tracked here: #318). I just adjusted it to the Go code. Thank you for your contribution and I apologize for not merging this sooner!

**Comment by jmou** [comment] 2020-03-28 17:13
Hi! I came looking for a similar issue but I think the problem is a little more general. In particular I think there are broadly 3 use cases for `toolbox run`:

- Running GUI (non-terminal) applications, possibly without a controlling tty. This is @tosmi 's use case. We SHOULD NOT allocate a tty in this case.
- Running interactive terminal applications that need a tty (bash, screen, vim, anything curses). We SHOULD allocate a tty in this case.
- Running non-interactive terminal applications. These may be used with stdin often attached to a pipe (netcat), which does not work with a tty. We SHOULD NOT allocate a tty in this case.

An app like ssh may be either the second (if invoked without a command, it allocates a tty) or the third (does not allocate a tty if invoked with a command).

I think a simple heuristic would work in the vast majority of situations. If stdin is attached to a tty, then we can allocate a tty; if stdin is not attached to a tty, then do not allocate a tty. I think this handles all of the above use cases. We might allocate a tty when it's not strictly necessary, but we should never allocate a tty when it would break (no controlling terminal or stdin redirected).

This is a simple script I put together to run netcat:

```
#!/bin/sh
[ -t 0 ] && ttyflag=-t
exec podman exec -i $ttyflag fedora-toolbox-32 nc "$@"  
```

Let me know if I can help with this, I can probably put together a PR.

**Comment by jmou** [comment] 2020-03-28 17:16
BTW I just had a quick glance at https://github.com/containers/toolbox/pull/179 and saw that --notty there is also used to unset --interactive. I think this is not desirable because it breaks the third use case, and it is not necessary for the original issue (not setting --tty is sufficient).

**Comment by e-user** [comment] 2020-12-16 20:09
@HarryMichal What happened to the changeset from #179? #318 was merged and master is now based on Go, but the `notty` flag is missing. I need this exact feature for several use cases.

**Comment by tosmi** [comment] 2021-01-04 13:45
thanks @e-user. i have the same issue with the go version. still using my forked versioin for -notty support.

**Comment by e-user** [comment] 2021-01-04 14:18
FWIW if anyone else is also still having this problem, I'm using a script `toolbox-wrapper` that I'm symlinking the respective command to: https://gist.github.com/e-user/d75db5a891bbb0593e9252ee5c8e0826

E.g. pointing `gcloud` at `toolbox-wrapper` means `gcloud` will be run from the toolbox, instead. The script also supports piping from stdin and starts the toolbox if it's not already running.

**Comment by jmou** [comment] 2021-01-07 23:08
I wrote almost the same script for myself! It also allocates a TTY if stdin is a terminal which helps with some interactive commands. https://gist.github.com/jmou/55111caa23d9aeb777ff70c89b9ceffb

**Comment by e-user** [comment] 2021-03-05 10:10
@HarryMichal can you please re-open this ticket? It was never fixed.

**Comment by HarryMichal** [comment] 2021-07-16 16:50
@debarshiray I think we should revisit this. There's also the issue with text outputted by `toolbox run` that adds CRLF to the of every line (there's a Podman [issue](https://github.com/containers/podman/issues/9718) about this). Because of the issue we also need to use a small [workaround](https://github.com/containers/toolbox/blob/main/test/system/103-run.bats#L31) in our system tests.

What approach would be more desirable? An explicit flag for setting/unsetting the `--tty` option in `podman exec` or having a heuristic as @jmou suggests? Or maybe both to give the option to override the heuristic?

**Closed** 2022-03-20 22:05 UTC
Labels: 1. Bug, 2. Host Realm

**Comment by e-user** [comment] 2022-03-21 07:39
Thank you @HarryMichal for fixing this!

**Comment by debarshiray** [comment] 2022-10-21 21:02
> @debarshiray I think we should revisit this.

My apologies!  This fell off my radar.
 
> What approach would be more desirable? An explicit flag for setting/unsetting the `--tty` option in `podman exec` or having a heuristic as @jmou suggests? Or maybe both to give the option to override the heuristic?

Yes, I think that using a heuristic as @jmou suggested is a better approach, if it can be made to work reliably, because then we don't put the burden on the user to figure out exactly what option is needed to make it work correctly.  Of course, we can't make the heuristic work for some reason, then an explicit option might be necessary.

Thanks for fixing this, @HarryMichal ; and everybody else for the helpful discussion!  Much appreciated.

**Comment by debarshiray** [comment] 2022-10-23 14:13
> Hi! I came looking for a similar issue but I think the problem is a little more general. In particular I think there are broadly 3 use cases for `toolbox run`:
> 
>     * Running GUI (non-terminal) applications, possibly without a controlling tty. This is @tosmi 's use case. We SHOULD NOT allocate a tty in this case.

I am a bit unsure about this point.

If `toolbox run` was invoked *from* a graphical environment without being connected to a controlling terminal (eg., dmenu or an IDE), then yes, we shouldn't be using `--tty`.  However, if `toolbox run` was invoked from a terminal *to* run a GUI app, then we should be using `--tty`, because if the same GUI app was run on the host without Toolbx, it would still be running inside a terminal device.

>     * Running interactive terminal applications that need a tty (bash, screen, vim, anything curses). We SHOULD allocate a tty in this case.
> 
>     * Running non-interactive terminal applications. These may be used with stdin often attached to a pipe (netcat), which does not work with a tty. We SHOULD NOT allocate a tty in this case.
> 
> 
> An app like ssh may be either the second (if invoked without a command, it allocates a tty) or the third (does not allocate a tty if invoked with a command).
> 
> I think a simple heuristic would work in the vast majority of situations. If stdin is attached to a tty, then we can allocate a tty; if stdin is not attached to a tty, then do not allocate a tty. I think this handles all of the above use cases. We might allocate a tty when it's not strictly necessary, but we should never allocate a tty when it would break (no controlling terminal or stdin redirected).

Thanks for summarizing the situation!  :)

**Comment by debarshiray** [comment] 2022-11-10 18:35
> @debarshiray I think we should revisit this. There's also the issue with text outputted by `toolbox run` that adds CRLF to the of every line (there's a Podman [issue](https://github.com/containers/podman/issues/9718) about this). Because of the issue we also need to use a small [workaround](https://github.com/containers/toolbox/blob/main/test/system/103-run.bats#L31) in our system tests.

I removed the workaround for the tests in https://github.com/containers/toolbox/pull/1156

**Comment by ernstki** [comment] 2025-09-13 03:35
When you must use an older `toolbox` and want to construct a pipline from its output, it appears you can simply remove the extraneous CRs with `tr -d`. No [`stty` incantations]() required.

Note that newer `toolbox`es _already_ detect whether they're connected to a terminal, and switch on or off the `podman exec --tty` flag as necessary, so you shouldn't see this problem. If you're using Ubuntu 22.04 distro packages, though, for example, you'll run into this.

Other related issues I found (like containers/podman#9718) are already closed and locked, and I wanted to document this for posterity _somewhere_.

## Before

```console
$ toolbox run -r f42 tail -5 /etc/services | cat -A
axio-disc       35100/udp               # Axiomatic discovery protocol^M$
                                                                         pmwebapi        44323/tcp               # Performance Co-Pilot client HTTP API^M$
                                                                                                                                                          cloudcheck-ping 45514/udp               # ASSIA CloudCheck WiFi Management keepalive^M$
                                                                       cloudcheck      45514/tcp               # ASSIA CloudCheck WiFi Management System^M$
                                                                                                                                                           spremotetablet  46998/tcp               # Capture handwritten signatures^M$
```

## After

```console
$ toolbox run -r f42 tail -5 /etc/services | tr -d \\r | cat -A
axio-disc       35100/udp               # Axiomatic discovery protocol$
pmwebapi        44323/tcp               # Performance Co-Pilot client HTTP API$
cloudcheck-ping 45514/udp               # ASSIA CloudCheck WiFi Management keepalive$
cloudcheck      45514/tcp               # ASSIA CloudCheck WiFi Management System$
spremotetablet  46998/tcp               # Capture handwritten signatures$
```
