### ISSUE TITLE
toolbox run command does not work in fedora-silverblue 35

### ISSUE THREAD

**Issue by millerthegorilla** [containers/toolbox#946] opened 2021-12-03 10:10 UTC
**Describe the bug**
I wish to start sublime-text-4 text editor which has been installed inside the standard toolbox 'fedora-toolbox-35' from the host, so that I can make a desktop entry for the sublime text editor.
However, when I run the command `toolbox run --container fedora-toolbox-35 /usr/bin/subl` nothing happens.  Nothing pertinent is reported in the toolbox logs (podman log fedora-toolbox-35).  

**Steps how to reproduce the behaviour**
1. Open terminal
2. type  `toolbox run --container fedora-toolbox-35 /usr/bin/subl` 
3. nothing happens

**Expected behaviour**
I expect sublime text 4 to open

**Actual behaviour**
nothing happens.  nothing is written to the log

**Screenshots**

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.2

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99.2^3.git075b9a8d2779-4.fc35.x86_64

**Output of `podman version`**
```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 20:25:37 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
podman-3.4.2-1.fc35.x86_64

**Info about your OS**
Fedora Silverblue 35
uname -a
Linux fedora 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
When did the issue start occurring? After an update (what packages were updated)?
If the issue is about operating with containers/images (creating, using, deleting,..), share here what image you used. If you're unsure, share here the output of `toolbox list -i` (shows all toolbox images on your system).

If you see an error message saying: `Error: invalid entry point PID of container <name-of-container>`, add to the ticket output of command `podman start --attach <name-of-container>`.

**Comment by debarshiray** [comment] 2021-12-03 18:29
Did you try running `/usr/bin/subl` from a `toolbox enter` shell?

**Comment by millerthegorilla** [comment] 2021-12-05 15:43
Yes, I did.

The command works inside the toolbox container, but not when invoked with
the run command from outside it.

**Comment by millerthegorilla** [comment] 2021-12-06 10:15
The toolbox run command exit code is 0 despite subl not launching.

**Comment by HarryMichal** [comment] 2021-12-07 12:57
Do you get any output from `toolbox run -c fedora-toolbox-35 /usr/bin/subl -v`? On my machine this successfully returns the program's version.

**Comment by HarryMichal** [comment] 2021-12-07 12:58
> The toolbox run command exit code is 0 despite subl not launching.

This is currently expected behaviour (though its not documented). See https://github.com/containers/toolbox/pull/867,

**Comment by millerthegorilla** [comment] 2021-12-10 11:04
I used the package install following these instructions:
https://www.sublimetext.com/docs/linux_repositories.html#dnf

**Comment by millerthegorilla** [comment] 2021-12-10 11:06
And it doesn't work on the host either.

**Comment by debarshiray** [comment] 2021-12-17 13:07
> And it doesn't work on the host either.

If Sublime Text is not working on the host either, then the problem is elsewhere.

Maybe try using `strace` against the `/usr/bin/subl` binary?

**Comment by debarshiray** [comment] 2021-12-17 13:08
Closing, because this doesn't look like a Toolbox problem.

Please feel free to leave a comment or re-open if you think otherwise.

**Closed by debarshiray** 2021-12-17 13:08 UTC
Labels: 1. Bug, 2. Container Realm
