### ISSUE TITLE
Fedora 31: /run/host/etc/resolv.conf does not exist

### ISSUE THREAD

**Issue by fansari** [containers/toolbox#339] opened 2019-11-20 10:13 UTC
After creating a new fedora-toolbox-31 I noticed that /run/host/etc/resolv.conf does not exist. /etc/resolv.conf is a link to this file.

I can remove the link and replace it with content - but this is not a permanent solution since this works only until the next start of the box.

Maybe this is related to the fact that I changed from NetworkManager to systemd-networkd on my host system.

What is the correct way to fix this?

**Comment by TingPing** [comment] 2019-11-20 16:28
Duplicate of #187

**Closed** 2019-12-05 20:55 UTC
Labels: duplicate
