### ISSUE TITLE
Enable automatic toolbox entering in new terminal for distros other than fedora

### ISSUE THREAD

**Issue by GerardoGR** [containers/toolbox#1309] opened 2023-06-10 08:20 UTC
I'm currently using Arch linux and would like to have the automatic toolbox upon entering in a new terminal tab. Based on the current implementation:
https://github.com/containers/toolbox/blob/28913fad1da2871287c51eceba43ad62c60f17b2/src/cmd/enter.go#L137-L141

The escape sequence to preserve the cwd is only set for Fedora flavors, namely, `Silverblue` or `Workstation`. Is it possible to support other distros, or to always emit the escape sequence so that other distros benefit of this feature?, e.g.

```golang
	emitEscapeSequence := true
```

**Comment by debarshiray** [comment] 2023-06-28 10:41
The escape sequence needs to be supported by the terminal emulator inside which Toolbx is being used.  It's emitted only on Fedora Silverblue and Workstation because the default terminal emulation application, GNOME Terminal, supports it through a downstream patch.

I suspect that it will be difficult to turn it on for Arch Linux because of it's roll-your-own nature.  It's hard to decide which is the default terminal app, which makes it hard to say if the escape sequence is supported or not.

There was an [attempt](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/17) to standardize the escape sequence across multiple terminal applications, but it's really difficult to push new things into the terminal emulation landscape.  I suggest making some noise on the [terminal-wg](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/17) proposal and requesting your favourite terminal emulators to implement it.

**Comment by chergert** [comment] 2023-11-21 22:27
I really want to see this check removed as well.

VTE already just passes through the 777 when not patched downstream, so for those terminals it should be fine. But for something more generic, can we at least switch to an environment variable that could be set by the terminal to change the default behavior?

For a Flatpak which has a patched VTE you still don't have control over the host even though you can definitely support this. Additionally, the os-release checks break the idea of push/pop semantics for containers of containers (say flatpak in toolbox).

**Comment by chergert** [comment] 2023-11-21 22:34
Another thing we can do, to also handle a few more cases is to look at `ID_LIKE=fedora` which would cover at least the remixes like Asahi where toolbox/gnome-terminal is currently broken.

**Comment by debarshiray** [comment] 2023-12-08 12:01
I am open to ideas on how to move forward with this.

I do like the idea of expecting the terminal to set an environment variable to request Toolbx to emit the escape sequence to preserve the current container.  We just need to agree on what the environment variable would be called, and the semantics of it (eg., if the variable is a set of flags, then the name of the flag and it's representation).

Is there a terminal emulator that's ready to go this way today?  Did you manage to get some consensus from VTE, @chergert ?  I have lost touch with the world of terminal emulators and I don't know what's the general consensus today.

When I first [came up](https://gitlab.freedesktop.org/terminal-wg/specifications/issues/17) with the [idea](https://github.com/containers/toolbox/pull/199) in the summer of 2019, we had very few terminal applications that were primarily being used as Flatpaks.  Most of the terminal emulation community didn't really care because they weren't using OSTree-based OSes where Toolbx was crucial.  Some people liked it, others also [didn't](https://github.com/containers/toolbox/issues/218) to various degrees.  You can see that people started complaining within two weeks of the code being merge.  :)

That's why I chose to limit it's impact to a subset of Fedora that I was personally invested in and responsible for.  eg., I didn't want dislike of this feature from Fedora CoreOS to impact the adoption of Toolbx in Fedora CoreOS.

Anyway, here we are today, four and a half years later.  :)

If we can find a way to improve the terminal emulation, then I am all for it.  Just let me know or send a pull request.

*I actually forgot that this issues exists, even though I responded to it.  I only tend to remember the [opposing(https://github.com/containers/toolbox/issues/218) counterpart.  I suppose it says something about negative emotions being stronger than positive ones.*

**Comment by debarshiray** [comment] 2023-12-08 12:13
> Another thing we can do, to also handle a few more cases is to look at `ID_LIKE=fedora`

The problem is that `ID_LIKE=fedora` includes Red Hat Enterprise Linux.  I didn't want to enable a half-baked prototype feature in RHEL and deal with all the fallout from that.  :)

> which would cover at least the remixes like Asahi where toolbox/gnome-terminal is currently broken.

For anybody following along, the escape sequences for Toolbx integration are now [enabled](https://github.com/containers/toolbox/pull/1413) for Fedora Asahi Remix.

> I don't really see the value of the workstation/silverblue check. I can't imagine people are building spins without the typical vte patches.

I was worried about push back from Fedora CoreOS that could hinder adoption of Toolbx.  I wanted to pick my battles until we could engineer a well rounded feature.  I know you are working on that now, @chergert , so thanks for that!

**Comment by chergert** [comment] 2023-12-08 17:28
For Prompt I added a profile option for "preserve-container" so I think some of the issues of 218 would go away.

**Comment by debarshiray** [comment] 2023-12-19 16:34
Duplicate of https://github.com/containers/toolbox/issues/218

**Comment by debarshiray** [comment] 2023-12-19 16:36
Let's use https://github.com/containers/toolbox/issues/218 as The One True Issue about how to improve the terminal integration to preserve the current container, instead of splitting the discussion into two for and against issues.

**Closed by debarshiray** 2023-12-19 16:36 UTC
Labels: 1. Feature request
