### ISSUE TITLE
Toolbox is not compatible with systemd-resolved

### ISSUE THREAD

**Issue by gcampax** [containers/toolbox#398] opened 2020-04-01 17:33 UTC
If the host system is using systemd-resolved, resolv.conf is a symlink to /run/systemd/resolve/stub-resolv.conf
This is not compatible with toolbox: inside toolbox /etc/resolv.conf becomes a dangling symlink because /run/systemd is not available.

As a workaround, one can add "resolve" to /etc/nssswitch.conf inside the toolbox, and then DNS resolution uses DBus and works fine for most apps.
Unfortunately, some apps use DNS directly (notably, some go apps) and will still be broken.

As a further workaround, one can remove /etc/resolv.conf and replace it with a real file in the running container, but this needs to be done at every reboot and it's not great.

It would be great if toolbox could recognize that resolv.conf is a symlink on the host and bind-mount the symlink destination instead of the symlink, or alternatively bind-mount /run/systemd/resolve unconditionally.

**Comment by debarshiray** [comment] 2020-05-13 13:26
Duplicate of #187

**Closed** 2020-05-13 13:26 UTC
