### ISSUE TITLE
NAME and VERSION leak into toolbox container env

### ISSUE THREAD

**Issue by juhp** [containers/toolbox#188] opened 2019-06-07 04:22 UTC
I noticed that envvar for `ENV NAME=fedora-toolbox VERSION=30` leak into the toolbox environment.
I am not sure if this is desirable: eg NAME affects changelog entry generation in Emacs rpm-spec-mode. And probably having VERSION in the container is not that useful either.

**Comment by debarshiray** [comment] 2019-06-07 07:08
Yeah, those variables are exported by Podman. It always felt odd that they aren't namespaced. I wonder if Docker does the same, and so it's done for compatibility.

**Comment by debarshiray** [comment] 2020-01-10 18:15
I wish I could transfer this to `libpod`. Doesn't look like I have the necessary permissions for that. :(

@juhp could you please (re)file this against `libpod` ? We could do something to suppress these variables, but they come directly from Podman, so might be better to at least discuss it a bit first. I have no idea why such generically named and non-namespaced variables were chosen in the first place.

**Comment by debarshiray** [comment] 2020-01-10 18:18
Oh wait, they actually come from the Dockerfile for the `fedora-toolbox` images.

**Comment by debarshiray** [comment] 2020-01-10 18:19
They are mandated by the [Fedora guidelines](https://docs.fedoraproject.org/en-US/containers/guidelines/creation/).

**Comment by debarshiray** [comment] 2020-01-10 18:22
On closer reading, it doesn't look like the guidelines actually require them, but they are part of the example Dockerfile snippets.

**Comment by cverna** [comment] 2020-01-10 18:40
So from a quick look at OSBS it seems that these labels are used to populate some data in koji post build. I don't think we can remove them.

I ll look into more details next week if there is a work around.

**Comment by debarshiray** [comment] 2020-01-10 18:42
Thanks for clarifying that, @cverna !

**Comment by debarshiray** [comment] 2020-05-13 13:29
@cverna confirmed in `#fedora-containers` on Freenode that `NAME` and `VERSION` really do need to be present in the Dockerfile.

**Comment by HarryMichal** [comment] 2020-06-13 16:11
@debarshiray, I guess we could unset the env vars when the container is being initialized. That way we keep them in the Dockerfiles but they will not cause problems during runtime.

**Comment by Jmennius** [comment] 2020-06-25 10:05
@debarshiray Can you clarify why exactly are they required?
Should we have them in non-Fedora images?

**Comment by debarshiray** [comment] 2020-06-25 11:18
> I guess we could unset the env vars when the container is
> being initialized. That way we keep them in the Dockerfiles
> but they will not cause problems during runtime.

The `NAME` and `VERSION` environment variables make their way into the toolbox containers from their corresponding images, and are part of the containers' metadata. See:
```
$ podman inspect --type container <container>
```

We could somehow unset the variables right before spawning the interactive shell inside the container. However, that would deepen the voodoo that we perform when launching the shell.

A cleaner alternative might be to block the environment variables from getting leaked into the container from the image, but I don't see an obvious way to do that.

**Comment by debarshiray** [comment] 2020-06-25 11:19
> Can you clarify why exactly are they required?

As @cverna mentioned, they are needed by the Fedora build system.

> Should we have them in non-Fedora images?

I don't think you need them in non-Fedora images.

**Comment by Jmennius** [comment] 2020-06-25 15:21
Thanks for the answer.
It looks like the only clean solution would be to change OSBS to rely on labels (which are actually designed for this type of metadata).

**Comment by debarshiray** [comment] 2020-08-28 16:14
Closing.

We can revisit this once the Fedora build system no longer needs `NAME` and `VERSION`.

**Closed by debarshiray** 2020-08-28 16:14 UTC

**Comment by JayDoubleu** [comment] 2022-01-16 17:31
@debarshiray I might be wrong on this but by looking at the guidelines, looks like there is a requirement for the right labels to be present by fedora build system and not the env vars themeselves ?

![image](https://user-images.githubusercontent.com/40270505/149670975-9c338a33-e742-4b65-a977-e2386b8dfa3e.png)
https://github.com/containerbuildsystem/atomic-reactor/blob/bdf5ecf52db1a30a5db135d12b51a488c04ebe29/atomic_reactor/plugins/pre_bump_release.py#L253..L266 

Could the env vars in Containerfile be converted to ARGS instead ?

**Comment by debarshiray** [comment] 2023-02-16 16:59
> Could the env vars in Containerfile be converted to ARGS instead

Just now @travier brought this up in https://github.com/containers/docs/pull/15

Unfortunately, I am not an expert in Fedora's OCI image building pipeline.  I 
mostly follow what the maintainers of the pipeline mandate.  :)
