### ISSUE TITLE
Invalid entrypoint on later versions of Toolbox

### ISSUE THREAD

**Issue by TheEvilSkeleton** [containers/toolbox#871] opened 2021-09-09 02:47 UTC
**Describe the bug**
A clear and concise description of *what the bug is*. If possible, re-run the command(s) with `--log-level debug` and put the output here.

One of my Toolbox containers worked in Fedora 34 Silverblue, but it stopped working in Fedora 35 Silverblue.

**Steps how to reproduce the behaviour**
1. run `toolbox create --image registry.gitlab.com/theevilskeleton/jekyll-toolbox`
2. Run any command inside the `jekyll-toolbox` container

**Expected behaviour**
Commands should run as intended.

**Actual behaviour**
Gives the following error:
```
Error: invalid entry point PID of container jekyll-toolbox
```

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.2`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.2^3.git075b9a8d2779-1.fc35.x86_64`

**Output of `podman version`**
```
Version:      3.3.0
API Version:  3.3.0
Go Version:   go1.16.6
Built:        Fri Aug 20 15:35:44 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-3.3.0-1.fc35.x86_64`

**Info about your OS**
Fedora Silverblue 35

**Additional context**
As explained before, this issue happened after I upgraded to Fedora Silverblue 35.

If you see an error message saying: `Error: invalid entry point PID of container <name-of-container>`, add to the ticket output of command `podman start --attach <name-of-container>`.

```
❯ podman start --attach jekyll-toolbox 
toolbox: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by toolbox)
```

**Comment by vchernin** [comment] 2021-09-09 07:50
See https://github.com/containers/toolbox/issues/821

**Comment by olivergs** [comment] 2021-09-09 08:33
After some time not being able to update fedora-toolbox images due to a fedora buil infrastructure bug, @debarshiray and @juhp were able to update the images for f35 and f36 (rawhide).

Please, update the images as the glibc versions should match now.

**Comment by nanonyme** [comment] 2021-09-09 14:04
Well, this still affects any non-Fedora toolbox using older glibc

**Comment by TheEvilSkeleton** [comment] 2021-09-09 14:22
Yup, some containers stopped working for me for that reason.

**Comment by juhp** [comment] 2021-09-10 05:47
I have been seeing this for quite a while too.

Can we add `toolbox` to fedora-toolbox??

**Comment by juhp** [comment] 2021-09-11 06:29
> Can we add `toolbox` to fedora-toolbox??

So I tried this for fun actually: patched toolbox to not copy /usr/bin/toolbox into the toolbox container
and created a localhost/fedora-toolbox:34 with toolbox preinstalled and it starts fine on F35!
A gentler approach would be to not bind mount the host toolbox binary into the container if the file already exists.

Though I appreciate this is a tricky thing to bootstrap, while it looks like the right thing to do.

**Comment by matthiasclasen** [comment] 2021-09-11 19:43
This is unfortunate, and will keep me away from f35.

**Comment by debarshiray** [comment] 2021-09-17 11:19
Duplicate of https://github.com/containers/toolbox/issues/821

**Closed** 2021-09-17 11:20 UTC
Labels: 1. Bug
