### ISSUE TITLE
toolbox list gives control characters in non-interactive shell

### ISSUE THREAD

**Issue by maweki** [containers/toolbox#596] opened 2020-10-26 08:54 UTC
**Describe the bug**

`toolbox list` gives as output the following (I am showing the control characters)

```
^[[0;00mCONTAINER ID  CONTAINER NAME  CREATED             STATUS   IMAGE NAME^[[0m
^[[1;32m66d2f1277a39  odm             About a minute ago  running  registry.fedoraproject.org/f32/fedora-toolbox:32^[[0m
```

`toolbox list | cat` gives the same output, including the color control characters, which means you cannot use `cut -12` (for example), to get the container ID. Usually console programs detect whether they are currently run in an interactive environment or not (like `ls`) and do not include control characters.

I think this behaviour changed recently, as a few of my scripts are broken when they weren't before.

**Steps how to reproduce the behaviour**
1. Enter `toolbox list | cat`

**Expected behaviour**

`toolbox list | cat` should not include control characters, while `toolbox list` within an interactive console should

**Actual behaviour**
`toolbox list | cat` includes control characters

**Screenshots**

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.96`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.96-1.fc32.x86_64`

**Output of `podman version`**
```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 21:31:11 2020
OS/Arch:      linux/amd64

```
**Podman package info (`rpm -q podman`)**
`podman-2.1.1-7.fc32.x86_64`

**Info about your OS**
Fedora 32

**Additional context**
I didn't use any of my scripts for a few months (maybe July or August) and they worked then. Now the control characters make problems. I guess this is a regression.

**Comment by maweki** [comment] 2020-10-26 09:03
I believe this issue is here https://github.com/containers/toolbox/commit/61a5f5158c130ecb4335b9b0ea9d8b9054927573

The control characters are written unconditionally. They should only be written if the shell is interactive

**Comment by maweki** [comment] 2020-10-30 09:33
As a comparison: https://git.savannah.gnu.org/cgit/grep.git/tree/src/grep.c#n2971

```
  if (color_option == 2)
    color_option = possibly_tty && should_colorize () && isatty (STDOUT_FILENO);
```

**Comment by debarshiray** [comment] 2020-10-30 20:07
> I didn't use any of my scripts for a few months (maybe July or August)
> and they worked then. Now the control characters make problems. I
> guess this is a regression.

Whether it's a regression or not depends on whether someone was using the older POSIX shell implementation of the tool or not. :)

The POSIX shell implementation also used to unconditionally show the colours. The initial Go implementation simply didn't have any coloured output due to limitations of Go's `tabwriter`, until @HarryMichal worked out a hack to add it.

**Comment by debarshiray** [comment] 2020-11-03 18:51
This should now be fixed in `master`. Thanks for stopping by!

**Closed** 2020-11-03 18:51 UTC
Labels: bug
