### ISSUE TITLE
toolbox stops all running podman containers

### ISSUE THREAD

**Issue by chaseadam** [containers/toolbox#896] opened 2021-10-20 15:16 UTC
**Describe the bug**
running `toolbox` triggers a `stop` request to all running containers. I have experienced this several times, but not consistently.

**Steps how to reproduce the behaviour**
1. run `toolbox` (with no arguments)

**Expected behaviour**
Existing containers are not stopped

**Actual behaviour**
* command appears to hang until the stop commands are issued
* all podman containers stopped
* returns "missing command" (as expected)

**Screenshots**
[toolbox-journalctl.log](https://github.com/containers/toolbox/files/7382369/toolbox-journalctl.log)

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.2

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99.2-7.fc34.x86_64

**Output of `podman version`**
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 15:40:21 2021
OS/Arch:      linux/amd64

**Info about your OS**
Fedora 34 workstation x86_64

**Additional context**
Could be unrelated, but there is mention of `podman-pause` scope in the logs around the time I ran the command.

**Comment by chaseadam** [comment] 2021-10-22 04:23
This package appears to be compiled from this github repo, so I think this is the correct place.

It makes sense that this tool does not call `podman stop`, but it is interacting as described with the running podman containers in my non-root user session. Alas, I do not have a clear reproduction case. Was hoping someone might chime in as well.

Any advice on running toolbox in debug mode?

**Comment by debarshiray** [comment] 2021-11-13 11:58
I continue to suspect that you are using https://github.com/coreos/toolbox because of this line:

> run toolbox (with no arguments)

Running `toolbox` without any arguments is a `coreos/toolbox` thing.

**Comment by debarshiray** [comment] 2021-11-13 11:59
I am tentatively closing this.  Feel free to re-open or leave a comment if you have reason to believe otherwise.

**Closed** 2021-11-13 12:00 UTC
Labels: 1. Bug

**Comment by chaseadam** [comment] 2022-02-23 18:23
I experienced this again, this time with debug on!

All off my running (non-toolbox?) podman containers appear to be shut down during the version "migration" process

```
➜  kernel git:(i915_clock-override) ✗ toolbox enter kernel
DEBU Running as real user ID 1000
DEBU Resolved absolute path to the executable as /usr/bin/toolbox
DEBU Running on a cgroups v2 host
DEBU Checking if /etc/subgid and /etc/subuid have entries for user achasen
DEBU Validating sub-ID file /etc/subuid
DEBU Validating sub-ID file /etc/subgid
DEBU TOOLBOX_PATH is /usr/bin/toolbox
DEBU Migrating to newer Podman
DEBU Toolbox config directory is /home/achasen/.config/toolbox
DEBU Current Podman version is 3.4.4
DEBU Creating runtime directory /run/user/1000/toolbox
DEBU Old Podman version is 3.4.2
DEBU Migration to Podman version 3.4.4 was ok
DEBU Updating Podman version in /home/achasen/.config/toolbox/podman-system-migrate
DEBU Setting up configuration
DEBU Setting up configuration: file /home/achasen/.config/containers/toolbox.conf not found
DEBU Resolving image name
DEBU Distribution (CLI): ''
DEBU Image (CLI): ''
DEBU Release (CLI): ''
DEBU Resolved image name
DEBU Image: 'fedora-toolbox:34'
DEBU Release: '34'
DEBU Resolving container name
DEBU Container: ''
DEBU Image: 'fedora-toolbox:34'
DEBU Release: '34'
DEBU Resolved container name
DEBU Container: 'fedora-toolbox-34'
DEBU Resolving image name
DEBU Distribution (CLI): ''
DEBU Image (CLI): ''
DEBU Release (CLI): ''
DEBU Resolved image name
DEBU Image: 'fedora-toolbox:34'
DEBU Release: '34'
DEBU Resolving container name
DEBU Container: 'kernel'
DEBU Image: 'fedora-toolbox:34'
DEBU Release: '34'
DEBU Resolved container name
DEBU Container: 'kernel'
DEBU Checking if container kernel exists
DEBU Inspecting mounts of container kernel
DEBU Starting container kernel
DEBU Inspecting entry point of container kernel
DEBU Entry point PID is a float64
DEBU Entry point of container kernel is toolbox (PID=971489)
DEBU Waiting for container kernel to finish initializing
DEBU Creating runtime directory /run/user/1000/toolbox
DEBU Checking if initialization stamp /run/user/1000/toolbox/container-initialized-971489 exists
DEBU Container kernel is initialized
DEBU Checking if 'podman exec' supports disabling the detach keys
DEBU 'podman exec' supports disabling the detach keys
DEBU Creating list of environment variables to forward
```

**Comment by HarryMichal** [comment] 2022-03-20 21:49
This is an expected behaviour. Toolbox keeps track of the latest used version of Podman and if a newer one is used, `podman system migrate` is called under the hood to execute necessary migrations (if there are any). Due to the nature of rootless containers, they need to be stopped (which is done by the command itself).
