### ISSUE TITLE
Some Nmap options do not work inside toolbox container

### ISSUE THREAD

**Issue by nexfwall** [containers/toolbox#67] opened 2019-02-28 21:03 UTC
```
🔹[ezakharov@toolbox ~]$ nmap -v -sS -A -p 1-1024 192.168.0.0/24
You requested a scan type which requires root privileges.
QUITTING!
🔹[ezakharov@toolbox ~]$ sudo nmap -v -sS -A -p 1-1024 192.168.0.0/24
Starting Nmap 7.70 ( https://nmap.org ) at 2019-02-28 20:57 UTC
NSE: Loaded 148 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 20:57
Completed NSE at 20:57, 0.00s elapsed
Initiating NSE at 20:57
Completed NSE at 20:57, 0.00s elapsed
Initiating ARP Ping Scan at 20:57
dnet: Failed to open device enp4s0
QUITTING!
```

Is where anything I can do about it? I don't want to bring nmap into my base image...

**Comment by debarshiray** [comment] 2020-11-03 21:25
It's now possible, using the code in Git `master`, to [run toolbox(1) as root](https://github.com/containers/toolbox/issues/267). I would say that this is an ideal use-case for that because if something really needs UID 0 on the host, then that's the only option.

**Comment by debarshiray** [comment] 2020-11-03 21:26
Duplicate of https://github.com/containers/toolbox/issues/267

**Closed by debarshiray** 2020-11-03 21:26 UTC
Labels: bug, help wanted
