### ISSUE TITLE
No Vulkan when using the proprietary Nvidia driver

### ISSUE THREAD

**Issue by andreldmonteiro** [containers/toolbox#343] opened 2019-11-27 14:35 UTC
I was setting a toolbox to test for bugs on native vs flatpak steam and I'm unable to run it on the toolbox.

First it complained about the drivers, installed the nvidia drivers on the toolbox solved the complaining but now it doesn't seem to go any further with little output on the terminal.

**Comment by monterrr** [comment] 2019-11-28 13:49
I was able to run steam after that by just performing a dnf update, from an initial test opengl works but vulkan doesn't.

**Comment by debarshiray** [comment] 2020-01-08 18:54
I ran `vulkaninfo` on my Intel Kaby Lake laptop and I do get Vulkan.

Is this just about Vulkan with the proprietary Nvidia driver?

**Comment by monterrr** [comment] 2020-01-11 18:20
I think the problem is specific to the proprietary nvidia driver.

If you can run vkmark then yes.

**Comment by debarshiray** [comment] 2021-11-17 00:14
Let's consider this to be a duplicate of https://github.com/containers/toolbox/issues/116

Ultimately, Toolbox can only give access to the NVIDIA driver. If it offers Vulkan, then great, if not, then Toolbox can't help.

**Comment by debarshiray** [comment] 2021-11-17 00:14
Duplicate of https://github.com/containers/toolbox/issues/116

**Closed by debarshiray** 2021-11-17 00:14 UTC
Labels: 1. Bug, 5. Help Wanted
