### ISSUE TITLE
Curl hostname resolve error in toolbox

### ISSUE THREAD

**Issue by rugk** [containers/toolbox#521] opened 2020-08-03 15:05 UTC
```
$ sudo dnf update
Fedora 32 openh264 (From Cisco) - x86_64                                                                                                                      0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora-cisco-openh264':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'fedora-cisco-openh264': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Fedora Modular 32 - x86_64                                                                                                                                    0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora-modular':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
```

in a freshly created toolbox container (with the usual `registry.fedoraproject.org/f32/fedora-toolbox:32`) on Fedora Workstation 32

With toolbox v0.0.92 and podman version 2.0.3.

Outside of the container, `dnf` works fine.

**Comment by D4N** [comment] 2020-08-04 08:36
I am facing exactly the same issue on opensuse Tumbleweed with toolbox build from git master with podman 1.9.3.

**Comment by D4N** [comment] 2020-08-04 10:37
In my case the issue was relatively simple: `/etc/resolv.conf` on my host system is a symlink to `/var/run/netconfig/resolv.conf` which is not accessible inside the toolbox container and thus all name resolution fails. I have fixed this for now by copying the contents of my host systems resolv.conf into the container's resolv.conf.

**Comment by HarryMichal** [comment] 2020-08-04 11:41
Yes, this is a duplicate of #187. There's already a patch (#460) ready that should fix the issue. I'm closing this.

**Closed by HarryMichal** 2020-08-04 11:41 UTC
