### ISSUE TITLE
Fail to enter toolbox container

### ISSUE THREAD

**Issue by inigoserna** [containers/toolbox#1064] opened 2022-06-01 21:33 UTC
**Describe the bug**
Can't enter into a new and default toolbox container after installing podman and toolbox packages and creating first container.

**Steps how to reproduce the behaviour**
``` bash
~ > toolbox create
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:36 (500MB)? [y/N]: y
Created container: fedora-toolbox-36
Enter with: toolbox enter
~ > toolbox enter
Error: failed to start container fedora-toolbox-36
```

**Expected behaviour**
Enter into the new toolbox container.

**Actual behaviour**
``` bash
~ > toolbox --verbose enter
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user inigo 
DEBU Validating sub-ID file /etc/subuid           
DEBU Validating sub-ID file /etc/subgid           
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Migrating to newer Podman                    
DEBU Toolbox config directory is /home/inigo/.config/toolbox 
DEBU Current Podman version is 4.1.0              
DEBU Creating runtime directory /run/user/1000/toolbox 
DEBU Old Podman version is 4.1.0                  
DEBU Migration not needed: Podman version 4.1.0 is unchanged 
DEBU Setting up configuration                     
DEBU Setting up configuration: file /home/inigo/.config/containers/toolbox.conf not found 
DEBU Resolving image name                         
DEBU Distribution (CLI): ''                       
DEBU Image (CLI): ''                              
DEBU Release (CLI): ''                            
DEBU Resolved image name                          
DEBU Image: 'fedora-toolbox:36'                   
DEBU Release: '36'                                
DEBU Resolving container name                     
DEBU Container: ''                                
DEBU Image: 'fedora-toolbox:36'                   
DEBU Release: '36'                                
DEBU Resolved container name                      
DEBU Container: 'fedora-toolbox-36'               
DEBU Resolving image name                         
DEBU Distribution (CLI): ''                       
DEBU Image (CLI): ''                              
DEBU Release (CLI): ''                            
DEBU Resolved image name                          
DEBU Image: 'fedora-toolbox:36'                   
DEBU Release: '36'                                
DEBU Resolving container name                     
DEBU Container: ''                                
DEBU Image: 'fedora-toolbox:36'                   
DEBU Release: '36'                                
DEBU Resolved container name                      
DEBU Container: 'fedora-toolbox-36'               
DEBU Checking if container fedora-toolbox-36 exists 
DEBU Inspecting mounts of container fedora-toolbox-36 
DEBU Starting container fedora-toolbox-36         
Error: failed to start container fedora-toolbox-36
```

**Screenshots**
/

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.3`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.3-4.fc36.x86_64`

**Output of `podman version`**
```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18
Built:        Fri May  6 18:15:54 2022
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-4.1.0-1.fc36.x86_64`

**Info about your OS**
Fedora WorkStation 36

**Additional context**
This Fedora installation has been upgraded from previous versions (33...36), but it's the first time I install podman & toolbox packages. No previous docker use either. Checked with selinux enabled and disabled.

It looks the same error that this old bug: https://github.com/containers/storage/issues/1068

``` bash
~ > podman start --attach fedora-toolbox-36
Error: unable to start container 6b6c1ab2bb8303f04b7842f148c040f555dd2f4ac863e46d81263e123e396862: crun: make `/home/inigo/.local/share/containers/storage/overlay/c72bb088f73f1f5a6d4e35dc914af0f064680997dcaab42c1b8e619fed64a24a/merged` private: Permission denied: OCI permission denied
```

``` bash
~ > ls -lZ ~/.local/share/containers/storage/overlay
total 0
drwx------. 5 inigo  inigo  unconfined_u:object_r:container_ro_file_t:s0  69 Jun  1 23:18 4fe2aae696d37916b68036632e625dfa39f3a20758ebf10a620c0396c4751874
drwx------. 5 100000 100000 unconfined_u:object_r:container_ro_file_t:s0  68 Jun  1 23:18 6fe086584e2cb90370083c3043dd2f42a16e052b6828424623f68f9c0a5d6dbd
drwx------. 6 inigo  inigo  unconfined_u:object_r:container_ro_file_t:s0  69 Jun  1 23:18 a7e6caf12d36232c05ce95d911fa5dace3f81d2f0e39556182015d258c881b64
drwx------. 4 100000 100000 unconfined_u:object_r:container_ro_file_t:s0  55 Jun  1 23:18 c72bb088f73f1f5a6d4e35dc914af0f064680997dcaab42c1b8e619fed64a24a
drwx------. 2 inigo  inigo  unconfined_u:object_r:container_ro_file_t:s0 142 Jun  1 23:18 l
```

**Comment by HarryMichal** [comment] 2022-06-01 22:17
Hi @inigoserna! This should not be https://github.com/containers/storage/issues/1068 because that refers to `~/.local/share/containers/storage/overlay` being set to be owned by `100000:100000` but in your case the child directories are having their ownership changed.

I wonder whether we can get a Podman reproducer. This seems to be tied to the `--userns=keep-id` flag, so could you try to run something like:

```
$ podman run -it --userns fedora echo hi
$ ls -lz ~/.local/share/containers/storage/overlay
```

I'd like to check whether the newly created directory is also having its ownership changed to `100000:100000`.

**Comment by inigoserna** [comment] 2022-06-02 19:02
Hi @HarryMichal, and thanks for your help.

Running the command without value for `--userns` fails, as it considers "fedora" the value for the parameter and "echo" the image to pull:
``` bash
~ > podman run -it --userns fedora echo hi
✔ registry.fedoraproject.org/echo:latest
Trying to pull registry.fedoraproject.org/echo:latest...
Error: initializing source docker://registry.fedoraproject.org/echo:latest: reading manifest latest in registry.fedoraproject.org/echo: manifest unknown: manifest unknown
```

But this works:
``` bash
~ > podman run -ti --userns="" fedora echo hi
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:latest...
Getting image source signatures
Copying blob 75f075168a24 done  
Copying config 3a66698e60 done  
Writing manifest to image destination
Storing signatures
hi
```

Directories look ok:
```
~ > ls -lZ ~/.local/share/containers/storage/overlay
total 0
drwx------. 6 inigo inigo unconfined_u:object_r:container_ro_file_t:s0 69 Jun  2 20:56 b7d796ba5c3712fe991dc728232cbad245d53f50afc1170f014ed894c4d0a25a
drwx------. 4 inigo inigo unconfined_u:object_r:container_ro_file_t:s0 55 Jun  2 20:56 bc403b707406bd69e304cc6b9a6263c652a782f48e288ea75166b3e2e00fd913
drwx------. 2 inigo inigo unconfined_u:object_r:container_ro_file_t:s0 74 Jun  2 20:56 l
```

**Comment by HarryMichal** [comment] 2022-06-02 19:11
> Running the command without value for `--userns` fails, as it considers "fedora" the value for the parameter and "echo" the image to pull

Ah, my mistake! The value to be passed to `--userns` is `keep-id`. So, the whole command would be `podman run -it --userns keep-id fedora echo hi`.

**Comment by inigoserna** [comment] 2022-06-02 19:40
It fails with the same error as `toolbox`:

``` bash
podman run -it --userns keep-id fedora echo hi
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:latest...
Getting image source signatures
Copying blob 75f075168a24 done  
Copying config 3a66698e60 done  
Writing manifest to image destination
Storing signatures
Error: crun: make `/home/inigo/.local/share/containers/storage/overlay/8fbc1dc14cdc27a16ab7b73492514cfd612e6b2be4db911398c6ff038f298dc6/merged` private: Permission denied: OCI permission denied

~ > ls -lZ ~/.local/share/containers/storage/overlay
total 0
drwx------. 4 100000 100000 unconfined_u:object_r:container_ro_file_t:s0  55 Jun  2 21:38 8fbc1dc14cdc27a16ab7b73492514cfd612e6b2be4db911398c6ff038f298dc6
drwx------. 6 inigo  inigo  unconfined_u:object_r:container_ro_file_t:s0  69 Jun  2 21:38 b7d796ba5c3712fe991dc728232cbad245d53f50afc1170f014ed894c4d0a25a
drwx------. 5 100000 100000 unconfined_u:object_r:container_ro_file_t:s0  68 Jun  2 21:38 cf3aa0dad39b880c585a72cf4145d49ef58a7cb688f60a30d0f75efc5ff3127c
drwx------. 2 inigo  inigo  unconfined_u:object_r:container_ro_file_t:s0 108 Jun  2 21:38 l
```

Thanks

**Comment by HarryMichal** [comment] 2022-06-02 21:22
@giuseppe, any ideas?

**Comment by giuseppe** [comment] 2022-06-06 08:48
could you please share the output of `findmnt -R /`?

**Comment by Arctize** [comment] 2022-06-14 08:27
I'll jump in here, since I'm seeing the exact same symptoms so far:

``` sh
$ toolbox enter
Error: failed to start container fedora-toolbox-36

$ podman run -it --userns="keep-id" fedora echo hi
Error: crun: make `/home/patrick/.local/share/containers/storage/overlay/c28082651c1dae0f48003f96053d192e2d456086745b3d11aa3ab49fe2f15932/merged` private: Permission denied: OCI permission denied

$ findmnt -R /
TARGET                        SOURCE          FSTYPE       OPTIONS
/                             /dev/mapper/luks-d8f5ddcb-b9d0-47b7-b0f1-e66b587fd358[/root]
                                              btrfs        rw,relatime,seclabel,compress=zstd:1,ssd,space_cache,subvolid=257,subvol=
├─/proc                       proc            proc         rw,nosuid,nodev,noexec,relatime
│ └─/proc/sys/fs/binfmt_misc  systemd-1       autofs       rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=
├─/sys                        sysfs           sysfs        rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/kernel/security      securityfs      securityfs   rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/cgroup            cgroup2         cgroup2      rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate,memory_recursiveprot
│ ├─/sys/fs/pstore            pstore          pstore       rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/firmware/efi/efivars efivarfs        efivarfs     rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/bpf               bpf             bpf          rw,nosuid,nodev,noexec,relatime,mode=700
│ ├─/sys/fs/selinux           selinuxfs       selinuxfs    rw,nosuid,noexec,relatime
│ ├─/sys/kernel/debug         debugfs         debugfs      rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/kernel/tracing       tracefs         tracefs      rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/fs/fuse/connections  fusectl         fusectl      rw,nosuid,nodev,noexec,relatime
│ └─/sys/kernel/config        configfs        configfs     rw,nosuid,nodev,noexec,relatime
├─/dev                        devtmpfs        devtmpfs     rw,nosuid,seclabel,size=4096k,nr_inodes=1048576,mode=755,inode64
│ ├─/dev/shm                  tmpfs           tmpfs        rw,nosuid,nodev,seclabel,inode64
│ ├─/dev/pts                  devpts          devpts       rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000
│ ├─/dev/mqueue               mqueue          mqueue       rw,nosuid,nodev,noexec,relatime,seclabel
│ └─/dev/hugepages            hugetlbfs       hugetlbfs    rw,relatime,seclabel,pagesize=2M
├─/run                        tmpfs           tmpfs        rw,nosuid,nodev,seclabel,size=3250500k,nr_inodes=819200,mode=755,inode64
│ └─/run/user/1000            tmpfs           tmpfs        rw,nosuid,nodev,relatime,seclabel,size=1625248k,nr_inodes=406312,mode=700
│   ├─/run/user/1000/gvfs     gvfsd-fuse      fuse.gvfsd-f rw,nosuid,nodev,relatime,user_id=1000,group_id=1000
│   └─/run/user/1000/doc      portal          fuse.portal  rw,nosuid,nodev,relatime,user_id=1000,group_id=1000
├─/tmp                        tmpfs           tmpfs        rw,nosuid,nodev,seclabel,nr_inodes=1048576,inode64
├─/boot                       /dev/nvme0n1p2  ext4         rw,relatime,seclabel
│ └─/boot/efi                 /dev/nvme0n1p1  vfat         rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=
├─/home                       /dev/mapper/luks-d8f5ddcb-b9d0-47b7-b0f1-e66b587fd358[/home00]
│                                             btrfs        rw,relatime,seclabel,compress=zstd:1,ssd,space_cache,subvolid=256,subvol=
    rw,relatime,seclabel,compress=zstd:1,ssd,space_cache,subvolid=5,subvol=/
└─/var/lib/nfs/rpc_pipefs     sunrpc          rpc_pipefs   rw,relatime
```

``` sh
OS: Fedora Workstation 36, same happens on Arch Linux

Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.2
Built:        Mon May 30 18:03:28 2022
OS/Arch:      linux/amd64

crun version 1.4.5
commit: c381048530aa750495cf502ddb7181f2ded5b400

toolbox version 0.0.99.3
```

**Comment by matyat** [comment] 2022-07-23 10:38
Any progress on this? I'm also encountering this issue on a fresh install of Silverblue 36.

Trying to create a toolbox from an older fedora release results in the same errors as well:
```
[matthewyates@fedora ~]$ toolbox create
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:36 (500MB)? [y/N]: y
Created container: fedora-toolbox-36
Enter with: toolbox enter
[matthewyates@fedora ~]$ toolbox enter
Error: failed to start container fedora-toolbox-36
[matthewyates@fedora ~]$ toolbox create -r 35
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:35 (500MB)? [y/N]: y
Created container: fedora-toolbox-35
Enter with: toolbox enter fedora-toolbox-35
[matthewyates@fedora ~]$ toolbox enter fedora-toolbox-35
Error: failed to start container fedora-toolbox-35
```

**Comment by matyat** [comment] 2022-07-23 10:46
When start manually via podman i'm seeing the same error as above:
```
[matthewyates@fedora ~]$ podman start fedora-toolbox-36
Error: unable to start container "b85b9aa16e32dbd4640bf3d534a7fa2f2b21ba248f860994816a7c51dfd7e68f": crun: make `/var/home/matthewyates/.local/share/containers/storage/overlay/95df5aacf9723c1f208b516a4b11c535878f57c23fa6703679cd9fb233f80514/merged` private: Permission denied: OCI permission denied

**Comment by matyat** [comment] 2022-07-23 10:56
Err, I think I fixed it somehow on my workstation, but I'm not exactly sure what happened. I tried running command above, and got the expected error:
```
[matthewyates@fedora ~]$ podman run -it --userns=keep-id fedora echo hi
Error: crun: make `/var/home/matthewyates/.local/share/containers/storage/overlay/7d00eca1f6179fa2884bef1b29b5012f27a813271dbee3a74f8b530f26c78f13/merged` private: Permission denied: OCI permission denied
```

I then started playing around with the `--userns` arg without really understanding what I was doing:
```
[matthewyates@fedora ~]$ podman run -it --userns="" fedora echo hi
hi
[matthewyates@fedora ~]$ podman run -it --userns=nomap fedora echo hi
hi
```

I then ran the same command again:
```
[matthewyates@fedora ~]$ podman run -it --userns=keep-id fedora echo hi
hi
````

And now it appears to be working? I can also enter the toolbox just fine.

```
[matthewyates@fedora ~]$ toolbox enter

Welcome to the Toolbox; a container where you can install and run
all your tools.

 - Use DNF in the usual manner to install command line tools.
 - To create a new tools container, run 'toolbox create'.

For more information, see the documentation.

⬢[matthewyates@toolbox ~]$ 
```

This seems like a podman bug, though if anyone could explain what happen on my machine it would be greatly appreciated!.

**Comment by matthiasclasen** [comment] 2022-09-19 11:28
@giuseppe does the findmnt output help to understand whats going on here ?

**Comment by giuseppe** [comment] 2022-09-19 15:59
It seems fine to me, I can't spot anything unusual

**Comment by np22-jpg** [comment] 2022-12-22 09:47
I was facing this exact issue, so I ran the same commands as @matyat, and it started to work.

**Comment by debarshiray** [comment] 2023-01-18 13:50
Did this get solved?  Or, is anybody still able to reproduce this?

**Comment by inigoserna** [comment] 2023-01-18 15:03
> Did this get solved? Or, is anybody still able to reproduce this?

It's working here on Fedora 37.

**Comment by debarshiray** [comment] 2023-01-19 11:35
> > Did this get solved? Or, is anybody still able to reproduce this?
> 
> It's working here on Fedora 37.

Thanks for the feedback, @inigoserna !  I am going to close this issue then.

Thanks for your contributions and interest, all!

**Closed by debarshiray** 2023-01-19 11:35 UTC
Labels: 1. Bug, 7. Need Information

**Comment by LyesSaadi** [comment] 2023-02-13 08:33
Just wanted to pop in and say this happened to me too. Somehow, the commands cited above solved it for me... This is magical xD.

**Comment by LyesSaadi** [comment] 2023-02-14 16:34
It happened to me again, so I was able to pinpoint the command which made it work again :
```
podman run -it --userns=nomap fedora echo hi
```

**Comment by A6GibKm** [comment] 2024-10-28 08:25
I just ran into this issue on debian. The command above did fix it

```
$ podman --version
podman version 4.3.1
$ toolbox --version
toolbox version 0.0.99.3
```
