### ISSUE TITLE
First typed character lags

### ISSUE THREAD

**Issue by fbruetting** [containers/toolbox#364] opened 2020-01-18 16:57 UTC
`v0.0.17-1`

Since playing with `toolbox`, I recognized that often the first two characters I type after opening a toolbox get twisted (i.e. when I type `dnf`, the shell then prints `ndf`). I already wondered because this was never a real issue to me, and now I saw that over and over again, but thought maybe the system lagged.

Then today I set `toolbox enter` as the starting command of some shell profiles (tested GNOME-Terminal and Tilix) for trying to shift my work into my toolbox – then it got obvious that `toolbox` seems to be to blame here. This issue then gets more invasive by the first character leading to absolutely no action (seems to just get buffered), but the second character then flushes that buffer after printing that second character.

#### Examples:

* When I open such a shell and type `a`, I see absolutely nothing. When I then type `b`, I see the terminal printing `ba`.

* When I open such a shell and type `^D`, nothing happens, but when I afterwards type some normal character, just the second character gets printed.

* When I open such a shell and type `^D`, nothing happens, but when I afterwards type `\n` (Enter), the shell gets closed.

**Comment by HarryMichal** [comment] 2020-01-21 15:00
I can reproduce this reliably. I didn't investigate yet but recently there was a change in Podman because of a problem with inputting character prior to starting the container https://github.com/containers/libpod/issues/4397. Maybe it is related.

**Comment by debarshiray** [comment] 2020-01-21 17:43
Duplicate of https://github.com/containers/libpod/issues/4863

**Closed** 2020-01-21 17:44 UTC
