### ISSUE TITLE
Error: Failed to start container fedora-toolbox-34

### ISSUE THREAD

**Issue by Zlopez** [containers/toolbox#764] opened 2021-05-11 09:14 UTC
**Describe the bug**
I have a toolbox container spawned for a few days, normally working in it till today. Today I just got `Error: failed to start container fedora-toolbox-34` when running `toolbox enter`. I noticed that the state of the container in `toolbox list` is `exited`.

**Steps how to reproduce the behaviour**
1. `toolbox enter`

**Expected behaviour**
Toolbox is started and you are inside it.

**Actual behaviour**
`Error: failed to start container fedora-toolbox-34`

**Output of `toolbox --version` (v0.0.90+)**
0.0.99.1

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99.1-1.fc34.x86_64

**Output of `podman version`**
```
Version:      3.2.0-rc1
API Version:  3.2.0-rc1
Go Version:   go1.16.3
Built:        Wed May  5 23:03:46 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
podman-3.2.0-0.1.rc1.fc34.x86_64

**Info about your OS**
Fedora Silverblue 34 Version: 34.20210511.0 (2021-05-11T01:42:56Z)

**Additional context**
Output of `toolbox run -vvv fedora-toolbox-34`
```
level=debug msg="Running as real user ID 1000"
level=debug msg="Resolved absolute path to the executable as /usr/bin/toolbox"
level=debug msg="Running on a cgroups v2 host"
level=debug msg="Checking if /etc/subgid and /etc/subuid have entries for user zlopez"
level=debug msg="TOOLBOX_PATH is /usr/bin/toolbox"
level=debug msg="Toolbox config directory is /var/home/zlopez/.config/toolbox"
time="2021-05-11T11:00:16+02:00" level=info msg="podman filtering at log level debug"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called version.PersistentPreRunE(podman --log-level debug version --format json)"
time="2021-05-11T11:00:16+02:00" level=debug msg="Merged system config \"/usr/share/containers/containers.conf\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Using conmon: \"/usr/bin/conmon\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing boltdb state at /var/home/zlopez/.local/share/containers/storage/libpod/bolt_state.db"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph driver overlay"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph root /var/home/zlopez/.local/share/containers/storage"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using run root /run/user/1000/containers"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using static dir /var/home/zlopez/.local/share/containers/storage/libpod"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using tmp dir /run/user/1000/libpod/tmp"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using volume path /var/home/zlopez/.local/share/containers/storage/volumes"
time="2021-05-11T11:00:16+02:00" level=debug msg="Set libpod namespace to \"\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Not configuring container store"
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing event backend journald"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using OCI runtime \"/usr/bin/crun\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Default CNI network name podman is unchangeable"
time="2021-05-11T11:00:16+02:00" level=info msg="Setting parallel job count to 25"
time="2021-05-11T11:00:16+02:00" level=info msg="podman filtering at log level debug"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called version.PersistentPreRunE(podman --log-level debug version --format json)"
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Merged system config \"/usr/share/containers/containers.conf\""
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using conmon: \"/usr/bin/conmon\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing boltdb state at /var/home/zlopez/.local/share/containers/storage/libpod/bolt_state.db"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph driver overlay"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph root /var/home/zlopez/.local/share/containers/storage"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using run root /run/user/1000/containers"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using static dir /var/home/zlopez/.local/share/containers/storage/libpod"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using tmp dir /run/user/1000/libpod/tmp"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using volume path /var/home/zlopez/.local/share/containers/storage/volumes"
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Set libpod namespace to \"\""
time="2021-05-11T11:00:16+02:00" level=debug msg="[graphdriver] trying provided driver \"overlay\""
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay: mount_program=/usr/bin/fuse-overlayfs"
time="2021-05-11T11:00:16+02:00" level=debug msg="backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false"
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing event backend journald"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using OCI runtime \"/usr/bin/crun\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Default CNI network name podman is unchangeable"
time="2021-05-11T11:00:16+02:00" level=info msg="Setting parallel job count to 25"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called version.PersistentPostRunE(podman --log-level debug version --format json)"
level=debug msg="Current Podman version is 3.2.0-rc1"
level=debug msg="Creating runtime directory /run/user/1000/toolbox"
level=debug msg="Old Podman version is 3.2.0-rc1"
level=debug msg="Migration not needed: Podman version 3.2.0-rc1 is unchanged"
level=debug msg="Resolving container and image names"
level=debug msg="Container: ''"
level=debug msg="Distribution: ''"
level=debug msg="Image: ''"
level=debug msg="Release: ''"
level=debug msg="Resolved container and image names"
level=debug msg="Container: 'fedora-toolbox-34'"
level=debug msg="Image: 'fedora-toolbox:34'"
level=debug msg="Release: '34'"
level=debug msg="Checking if container fedora-toolbox-34 exists"
time="2021-05-11T11:00:16+02:00" level=info msg="podman filtering at log level debug"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called exists.PersistentPreRunE(podman --log-level debug container exists fedora-toolbox-34)"
time="2021-05-11T11:00:16+02:00" level=debug msg="Merged system config \"/usr/share/containers/containers.conf\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Using conmon: \"/usr/bin/conmon\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing boltdb state at /var/home/zlopez/.local/share/containers/storage/libpod/bolt_state.db"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph driver overlay"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph root /var/home/zlopez/.local/share/containers/storage"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using run root /run/user/1000/containers"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using static dir /var/home/zlopez/.local/share/containers/storage/libpod"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using tmp dir /run/user/1000/libpod/tmp"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using volume path /var/home/zlopez/.local/share/containers/storage/volumes"
time="2021-05-11T11:00:16+02:00" level=debug msg="Set libpod namespace to \"\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Not configuring container store"
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing event backend journald"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using OCI runtime \"/usr/bin/crun\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Default CNI network name podman is unchangeable"
time="2021-05-11T11:00:16+02:00" level=info msg="Setting parallel job count to 25"
time="2021-05-11T11:00:16+02:00" level=info msg="podman filtering at log level debug"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called exists.PersistentPreRunE(podman --log-level debug container exists fedora-toolbox-34)"
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Merged system config \"/usr/share/containers/containers.conf\""
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using conmon: \"/usr/bin/conmon\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing boltdb state at /var/home/zlopez/.local/share/containers/storage/libpod/bolt_state.db"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph driver overlay"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph root /var/home/zlopez/.local/share/containers/storage"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using run root /run/user/1000/containers"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using static dir /var/home/zlopez/.local/share/containers/storage/libpod"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using tmp dir /run/user/1000/libpod/tmp"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using volume path /var/home/zlopez/.local/share/containers/storage/volumes"
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Set libpod namespace to \"\""
time="2021-05-11T11:00:16+02:00" level=debug msg="[graphdriver] trying provided driver \"overlay\""
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay: mount_program=/usr/bin/fuse-overlayfs"
time="2021-05-11T11:00:16+02:00" level=debug msg="backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false"
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing event backend journald"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using OCI runtime \"/usr/bin/crun\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Default CNI network name podman is unchangeable"
time="2021-05-11T11:00:16+02:00" level=info msg="Setting parallel job count to 25"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called exists.PersistentPostRunE(podman --log-level debug container exists fedora-toolbox-34)"
level=debug msg="Inspecting mounts of container fedora-toolbox-34"
time="2021-05-11T11:00:16+02:00" level=info msg="podman filtering at log level debug"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called inspect.PersistentPreRunE(podman --log-level debug inspect --format json --type container fedora-toolbox-34)"
time="2021-05-11T11:00:16+02:00" level=debug msg="Merged system config \"/usr/share/containers/containers.conf\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Using conmon: \"/usr/bin/conmon\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing boltdb state at /var/home/zlopez/.local/share/containers/storage/libpod/bolt_state.db"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph driver overlay"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph root /var/home/zlopez/.local/share/containers/storage"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using run root /run/user/1000/containers"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using static dir /var/home/zlopez/.local/share/containers/storage/libpod"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using tmp dir /run/user/1000/libpod/tmp"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using volume path /var/home/zlopez/.local/share/containers/storage/volumes"
time="2021-05-11T11:00:16+02:00" level=debug msg="Set libpod namespace to \"\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Not configuring container store"
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing event backend journald"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using OCI runtime \"/usr/bin/crun\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Default CNI network name podman is unchangeable"
time="2021-05-11T11:00:16+02:00" level=info msg="Setting parallel job count to 25"
time="2021-05-11T11:00:16+02:00" level=info msg="podman filtering at log level debug"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called inspect.PersistentPreRunE(podman --log-level debug inspect --format json --type container fedora-toolbox-34)"
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Merged system config \"/usr/share/containers/containers.conf\""
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using conmon: \"/usr/bin/conmon\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing boltdb state at /var/home/zlopez/.local/share/containers/storage/libpod/bolt_state.db"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph driver overlay"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using graph root /var/home/zlopez/.local/share/containers/storage"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using run root /run/user/1000/containers"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using static dir /var/home/zlopez/.local/share/containers/storage/libpod"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using tmp dir /run/user/1000/libpod/tmp"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using volume path /var/home/zlopez/.local/share/containers/storage/volumes"
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay storage already configured with a mount-program"
time="2021-05-11T11:00:16+02:00" level=debug msg="Set libpod namespace to \"\""
time="2021-05-11T11:00:16+02:00" level=debug msg="[graphdriver] trying provided driver \"overlay\""
time="2021-05-11T11:00:16+02:00" level=debug msg="overlay: mount_program=/usr/bin/fuse-overlayfs"
time="2021-05-11T11:00:16+02:00" level=debug msg="backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false"
time="2021-05-11T11:00:16+02:00" level=debug msg="Initializing event backend journald"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
time="2021-05-11T11:00:16+02:00" level=debug msg="Using OCI runtime \"/usr/bin/crun\""
time="2021-05-11T11:00:16+02:00" level=debug msg="Default CNI network name podman is unchangeable"
time="2021-05-11T11:00:16+02:00" level=info msg="Setting parallel job count to 25"
time="2021-05-11T11:00:16+02:00" level=debug msg="Called inspect.PersistentPostRunE(podman --log-level debug inspect --format json --type container fedora-toolbox-34)"
level=debug msg="Starting container fedora-toolbox-34"
Error: failed to start container fedora-toolbox-34
```

I deleted the faulty one and created a new one, which worked without issue. We will see if this will happen in the future.

**Comment by HarryMichal** [comment] 2021-05-12 16:30
Duplicate of #760.

**Closed by HarryMichal** 2021-05-12 16:30 UTC
Labels: 1. Bug
