### ISSUE TITLE
Feature request: specify shell at toolbox creation time

### ISSUE THREAD

**Issue by yann-soubeyrand** [containers/toolbox#413] opened 2020-04-18 21:57 UTC
Hello,

Currently, the shell launched when entering a toolbox is the one specified in the `SHELL` environment variable. I'd like to be able to specify which shell will be used by a toolbox at creation time. This would allow having a different shell on the host (bash) and in the toolbox (zsh). It would also allow having several toolboxes, each with its specific shell (maybe a python toolbox using an interactive python interpreter as shell?).

I can try to work on a PR if this idea is accepted.

**Comment by HarryMichal** [comment] 2020-04-24 08:56
Hey @yann-soubeyrand! Sounds good to me. Let's hear what @debarshiray thinks.

If you were to make the PR, would you mind making it for the [new version of Toolbox](https://github.com/containers/toolbox/issues/318)?

**Comment by debarshiray** [comment] 2020-05-13 14:05
Yes, this does sound like a neat idea to me.

And, yes, as @HarryMichal said, please work on the [Go version](https://github.com/containers/toolbox/pull/318/).

**Comment by debarshiray** [comment] 2021-11-16 01:50
https://github.com/containers/toolbox/issues/908 has some more in-depth discussion on this.

**Comment by debarshiray** [comment] 2021-11-16 01:51
Duplicate of https://github.com/containers/toolbox/issues/908

**Closed by debarshiray** 2021-11-16 01:51 UTC
Labels: 5. Good First Issue, 1. Feature request

**Comment by debarshiray** [comment] 2022-11-28 19:37
I realized that I never said this clearly ...

It will be better to teach Toolbx to respect the user's local configuration inside the container instead of adding an option to `toolbox create` to specify a shell.  eg., a user can use [chsh(1)](https://linux.die.net/man/1/chsh) or [usermod -s](https://man7.org/linux/man-pages/man8/usermod.8.html) inside the container to change their shell.

The biggest problem with adding an option to `toolbox create` is that it won't have any effect on existing containers.  Plus, every extra option increases Toolbx's the maintenance burden -- it's another user-visible thing that can't be changed without consequences.

This is what https://github.com/containers/toolbox/issues/908 is about.
