### ISSUE TITLE
cannot find name for group ID 1000

### ISSUE THREAD

**Issue by alexpattyn** [containers/toolbox#549] opened 2020-08-31 03:53 UTC
# Issue

Created a new container using the fedora 32 image. Seems to have some issues when using sudo within the container. If I run `sudo dnf update` it'll ask for a password, and won't accept the host password. Normally this doesn't require a password.  

## Error

When creating a new container the follow error appears. 

```
$ toolbox enter -c rust-dev 
/usr/bin/id: cannot find name for group ID 1000
```

# Specs

```
● ostree://fedora:fedora/32/x86_64/silverblue
                   Version: 32.20200829.0 (2020-08-29T16:38:01Z)
                BaseCommit: d7bf68998a9224f18067af35cb3d16508cbf7f66f11426b265968956100f3f4e
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
           LayeredPackages: gnome-tweak-tool
```

```
$ toolbox --version
toolbox version 0.0.93
```

**Comment by yilkalargaw** [comment] 2020-08-31 08:52
I can confirm the issue. It happened on a new install of fedora silverblue32  and in my case it is user 1001 instead of 1000

```
ostree://fedora:fedora/32/x86_64/silverblue
                   Version: 32.20200829.0 (2020-08-29T16:38:01Z)
                BaseCommit: d7bf68998a9224f18067af35cb3d16508cbf7f66f11426b265968956100f3f4e
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
           LayeredPackages: awesome conky joe pavucontrol picom tlp udiskie volumeicon


```

**Comment by HarryMichal** [comment] 2020-08-31 10:03
Hi @alexpattyn! This issue is a duplicate of #523.

**Closed by HarryMichal** 2020-08-31 10:03 UTC

**Comment by HarryMichal** [comment] 2020-08-31 10:05
@yilkalargaw, the latest release of Toolbox should fix the problem at least partially. https://github.com/containers/toolbox/releases/tag/0.0.95

**Comment by alexpattyn** [comment] 2020-09-01 00:20
@HarryMichal Thanks! My bad on the duplicate :/ I'll keep an eye out for the update in fedoras repos.

**Comment by LeonardKoenig** [comment] 2020-09-02 13:33
@HarryMichal I'm not sure whether this really is a duplicate, I was affected by #523 and while this is fixed in 0.0.95 this bug here still surfaces:

```
$ toolbox enter -r f32
/usr/bin/id: cannot find name for group ID 60021
```

Maybe it's relevant that I'm using systemd-homed on Arch?

**Comment by DataRepository** [comment] 2020-09-09 01:37
![Screenshot from 2020-09-09 02-36-34](https://user-images.githubusercontent.com/12666951/92544245-56bb4480-f245-11ea-94ad-da6b41180bc3.png)

I'm experiencing the same issue. Has anyone been able to resolve it?

**Comment by HarryMichal** [comment] 2020-09-09 10:32
It is an upstream bug (https://github.com/containers/podman/issues/7389) that was discussed in the ticket I shared in my previous comment. I'm certain this is a duplicate issue :-)

According to upstream developers the fix should be present in the next release (the current being v2.0.6).

**Comment by HarryMichal** [comment] 2020-09-09 10:35
@martinpitt shared a workaround with us that can fix the error message: https://github.com/containers/toolbox/issues/523#issuecomment-688271542

But unless your workflow somehow relies on the presence of the name of the group, there's no real need to use the workaround. I hope the new version of Podman will fix the error message for all affected containers.

**Comment by HarryMichal** [comment] 2020-09-22 13:50
This should be fixed in the next release of Podman (current version is v2.0.6): https://github.com/containers/podman/pull/7541.

**Comment by wkrea** [comment] 2020-10-06 20:32
hey @DataRepository @LeonardKoenig 

the same issue happens to me, so i solved this just updating my distro

![image](https://user-images.githubusercontent.com/47398695/95256846-00600800-07e9-11eb-82e7-561954fc72cb.png)

best regrads!!!
