### ISSUE TITLE
expose GUI apps to host's Desktop environment

### ISSUE THREAD

**Issue by bam80** [containers/toolbox#555] opened 2020-09-09 19:18 UTC
Right now I have to manually copy .desktop and icon files of containerized apps to the host's relevant directories, and edit the .desktop file afterwards so that it can be explorable/runnable there.
I did it ones but it would be too bothering to repeat, however I have other container apps I would like to expose too.
So I think it would be helpful to have that job automated by a script or other mean.

**Comment by HarryMichal** [comment] 2020-09-09 20:03
Hi @bam80! I believe this is a duplicate of https://github.com/containers/toolbox/issues/417.

**Closed by HarryMichal** 2020-09-09 20:03 UTC
Labels: feature request
