### ISSUE TITLE
`toolbox run` command isn't terminated properly when terminal emulator is exited

### ISSUE THREAD

**Issue by ghost** [containers/toolbox#1157] opened 2022-11-15 07:47 UTC
**Describe the bug**

`toolbox run` command isn't terminated properly when terminal emulator is exited, causing processes to linger around without user's awareness.

**Steps how to reproduce the behaviour**

1. Open System Monitor / Task Manager equivilent in your desktop environment
2. Search for `sleep`
3. Execute the following command in a terminal emulator (GNOME Terminal):

```bash
toolbox run sleep 30
```

4. Before `sleep` runs out of time, try to close the terminal emulator
5. It'll prompt for something like this:

![image](https://user-images.githubusercontent.com/40300931/191938419-18d5f1e0-7daf-4946-beeb-f2aa06cf07c1.png)

Insist closing it by pressing `Close Terminal`.

**Expected behaviour**

`sleep` process is terminated.

**Actual behaviour**

`sleep` keeps lingering around.

**Output of `toolbox --version` (v0.0.90+)**

`toolbox version 0.0.99.3`

**Toolbox package info (`rpm -q toolbox`)**

`toolbox-0.0.99.3-6.fc36.x86_64`

**Output of `podman version`**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Thu Sep  8 03:58:19 2022
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**

`podman-4.2.1-2.fc36.x86_64`

**Info about your OS**

Fedora Silverblue 36

**Additional context**

> This is a screenshot which represent the issue better:
> 
> ![image](https://user-images.githubusercontent.com/40300931/201854868-f89a75dd-323d-4bbb-81bf-34dc05b60c82.png)
> 
> If I try to close the terminal emulator, it'll prompt the following:
> 
> ![image](https://user-images.githubusercontent.com/40300931/191938419-18d5f1e0-7daf-4946-beeb-f2aa06cf07c1.png)
> 
> If I press "Close Terminal", `sh`, `toolbox` and `podman` (which runs `exec` command) will be terminated because they're child process of the vte session.
> 
> However, notice the `conmon` and its child process `sleep` aren't part of `gnome-terminal-server`. When `sh` is terminated, `podman` (`exec` command) will be terminated but the corresponding `conmon` process will be kept intact. As a result, `sleep 30` isn't terminated properly.
> 
> And `sleep 30` is only used for demonstration. In reality one could run something resource intensive, and then close the terminal emulator not knowing they're lingering in the background.

Source: https://github.com/containers/toolbox/issues/1204

**Comment by debarshiray** [comment] 2023-09-30 12:35
Duplicate of https://github.com/containers/toolbox/issues/1204

**Comment by debarshiray** [comment] 2023-09-30 12:36
I know you had originally filed https://github.com/containers/toolbox/issues/1204 against Podman, but for some reason @rhatdan moved it to Toolbx, and he hasn't responded since.  So, for all practical purposes, we can treat them as duplicates.

**Comment by debarshiray** [comment] 2023-09-30 12:37
Thanks for playing with Toolbx and contributing.

**Closed by debarshiray** 2023-09-30 12:37 UTC
Labels: 1. Bug
