### ISSUE TITLE
Unable to create containers, podman version could not be read

### ISSUE THREAD

**Issue by cschalle** [containers/toolbox#288] opened 2019-10-07 14:11 UTC
[cschalle@ultron ~]$ toolbox create
toolbox: unable to migrate containers: Podman version couldn't be read

[cschalle@ultron ~]$ podman --log-level debug version --format "{{.Version}}"
DEBU[0000] using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/cschalle/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/cschalle/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000                
DEBU[0000] Using static dir /home/cschalle/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/cschalle/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend                   
ERRO[0000] could not get runtime: unknown event logger type:  
[cschalle@ultron ~]$

**Comment by HarryMichal** [comment] 2019-10-07 14:47
I would say that this is not an issue caused by Toolbox but by Podman. https://github.com/containers/libpod/issues/4210

**Comment by cschalle** [comment] 2019-10-07 16:36
Yeah, Debarshi asked to to file the ticket so he could track it. That said removing libpod.conf as mentioned in that libpod bug do seem to resolve the issue.

**Comment by debarshiray** [comment] 2019-10-07 21:39
@cschalle could you try `rm -rf ~/.config/containers` ?

**Comment by debarshiray** [comment] 2019-10-07 21:39
Duplicate of https://github.com/containers/libpod/issues/4210

**Closed** 2019-10-07 21:40 UTC
