### ISSUE TITLE
ping <host> doesn't work - Operation not permitted

### ISSUE THREAD

**Issue by dwrobel** [containers/toolbox#316] opened 2019-10-30 20:06 UTC
Trying to execute `ping` inside the toolbox _(f30 image)_ returns the following:
```
$ ping host
ping: socket: Operation not permitted
```
That seems to be caused by the lack of the capabilities _(cap_net_admin,cap_net_raw+p):
```
$ getcap $(which ping)
$
```

**Comment by evelineraine** [comment] 2019-10-31 04:03
I don't think it's because of capabilities on the ping binary. None are set in my `f30` image, yet it works:
```shell
toolbox$ getcap $(which ping)
toolbox$ ping -c 1 github.com
PING github.com (140.82.118.4) 56(84) bytes of data.
64 bytes from lb-140-82-118-4-ams.github.com (140.82.118.4): icmp_seq=1 ttl=51 time=115 ms
--- github.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 114.954/114.954/114.954/0.000 ms
toolbox$ cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Fedora 30 (Container Image)"
```

I'm running the fresh `f30` image on my Fedora 31 host with toolbox `0.0.15-1.fc31` and podman `podman-1.6.2-2.fc31`.

Here is the `inspect` output for this container: [fedora-toolbox-30.inspect.txt](https://github.com/containers/toolbox/files/3792107/fedora-toolbox-30.inspect.txt)

**Comment by dwrobel** [comment] 2019-10-31 07:50
I tested it also on f31 image and here is the strace output:

```
$ strace -ecapget,socket ping host
capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, NULL) = 0
capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, {effective=0, permitted=0, inheritable=0}) = 0
capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, NULL) = 0
capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, NULL) = 0
capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, {effective=0, permitted=0, inheritable=0}) = 0
socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP) = -1 EACCES (Permission denied)
socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = -1 EPERM (Operation not permitted)
socket(AF_INET6, SOCK_DGRAM, IPPROTO_ICMPV6) = -1 EACCES (Permission denied)
socket(AF_INET6, SOCK_RAW, IPPROTO_ICMPV6) = -1 EPERM (Operation not permitted)
ping: socket: Operation not permitted
```
Versions used:
```
$ rpm -qv podman toolbox
podman-1.6.2-2.fc30.x86_64
toolbox-0.0.15-1.fc30.noarch
```

**Comment by HarryMichal** [comment] 2019-10-31 09:34
This is a duplicate of #214. The problem should be fixed in Fedora 31. Closing.

**Closed by HarryMichal** 2019-10-31 09:34 UTC
