### ISSUE TITLE
Unable to start container if user is managed by Active Directory (contains @ "at" sign)

### ISSUE THREAD

**Issue by Mazwak** [containers/toolbox#1022] opened 2022-03-14 15:20 UTC
**Describe the bug**

If I try to enter a toolbox and my username contains '@', it fails with:
Error: invalid entry point PID of container test

If I try to attach with podman, the error is more obvious:
passwd: Libuser error at line: 210 - name contains invalid char `@'.
Error: failed to remove password for user login@company.com: failed to invoke passwd(1)

**Steps how to reproduce the behaviour**
Create a user with '@' in it.
toolbox create test
toolbox enter test

**Expected behaviour**
Entering the toolbox without error, at best.
Failing with a usefull message, at least.

**Actual behaviour**
Fails with a useless message.
I agree with https://github.com/containers/toolbox/issues/691#issuecomment-987977286 that debug info did not help at all.
Only trying with podman, after reading https://github.com/containers/toolbox/issues/691#issuecomment-776911477 did help.

**Output of `toolbox --version` (v0.0.90+)**

toolbox version 0.0.99.3

**Toolbox package info (`rpm -q toolbox`)**

toolbox-0.0.99.3-2.fc35.x86_64

**Output of `podman version`**
e.g.,
```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 22:45:07 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**

podman-3.4.4-1.fc35.x86_64

**Info about your OS**
Fedora Silverblue 35

**Additional context**

My user is imported from ActiveDirectory, and thus is login@company.com.

**Comment by yrro** [comment] 2022-11-17 17:39
The problem is really the `usermod` command. I can `toolbox enter debian-10` just fine, which ships `shadow-utils` 4.5; but `toolbox-enter centos-stream8`, which ships `shadow-utils` 4.6, gives me this error. Additionally I've noticed in the man page that usernames are limited to 32 characters, which is way too short for many users in an Active Directory environment!

But Toolbox can't do anything to fix the `usermod` command in dozens of old versions of distros. So what else could it do; detecting that `useradd` has failed, and re-running it with a modified username that is known to be accepted by `usermod` would be one approach.

**Comment by debarshiray** [comment] 2022-11-29 02:02
Duplicate of https://github.com/containers/toolbox/issues/585

**Comment by debarshiray** [comment] 2022-11-29 02:06
Closing.  Thanks for your interest in Toolbx and digging into this!

**Closed by debarshiray** 2022-11-29 02:06 UTC
Labels: 1. Bug, 5. Help Wanted, 2. Container Realm, 2. Container Configuration

**Comment by yrro** [comment] 2022-11-29 10:01
Thanks. Apologies for not finding the duplicate issue...
