### ISSUE TITLE
Sync Toolbox images and the host's OpenGL implementation (`mesa-dri-drivers` not in base image)

### ISSUE THREAD

**Issue by returntrip** [containers/toolbox#538] opened 2020-08-25 18:16 UTC
**Is your feature request related to a problem? Please describe.**
Applications requiring an OpenGL implementation are currently not working, for example: `imv`.

**Describe the solution you'd like**
Make sure that the host OpenGL implementation is in sync with the host.  For instance, the `mesa-dri-drivers` is installed on Fedora Silverblie/Workstation by default.

**Describe alternatives you've considered**
Manually install `mesa-dri-drivers`

Or

Ask package mantainer(s) to add `Recommends` to the spec file of the affected package(s)

**Additional context**
Coversation around `imv` PR:
https://src.fedoraproject.org/rpms/imv/pull-request/1

**Comment by debarshiray** [comment] 2024-08-02 11:13
Duplicate of https://github.com/containers/toolbox/issues/1110

**Closed** 2024-08-02 11:13 UTC
Labels: 1. Feature request
