### ISSUE TITLE
container continues to run even after shell exit

### ISSUE THREAD

**Issue by bam80** [containers/toolbox#540] opened 2020-08-26 14:01 UTC
After `toolbox enter`, I pressed `Ctrl+D` in the shell to exit it, and still see the container is running:
```
$ toolbox enter --container toolbox
⬢[bam@toolbox bam]$
<Ctrl+D>

$ toolbox list 
IMAGE ID      IMAGE NAME                                            CREATED
a198bc8c3cda  registry.fedoraproject.org/f31/fedora-toolbox:31      9 months ago
fe7b8c2393f9  registry.fedoraproject.org/f32/fedora-toolbox:32      4 months ago
3864bc58ab7b  registry.fedoraproject.org/f33/fedora-toolbox:33      4 months ago
b390f0663e2a  registry.fedoraproject.org/f33/fedora-toolbox:latest  2 weeks ago

CONTAINER ID  CONTAINER NAME     CREATED       STATUS      IMAGE NAME
c27048bea726  fedora-toolbox-31  6 months ago  configured  registry.fedoraproject.org/f31/fedora-toolbox:31
f48d171dc79e  fedora-toolbox-32  3 months ago  running     registry.fedoraproject.org/f32/fedora-toolbox:32
323c52fecd29  fedora-toolbox-33  2 hours ago   configured  registry.fedoraproject.org/f33/fedora-toolbox:33
65a6710e56df  gnome              3 months ago  exited      registry.fedoraproject.org/f31/fedora-toolbox:31
12ad2e19c81e  kde                4 months ago  exited      registry.fedoraproject.org/f31/fedora-toolbox:31
3cda239851f1  kde.f32            4 months ago  exited      registry.fedoraproject.org/f32/fedora-toolbox:32
f80dca917199  kde.f33            4 months ago  exited      registry.fedoraproject.org/f33/fedora-toolbox:33
10f2407ade08  kde.f33.prebuilt   3 months ago  exited      registry.fedoraproject.org/f33/fedora-toolbox:33
36e5ff304f93  kde.prebuilt       3 months ago  configured  registry.fedoraproject.org/f31/fedora-toolbox:31
6e60d3c55fb7  scanner            4 months ago  configured  registry.fedoraproject.org/f31/fedora-toolbox:31
b35ff6c1acfe  setools            4 months ago  configured  registry.fedoraproject.org/f31/fedora-toolbox:31
f429c215fa02  toolbox            2 hours ago   running     registry.fedoraproject.org/f32/fedora-toolbox:32
0954ffa1d256  weston             3 months ago  configured  registry.fedoraproject.org/f31/fedora-toolbox:31

$ toolbox --version
toolbox version 0.0.93
```

**Comment by debarshiray** [comment] 2020-08-26 14:15
Duplicate of https://github.com/containers/toolbox/issues/114

**Closed by debarshiray** 2020-08-26 14:15 UTC
Labels: bug
