### ISSUE TITLE
There's no f40 toolbox, so running toolbox enter on Rawhide fails now F39 has branched

### ISSUE THREAD

**Issue by aaradhak** [containers/toolbox#1350] opened 2023-08-15 21:21 UTC
**Describe the bug**
Fedora 39 has branched from Rawhide. There's no 'f40' toolbox container, apparently, so running `toolbox enter` on Rawhide fails now.

**Steps how to reproduce the behaviour**
1) Install Fedora Rawhide and toolbox
2) Run `toolbox enter` or run `ext.config.toolbox` kola test

**Expected behaviour**
Toolbox works or `ext.config.toolbox` kola test PASS

**Actual behaviour**
Toolbox fails

**Info about your OS**
e.g., Fedora Rawhide

**Comment by juhp** [comment] 2023-08-25 10:18
This might be a coreos toolbox request?  If so this probably the wrong place?

`fedora-toolbox:40` has been available for some weeks now.

**Comment by debarshiray** [comment] 2023-09-28 04:59
Yes, I can do:
```
$ toolbox create --release 40
```

... on my Fedora 38 Workstation.

**Comment by debarshiray** [comment] 2023-12-20 23:32
Duplicate of https://github.com/containers/toolbox/issues/1233

**Closed by debarshiray** 2023-12-20 23:32 UTC
Labels: 1. Bug
