### ISSUE TITLE
toolbox enter failed with "Error: failed to start container fedora-toolbox-37"

### ISSUE THREAD

**Issue by coiby** [containers/toolbox#1297] opened 2023-05-14 13:21 UTC
**Describe the bug**

`toolbox enter` failed with "Error: failed to start container fedora-toolbox-37".

**Steps how to reproduce the behaviour**
1.  dnf install VirtualBox
2. toolbox create
3. toolbox enter
 
**Expected behaviour**
`toolbox enter` should work.

**Actual behaviour**

`toolbox enter` failued.

**Screenshots**

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.4
`

**Toolbox package info (`rpm -q toolbox`)**
e.g., `toolbox-0.0.99.4-1.fc37.x86_64`

**Output of `podman version`**
```
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 23:42:56 2023
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-4.5.0-1.fc37.x86_64`

**Info about your OS**
e.g., Fedora 37

**Additional context**

1. journalctl shows the following logs with `toolbox enter -vv`
```
conmon[3469]: conmon d5bc67555f5777078a4d <nwarn>: runtime stderr: mkdir `/dev/vboxusb/003`: Permission denied
conmon[3469]: conmon d5bc67555f5777078a4d <error>: Failed to create container: exit status 1
```
2. `sudo chmod 755 /dev/vboxusb/003`  (suggested by [OCI Permission Denied when running on host with VirtualBox · Issue #995 · containers/crun](https://github.com/containers/crun/issues/995)) or remove current user from the vboxusers group could workaround this issue.
3. `podman --group-add keep-groups` seems to also work according to [`podman run` fails with Permission denied: OCI permission denied · Issue #14284 · containers/podman](https://github.com/containers/podman/issues/14284). But I don't know how to let toolbox call podman with ` --group-add keep-groups`.

**Comment by mtalexan** [comment] 2023-08-14 18:17
This prior issue seems to have been closed incorrectly, and is a duplicate: https://github.com/containers/toolbox/issues/247

**Comment by debarshiray** [comment] 2023-09-28 07:32
Duplicate of https://github.com/containers/toolbox/issues/1348

**Closed** 2023-09-28 07:32 UTC
Labels: 1. Bug
