### ISSUE TITLE
/dev/pts/* is owned by root

### ISSUE THREAD

**Issue by swick** [containers/toolbox#1242] opened 2023-02-20 15:51 UTC
**Describe the bug**
Running qemu as part of the mutter test suit requires access to /proc/self/fd/2 which is a  symlink to /dev/pts/4 in my case. All of the files in /dev/pts are owned by root. Simply chowning them does work around the issue.

**Steps how to reproduce the behaviour**
`qemu-system-x86_64: -chardev file,id=console,path=/proc/self/fd/2`, as issued by the mutter test suit.

**Expected behaviour**
`/dev/pts/*` should be owned by the user running the toolbox.

**Actual behaviour**
`/dev/pts/*` is owned by root.

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.3

**Comment by swick** [comment] 2023-02-20 15:52
Apparently I'm blind. This is a duplicate.

**Comment by debarshiray** [comment] 2023-03-02 19:38
It happens to me all the time.  :)

**Comment by debarshiray** [comment] 2023-03-02 19:38
Duplicate of https://github.com/containers/toolbox/issues/1016

**Closed by debarshiray** 2023-03-02 19:38 UTC
Labels: 1. Bug
