### ISSUE TITLE
Pass host graphics drivers into container

### ISSUE THREAD

**Issue by Jacalz** [containers/toolbox#1025] opened 2022-03-20 09:16 UTC
## Is your feature request related to a problem? Please describe.

The majority of my spare time is spent developing graphical applications. To be able to develop those comfortably on something like Fedora Silverblue, I need to do so inside a toolbox. However, to be able to run the applications inside it, I need to install graphics drivers inside the toolbox as well.

That necessity seems to me like an annoying and unintuitive step. All installation commands (such as those that I use on https://developer.fyne.io/started/) would have to be updated with a specific section about installing inside a toolbox. My view is that if something can be rendered on the screen, it should do so using the same drivers that the host desktop environment uses.

This not only affects me as a GUI developer, but also anyone installing a graphical application (through dnf or similar) that, for various reasons, isn't yet available as a flatpak.

## Describe the solution you'd like
I'd like the graphics drivers from the host to be passed into the container, this would make the toolbox a lot better integrated into the host system.

## Describe alternatives you've considered**

Graphics drivers could be installed by default, but that would significantly increase toolbox sizes. It also would not work very well for proprietary Nvidia drivers.

## Additional context
This feature is related to issues like https://github.com/containers/toolbox/issues/1023 and https://github.com/containers/toolbox/issues/116.

**Comment by Jacalz** [comment] 2022-03-20 09:21
Looking at the goals (https://github.com/containers/toolbox/blob/main/GOALS.md), it seems to me like this would be very much in line with them.

**Comment by akdev1l** [comment] 2022-06-05 13:01
I have a hack to passthrough the nvidia drivers to a podman container - seems to work well enough (but I've managed to crash my graphic stack a couple times)

```
NVIDIA_DRIVERS="$(rpm -ql xorg-x11-drv-nvidia xorg-x11-drv-nvidia-libs | grep -v ".build-id" | xargs -I{} bash -c "test -e {} && echo '-v {}:{}:ro '")"

podman run --rm -it $NVIDIA_DRIVERS fedora:latest
```

but this only works as long as the host and container have the same base.

**Comment by debarshiray** [comment] 2022-09-10 06:59
This is a duplicate of two different issues.

For the proprietary NVIDIA driver, see https://github.com/containers/toolbox/issues/116

In this case, we really do need to pass the user-space drivers from the host into the container because the kernel and user sides of NVIDIA's proprietary driver absolutely must match.

For hardware with free drivers, it will be easier, see https://github.com/containers/toolbox/issues/1110

In this case, we likely won't do any passthrough.  There's no requirement for the kernel and user sides to stay synchronized, and passing shared libraries from a different host OS to a different container will lead to runtime ABI problems.

**Comment by debarshiray** [comment] 2022-09-10 07:00
Closing.  Thanks for stopping by!

By the way, Fyne looks like a really interesting project.  Good luck with that.  :)

**Closed by debarshiray** 2022-09-10 07:00 UTC
Labels: 5. Help Wanted, 7. Need Information, 2. Images, 1. Feature request, 2. Container Configuration

**Comment by debarshiray** [comment] 2022-09-10 07:35
Duplicate of https://github.com/containers/toolbox/issues/116

**Comment by debarshiray** [comment] 2022-09-10 07:36
Duplicate of https://github.com/containers/toolbox/issues/1110

**Comment by Iolaum** [comment] 2023-02-19 07:56
Tried the way suggested [here](https://github.com/containers/toolbox/issues/1025#issuecomment-1146800559) but got a permissions error:

```
$ podman run --rm -it $NVIDIA_DRIVERS fedora:latest
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:latest...
Getting image source signatures
Copying blob 8e52fb4aba15 done  
Copying config f65672aa0c done  
Writing manifest to image destination
Storing signatures
/bin/bash: error while loading shared libraries: /lib64/libc.so.6: cannot apply additional memory protection after relocation: Permission denied
```

**Comment by akdev1l** [comment] 2023-02-19 21:25
Fwiw this is how I tested that: https://github.com/akdev1l/etbox/blob/master/src/etbox-run#L22

Your podman call might be missing other things that aren't nvidia related (or the whole thing could be failing because it is kinda hacky :-()
