### ISSUE TITLE
Can't copy /etc/profile.d/toolbox.sh to old containers with colons in their names

### ISSUE THREAD

**Issue by refi64** [containers/toolbox#186] opened 2019-06-06 22:52 UTC
At this point I'm just going to recreate it, but still filing here because it's still a bug.

Basically I just run `toolbox -v enter` and, voila:

```
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 1.3.1 is unchanged
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: container is fedora-toolbox-30
toolbox: checking if container fedora-toolbox-30 exists
toolbox: container fedora-toolbox-30 not found
toolbox: container fedora-toolbox-ryan:30 found
toolbox: trying to start container fedora-toolbox-ryan:30
toolbox: looking for /etc/profile.d/toolbox.sh in container fedora-toolbox-ryan:30
Error: exit status 1
toolbox: copying /etc/profile.d/toolbox.sh to container fedora-toolbox-ryan:30
Error: invalid arguments /etc/profile.d/toolbox.sh, fedora-toolbox-ryan:30:/etc/profile.d you must use just one container
toolbox: unable to copy /etc/profile.d/toolbox.sh to container fedora-toolbox-ryan:30
```

**Comment by vinzent** [comment] 2019-06-07 10:56
@refi64 did re-create work out for you? didnt solve the issue for me.

**Comment by refi64** [comment] 2019-06-07 18:28
@vinzent For me it creating a new one indeed fixed the problem.

**Comment by miabbott** [comment] 2019-06-13 12:56
Hit this today with `toolbox 0.10` and `podman 1.4.0`

```
$ toolbox list

$ toolbox -v create
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 1.4.0 is unchanged
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: container is fedora-toolbox-30
toolbox: checking value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: parsing value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: checking if 'podman create' supports --dns=none and --no-hosts
toolbox: 'podman create' supports --dns=none and --no-hosts
toolbox: looking for image localhost/fedora-toolbox:30
toolbox: looking for image registry.fedoraproject.org/f30/fedora-toolbox:30
Image required to create toolbox container.
Download registry.fedoraproject.org/f30/fedora-toolbox:30 (500MB)? [y/N]: y
toolbox: pulling image registry.fedoraproject.org/f30/fedora-toolbox:30
Trying to pull registry.fedoraproject.org/f30/fedora-toolbox:30...Getting image source signatures
Copying blob 4c4fc0337a75 done
Copying blob eb96ef222807 done
Copying config 42cdab313e done
Writing manifest to image destination
Storing signatures
toolbox: base image fedora-toolbox:30 resolved to registry.fedoraproject.org/f30/fedora-toolbox:30
toolbox: checking if container fedora-toolbox-30 already exists
toolbox: trying to create container fedora-toolbox-30
Created container: fedora-toolbox-30
Enter with: toolbox enter

$ toolbox -v enter
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 1.4.0 is unchanged
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: container is fedora-toolbox-30
toolbox: checking if container fedora-toolbox-30 exists
toolbox: trying to start container fedora-toolbox-30
toolbox: looking for /etc/profile.d/toolbox.sh in container fedora-toolbox-30
Error: unable to find user miabbott: no matching entries in passwd file
toolbox: copying /etc/profile.d/toolbox.sh to container fedora-toolbox-30
Error: error copying "/etc/profile.d/toolbox.sh" to "/var/home/miabbott/.local/share/containers/storage/overlay/1bc532e4d664fe242dc96aeebb585f24355b5faab77839aaf6fed0dde543398f/merged/etc/profile.d/toolbox.sh/toolbox.sh": mkdir /var/home/miabbott/.local/share/containers/storage/overlay/1bc532e4d664fe242dc96aeebb585f24355b5faab77839aaf6fed0dde543398f/merged/etc/profile.d/toolbox.sh: not a directory
toolbox: unable to copy /etc/profile.d/toolbox.sh to container fedora-toolbox-30
```

Creating new containers doesn't seem to help

**Comment by debarshiray** [comment] 2019-06-14 20:03
Container names with colons in them are not really supported. The OCI specification disallows colons, but that wasn't enforced by Podman for a while, and that's why Toolbox ended up using them. See #106

We can paper over this for some more time for the sake of backwards compatibility, but I think users would at some point have to re-create their toolbox containers. OCI containers, which is what toolbox containers are, are quite immutable once created. So as they grow older they tend to lose niceties introduced in newer versions of Toolbox.

I think it's time to stick a notice egging users to move away.

It makes me sad to break backwards compatibility, but for a project that's less than a year old, I think we've done reasonably well, and given how new rootless Podman itself is, I think it's fine to have a soft break like this.

**Comment by debarshiray** [comment] 2019-06-14 20:09
@miabbott yours is a different bug, which I managed to predictably reproduce today.

The key lines are:
```
toolbox: looking for /etc/profile.d/toolbox.sh in container fedora-toolbox-30
Error: unable to find user miabbott: no matching entries in passwd file
```

That's caused by a `podman exec --user "$USER" ... sh -c 'mount | grep ...'` invocation failing that's supposed to check if `/etc/profile.d/toolbox.sh` has already been bind mounted into the container. There's something funny going on in Podman, that's not related to having colons in container names. :)

Do you mind opening a separate issue?

**Comment by refi64** [comment] 2019-06-15 03:34
Could some sort of migrate command that just exports and re-imports it with new options be possible?

**Comment by tosmi** [comment] 2019-06-16 20:08
i'm having the same issue as @miabbott with podman 1.4.0. first `toolbox enter` fails with `unable to find user...` and `error copying...`. running enter a second time works. if @miabbott does not mind, i'm going to create a new issue for that.

**Comment by miabbott** [comment] 2019-06-17 13:13
> Do you mind opening a separate issue?

https://github.com/debarshiray/toolbox/issues/196

**Comment by debarshiray** [comment] 2020-01-10 16:19
https://github.com/containers/toolbox/pull/336 added a deprecation notice for old Toolbox containers. There's no `migrate` command, yet, but it's still a somewhat passable excuse to close this issue about invalidly named old Toolbox containers. :)

**Closed by debarshiray** 2020-01-10 16:19 UTC
