### ISSUE TITLE
toolbox enter does not work in su - user workflow

### ISSUE THREAD

**Issue by hholst80** [containers/toolbox#415] opened 2020-04-19 07:40 UTC
```
[om@puff-lan ~]$ su - hh
Password: 
Last login: Sun Apr 19 09:38:57 CEST 2020 on pts/1
[hh@puff-lan ~]$ toolbox --verbose enter
toolbox: running as real user ID 1000
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user hh
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
mkdir: cannot create directory ‘/toolbox’: Operation not permitted
toolbox: unable to migrate containers: runtime directory not created
[hh@puff-lan ~]$ 
```

**Comment by hholst80** [comment] 2020-09-09 16:36
XDG_RUNTIME_DIR being undefined should not break toolbox. Pick a reasonable fallback.
https://serverfault.com/questions/388840/good-default-for-xdg-runtime-dir

**Comment by HarryMichal** [comment] 2020-09-09 19:03
Hi @hholst80.

> XDG_RUNTIME_DIR being undefined should not break toolbox. Pick a reasonable fallback.
> https://serverfault.com/questions/388840/good-default-for-xdg-runtime-dir

Fair enough. We can address that in a future release.

**Comment by debarshiray** [comment] 2020-11-03 21:28
Duplicate of https://github.com/containers/toolbox/issues/267

**Closed by debarshiray** 2020-11-03 21:28 UTC
Labels: bug
