### ISSUE TITLE
Error: Failed to start container

### ISSUE THREAD

**Issue by psiquo** [containers/toolbox#876] opened 2021-09-14 14:03 UTC
**Describe the bug**
Just installed toolbox and created a new container via `toolbox create` but when entering i get `Error: Failed to start container`.

Output with log-level debug:
```
[davide@localhost]~% toolbox enter nrf52840 --log-level debug
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user davide 
DEBU Validating sub-ID file /etc/subuid           
DEBU Validating sub-ID file /etc/subgid           
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Migrating to newer Podman                    
DEBU Toolbox config directory is /home/davide/.config/toolbox 
DEBU Current Podman version is 3.3.1              
DEBU Creating runtime directory /run/user/1000/toolbox 
DEBU Old Podman version is 3.3.1                  
DEBU Migration not needed: Podman version 3.3.1 is unchanged 
DEBU Resolving container and image names          
DEBU Container: 'nrf52840'                        
DEBU Distribution: ''                             
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'nrf52840'                        
DEBU Image: 'fedora-toolbox:34'                   
DEBU Release: '34'                                
DEBU Checking if container nrf52840 exists        
DEBU Inspecting mounts of container nrf52840      
DEBU Starting container nrf52840                  
Error: failed to start container nrf52840
```

**Steps how to reproduce the behaviour**
1. Create container with `toolbox create <name>`
2. Enter newly created container with `toolbox enter <name>`

**Expected behaviour**
I should enter the container.

**Actual behaviour**
The error message `failed to start container` is shown

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.2`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.2-7.fc34.x86_64`

**Output of `podman version`**
```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Mon Aug 30 22:46:36 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-3.3.1-1.fc34.x86_64`

**Info about your OS**
Fedora 34

**Additional context**
Trying to start the container with podman  using `podman start nrf52840` results in the following error:
```
Error: unable to start container "28f9fb3e12c4927c32f700047c3db9529dc973c8acaf98dafbd99cc3d0bc076b": 
make `/home/davide/.local/share/containers/storage/overlay/fc656c78681d2d3e51977006d82a4c54dfa98db28735fbc9549d328222213927/merged` private: 
Permission denied: OCI permission denied
```

**Comment by FlyinPancake** [comment] 2021-09-14 15:23
I am getting the same error as @psiquo :disappointed:

**Comment by prateekmedia** [comment] 2021-09-30 16:12
Same error on fedora silverblue 34. Is there any solution yet? I have to rely on `rpm-ostree`/`flatpak` for installation of the apps for now.

**Comment by prateekmedia** [comment] 2021-10-01 10:57
@FlyinPancake There is no directory in `~/.local/share named overlay`, Is that directory correct?

**Comment by FlyinPancake** [comment] 2021-10-01 11:00
the correct path is this: `~/.local/share/containers/storage/overlay/` 
Wasn't at my computer sorry for the misdirection

**Comment by prateekmedia** [comment] 2021-10-01 13:07
@FlyinPancake Doesn't actually work with Fedora-Silverblue-34, but anyways thanks for your help.

**Comment by FlyinPancake** [comment] 2021-10-01 15:26
@prateekmedia can you start the toolbox container directly with podman? If it fails there just try adding some -vvvv flags and that output will most likely be helpful. 

You can also post your logs here and we can take a look at them.

**Comment by prateekmedia** [comment] 2021-10-01 15:47
@FlyinPancake Sure, here you go!

<details>
<summary><code>$ toolbox enter coding -vvv</code></summary>

```
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user prateeksu 
DEBU Validating sub-ID file /etc/subuid           
DEBU Validating sub-ID file /etc/subgid           
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Migrating to newer Podman                    
DEBU Toolbox config directory is /var/home/prateeksu/.config/toolbox 
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called version.PersistentPreRunE(podman --log-level debug version --format json) 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/home/prateeksu/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/home/prateeksu/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /var/home/prateeksu/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /var/home/prateeksu/.local/share/containers/storage/volumes 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is not being used 
DEBU[0000] cached value indicated that native-diff is usable 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Found CNI network podman (type=bridge) at /var/home/prateeksu/.config/cni/net.d/87-podman.conflist 
DEBU[0000] Default CNI network name podman is unchangeable 
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Called version.PersistentPostRunE(podman --log-level debug version --format json) 
DEBU Current Podman version is 3.3.1              
DEBU Creating runtime directory /run/user/1000/toolbox 
DEBU Old Podman version is 3.3.1                  
DEBU Migration not needed: Podman version 3.3.1 is unchanged 
DEBU Resolving container and image names          
DEBU Container: 'coding'                          
DEBU Distribution: ''                             
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'coding'                          
DEBU Image: 'fedora-toolbox:34'                   
DEBU Release: '34'                                
DEBU Checking if container coding exists          
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called exists.PersistentPreRunE(podman --log-level debug container exists coding) 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/home/prateeksu/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/home/prateeksu/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /var/home/prateeksu/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /var/home/prateeksu/.local/share/containers/storage/volumes 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is not being used 
DEBU[0000] cached value indicated that native-diff is usable 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Found CNI network podman (type=bridge) at /var/home/prateeksu/.config/cni/net.d/87-podman.conflist 
DEBU[0000] Default CNI network name podman is unchangeable 
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Called exists.PersistentPostRunE(podman --log-level debug container exists coding) 
DEBU Inspecting mounts of container coding        
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called inspect.PersistentPreRunE(podman --log-level debug inspect --format json --type container coding) 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/home/prateeksu/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/home/prateeksu/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /var/home/prateeksu/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /var/home/prateeksu/.local/share/containers/storage/volumes 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is not being used 
DEBU[0000] cached value indicated that native-diff is usable 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Found CNI network podman (type=bridge) at /var/home/prateeksu/.config/cni/net.d/87-podman.conflist 
DEBU[0000] Default CNI network name podman is unchangeable 
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Called inspect.PersistentPostRunE(podman --log-level debug inspect --format json --type container coding) 
DEBU Starting container coding                    
Error: failed to start container coding
```

</details>

I think the problem is with below two lines:
```
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
```

**Comment by prateekmedia** [comment] 2021-10-01 16:05
Also Note that I am running toolbox without sudo.

**Comment by debarshiray** [comment] 2021-11-15 21:50
Closing.

Thanks for playing with Toolbox! :)

**Closed by debarshiray** 2021-11-15 21:50 UTC
Labels: 1. Bug
