### ISSUE TITLE
Choose what parts of host filesystem should be writeable/overlaid

### ISSUE THREAD

**Issue by carlpett** [containers/toolbox#605] opened 2020-10-29 16:47 UTC
**Is your feature request related to a problem? Please describe.**
_(Very new toolkit user, let me know if I misunderstand something)_
Currently, the toolbox appears to pass a fully rw-mounted /home/myuser into the container. This has the drawback that the tools I was hoping to isolate within the toolbox still writes stuff all over my host environment. 

**Describe the solution you'd like**
Ideally, the home directory is read-only or has some type of overlay (not sure about the feasibility of this) for writes.
Additionally, I'd be able to specify directories (probably subdirectories of home) that should be writeable and reflect to the host.

**Describe alternatives you've considered**
None that seem to work :)

**Additional context**
N/A

**Comment by debarshiray** [comment] 2020-12-18 23:14
Duplicate of https://github.com/containers/toolbox/issues/183

**Closed by debarshiray** 2020-12-18 23:14 UTC
Labels: 1. Feature request
