### ISSUE TITLE
podman support inside toolbox containers via podman-remote

### ISSUE THREAD

**Issue by vorburger** [containers/toolbox#1072] opened 2022-07-03 21:18 UTC
#145 related new issue specifically (and only) re. `podman` via `podman-remote`.

The goal would be that `podman ...` would "just work" in a `toolbox enter` (but redirected to the host, obviously).

Basically, based on https://github.com/containers/podman/blob/main/docs/tutorials/remote_client.md, or [this blog post](https://www.redhat.com/sysadmin/podman-inside-container) and my [TL;DR](https://github.com/vorburger/vorburger-dotfiles-bin-etc/blob/master/docs/podman.md#podman-in-podman), one needs this on their Fedora host:

    systemctl enable --now --user podman.socket

and then launch a container (not toolbox, this is just to illustrate & document the approach):

    podman run -it --rm -v /run/user/$UID/podman:/run/user/0/podman --security-opt label=disable fedora
    dnf install -y podman-remote
    podman-remote info

For this to "just work" out of the box inside any new `toolbox`, perhaps only the following is still needed (as far as I learnt so far):

1. Include the `podman-remote` package in toolbox image (easy, of course)
1. Provide `podman` (and perhaps `docker` as well while we're at it, for convenience) redirects to `podman-remote`, ideally with shell completions. Shell aliases may not be visible in scripts depending on how & where they are defined, so perhaps a simple `/usr/bin/podman` containing `#!/usr/bin/sh` and `exec /usr/bin/podman-remote "$@"` is the way to go, just like the `podman-docker` package does - but without actually installing it; that's not a good idea because it depends on and would pull all of `podman` into the toolbox container, which you wouldn't want.

I got something like this working in my personal dotfiles container (not using toolbox, yet), see https://github.com/vorburger/vorburger-dotfiles-bin-etc/commit/d0d9ee0cc89d60e2352dc5f2d9bda7110a7fb5dc and https://github.com/vorburger/vorburger-dotfiles-bin-etc/commit/5057c921712b00cac8d02151f58fa001ebc5b2ba. (But `toolbox` appears to already mount `/run/user/$UID/podman/podman.socket` (with the correct file permission), and not require the `CONTAINER_HOST` environment variable to be set. Also the `--security-opt label=disable` is either already done by toolbox, or it's solved differently and not required.)

Would toolbox would want to do something like that, or would this project prefer not integrating `podman-remote` for any reason and going another way?

**Comment by vorburger** [comment] 2022-07-03 21:21
> perhaps a simple `/usr/bin/podman` containing `#!/usr/bin/sh` and `exec /usr/bin/podman-remote "$@"`

Or even just a symbolic link?

**Comment by debarshiray** [comment] 2022-08-05 23:05
Let's keep the discussion in one place at https://github.com/containers/toolbox/issues/145

Having separate issues to discuss different approaches to solve a problem will explode the number of open issues to a point where they will no longer be representative of our current to-do list.

**Comment by debarshiray** [comment] 2022-08-05 23:05
Duplicate of https://github.com/containers/toolbox/issues/145

**Closed by debarshiray** 2022-08-05 23:05 UTC
Labels: 1. Feature request
