### ISSUE TITLE
Writing to `/var/tmp`

### ISSUE THREAD

**Issue by anthr76** [containers/toolbox#741] opened 2021-03-23 12:06 UTC
Hello,

I'm trying to build packages with the CLI tool `osc` from the Open Build Service by openSUSE. By default they write a package cache to `/var/tmp` as `nobody` though no matter what I'm having a hard time writing to `/var/tmp` . I set a manual override to write to the dir as 'caller' which is my UID/GID. Still nothing

```sh
☁  tmp  pwd
/var/tmp
☁  tmp  touch test
touch: setting times of 'test': No such file or directory
```

It seems no magic sauce with toolbox is happening with `/var/tmp` so the directory should just live just fine within the container. Can anyone explain this pattern and the best workaround?

For what it's worth I'm opting to build in kvm instead of a chroot as I've heard success in the openSUSE implementation of toolbox (running as root). 

I'm using Fedora 33, and my own custom toolbox image. Both reproduce identically.

**Comment by debarshiray** [comment] 2021-11-16 00:39
Umm... I don't understand what the problem is.  `/var/tmp` is still world writable inside a Toolbox container.

**Comment by debarshiray** [comment] 2023-10-05 19:41
I see that you thought that this is related to https://github.com/containers/toolbox/issues/761 which turned out to be duplicate of https://github.com/rpm-software-management/mock/issues/715 and has since been fixed in Mock.  Did that fix it for you?

**Comment by debarshiray** [comment] 2023-10-05 19:42
> For what it's worth I'm opting to build in kvm instead of a chroot as I've heard success in the openSUSE implementation of toolbox (running as root).

I didn't understand what you meant here.  Are you using a different tool than this project?

**Comment by debarshiray** [comment] 2023-10-05 19:44
I am tentatively closing this issue because there hasn't been any updates for the past two years.  However, please feel free to leave a comment with the answers to the above questions, if this is still causing problems for you, and we can re-open.

Either way, thanks for stopping by!

**Closed by debarshiray** 2023-10-05 19:44 UTC
Labels: 1. Bug
