### ISSUE TITLE
unable to find user root: no matching entries in passwd file

### ISSUE THREAD

**Issue by stove-panini** [containers/toolbox#355] opened 2020-01-06 16:43 UTC
After a reboot on SIlverblue 31, I noticed my toolbox had stopped working. When this happens, I typically remove and recreate the container, but that doesn't seem to be a suitable fix this time around. I'm running Podman 1.6.2.

```
$ toolbox -v enter
toolbox: running as real user ID 1000
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user stephen
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: running on a cgroups v2 host
toolbox: current Podman version is 1.6.2
toolbox: migration not needed: Podman version 1.6.2 is unchanged
toolbox: Fedora generational core is f31
toolbox: base image is fedora-toolbox:31
toolbox: container is fedora-toolbox-31
toolbox: checking if container fedora-toolbox-31 exists
toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
toolbox: starting container fedora-toolbox-31
toolbox: /etc/profile.d/toolbox.sh already mounted in container fedora-toolbox-31
toolbox: inspecting entry point of container fedora-toolbox-31
toolbox: entry point of container fedora-toolbox-31 is toolbox
toolbox: waiting for container fedora-toolbox-31 to finish initializing
Error: unable to find user root: no matching entries in passwd file
toolbox: failed to create /run/.toolboxenv in container fedora-toolbox-31
```

Removing the container via toolbox also presents an issue:
```
$ toolbox -v rm -f fedora-toolbox-31
toolbox: running as real user ID 1000
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user stephen
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: running on a cgroups v2 host
toolbox: current Podman version is 1.6.2
toolbox: migration not needed: Podman version 1.6.2 is unchanged
Error: error removing container 7eaf90a951538174d732497bbc879d854302fabba0dd2366557fad2bcc4b30cf root filesystem: unlinkat /var/home/stephen/.local/share/containers/storage/overlay/8da415692461673bb0752d06f1b1838f715b365da73efee67a1af0cc7bcd5093/merged: device or resource busy
toolbox: failed to remove container fedora-toolbox-31
```
Which is strange because it actually _does_ remove the container:
```
$ podman container list --all
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```

The volume is removed as well, but entries are still leftover (with root ownership) in ~/.local/share/containers/storage

Removing the image has a similar issue:
```
$ toolbox -v rmi -f registry.fedoraproject.org/f31/fedora-toolbox:31 
toolbox: running as real user ID 1000
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user stephen
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: running on a cgroups v2 host
toolbox: current Podman version is 1.6.2
toolbox: migration not needed: Podman version 1.6.2 is unchanged
Error: error removing containers [7eaf90a951538174d732497bbc879d854302fabba0dd2366557fad2bcc4b30cf] for image "a198bc8c3cda783856295d4d4859668217afc4ffc6f79a171c896f1b13e5ed21": could not remove container "7eaf90a951538174d732497bbc879d854302fabba0dd2366557fad2bcc4b30cf": unlinkat /var/home/stephen/.local/share/containers/storage/overlay/8da415692461673bb0752d06f1b1838f715b365da73efee67a1af0cc7bcd5093/merged: device or resource busy
toolbox: failed to remove image registry.fedoraproject.org/f31/fedora-toolbox:31
```

I can `sudo rm -rf ~/.local/share/containers`, clear out everything using `podman`, but the "unable to find user root" issue persists when I attempt to create a fresh toolbox.

**Comment by zapateo** [comment] 2020-01-07 14:31
I have a similar issue on Fedora 31 Workstation, with toolbox 0.0.17 and podman 1.6.2.

**Comment by HarryMichal** [comment] 2020-03-13 14:46
Hi @stove-panini and @zapateo! I apologize for not responding to this issue much earlier. Is the issue still present? Or did it go away after some update?

@stove-panini  You said the issue happened after rebooting. Did you upgrade your system prior to the update? Maybe some minor change to Podman/crun/runc/fuse-overlayfs could cause that problem.

**Comment by zapateo** [comment] 2020-03-13 15:41
> Hi @stove-panini and @zapateo! I apologize for not responding to this issue much earlier. Is the issue still present? Or did it go away after some update?
> 
> @stove-panini You said the issue happened after rebooting. Did you upgrade your system prior to the update? Maybe some minor change to Podman/crun/runc/fuse-overlayfs could cause that problem.

@HarryMichal don't worry! The issue seems to be gone, I can't reproduce it any more :smile:  (toolbox updated from `0.0.17` to `0.0.18`, podman updated from `1.6.2` to `1.8.0`).

**Comment by HarryMichal** [comment] 2020-03-13 15:56
Good to hear that. So I suppose it's ok to close this issue.

**Closed by HarryMichal** 2020-03-13 15:56 UTC
