### ISSUE TITLE
/etc/group not replicated in Toolbox

### ISSUE THREAD

**Issue by bkhl** [containers/toolbox#560] opened 2020-09-20 09:49 UTC
**Describe the bug**

For new toolboxes, the host `/etc/group` file is not mirrored in the toolbox, resulting in:

```
bkhl@foxglove:~$ toolbox create 
Created container: fedora-toolbox-32
Enter with: toolbox enter
bkhl@foxglove:~$ toolbox enter
/usr/bin/id: cannot find name for group ID 1000
bkhl@toolbox:~$ 
```

Also of course my files all appear owned by the group `1000` rather than the group name.

**Steps how to reproduce the behaviour**

1. Delete any old toolbox container with the same name created before upgrading to Toolbox 0.0.95
2. Create a new toolbox container
3. Enter the new toolbox container
4. See the error: `/usr/bin/id: cannot find name for group ID 1000`

**Expected behaviour**

The user group entries from the host system to be replicated in the container.

**Actual behaviour**

My user group is not included in the `/etc/group` in the container.

For containers created a while ago, I don't see this issue. I can't say at exactly what update of Toolbox/Podman the issue started occurring, as I haven't created any new Toolbox containers for a while.

**Output of `toolbox --version` (v0.0.90+)**

`toolbox version 0.0.95`

**Toolbox package info (`rpm -q toolbox`)**

toolbox-0.0.95-1.fc32.x86_64

**Output of `podman version`**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.14.6
Built:        Wed Sep  2 02:26:51 2020
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**

`podman-2.0.6-1.fc32.x86_64`

**Info about your OS**

Fedora Silverblue 32

**Comment by mvalahtv** [comment] 2020-09-21 11:41
Same here. 
```
[mvala@localhost ~]$ toolbox enter fc32
/usr/bin/id: cannot find name for group ID 1000
```

**Comment by HarryMichal** [comment] 2020-09-22 13:51
Hi @bkhl! This is a duplicate of https://github.com/containers/toolbox/issues/549.

**Closed by HarryMichal** 2020-09-22 13:51 UTC
Labels: bug
