### ISSUE TITLE
"seamless" / "tight" integration are not defined

### ISSUE THREAD

**Issue by markstos** [containers/toolbox#353] opened 2019-12-30 15:25 UTC
According to the README, one of the key documented features of Toolbox is that it is _seamlessly integrated_ with the host while one of "Non-Goals / Anti Use Cases" are cases when the container is not _tightly integrated_ with the host.

So understanding the definition of  "seamless", "tight" integration is key to knowing whether Toolbox is a good fit.

Toolbox should document exactly what it does to create a seamless and tight integration. Also, consider using the word "seamless" or "tight" throughout instead of both. 

The documentation is doubly important because while containers are associated with improved security, Toolbox focuses on convenience at the expense of security and these trade-offs should be clear to the user so they can make an informed decision if Toolbox is right for their use case.   Toolbox shares private SSH credentials with the containers. Toolbox plans to share environment variables with the container (#29), and Toolbox also shares media and other mounted devices with the container which may contain yet more sensitive information. 

It seems to me that Toolbox focuses on providing a seamless experience for _trusted_ containers, but this not currently clear from the docs.

**Comment by abitrolly** [comment] 2020-11-01 06:57
I was surprised by this too in #427.

**Comment by debarshiray** [comment] 2024-08-02 11:23
Duplicate of https://github.com/containers/toolbox/issues/1020

**Comment by debarshiray** [comment] 2024-08-02 11:32
Note that we are very careful about the use of the word *container* in the context of the Toolbx project.  This GitHub project describes it as, either:
*Tool for interactive command line environments on Linux *

... or:
*Toolbx is a tool for Linux, which allows the use of interactive command line environments for development and troubleshooting the host operating system, without having to install software on the host.*

... and ends the paragraph just by stating:
*It is built on top of Podman and other standard container technologies from OCI.*

It doesn't mention words like *privilege*, *security*, etc..

Finally, the idea that containers are about security is an oversimplification that a lot of people have built up in their heads.  Containers may or may not provide more security, depending on a lot of details.

Anyway, at the end of the day, the `README.md` and the website are premium digital real estate.  We try our best to introduce the problem statement and how Toolbx solves it.  Every reader is different, but we hope that people will finally get it.

**Closed** 2024-08-02 11:33 UTC
Labels: 2. Documentation

**Comment by abitrolly** [comment] 2024-08-03 16:40
@debarshiray I would still replace phrase "seamless access" with "full access" to avoid shady marketing language.
