### ISSUE TITLE
Locale not working for GUI app launched in toolbox

### ISSUE THREAD

**Issue by seb62** [containers/toolbox#967] opened 2021-12-21 17:34 UTC
**Describe the bug**
GUI app launched in a toolbox don't use the locale set in the toolbox.

**Steps how to reproduce the behaviour**
1. installed glibc-langpack-fr in the toolbox
2. exported LC_ALL as fr_FR.UTF-8
3. installed GUI app in the toolbox (vlc, grisbi)
4. launched vlc or grisbi

**Expected behaviour**
Menus of the GUI app in french.

**Actual behaviour**
Menus of the GUI app in english.

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.2

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99.2^3.git075b9a8d2779-4.fc35.x86_64

**Output of `podman version`**
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 22:45:07 2021
OS/Arch:      linux/amd64

**Podman package info (`rpm -q podman`)**
podman-3.4.4-1.fc35.x86_64

**Info about your OS**
Fedora Silverblue 35

**Comment by JayDoubleu** [comment] 2021-12-21 23:51
I'm also able to replicate this: 

Running below on host shows FR UI.
```
export LANGUAGE=fr_FR
$ vlc
```
Running the same from toolbox still shows UI in English. 
Running other programs like nautilus have the same result.

**Comment by HarryMichal** [comment] 2022-01-07 07:33
I suspect this is a duplicate of https://github.com/containers/toolbox/issues/60. If not, we'll reopen this.

**Closed by HarryMichal** 2022-01-07 07:33 UTC
Labels: 1. Bug
