### ISSUE TITLE
Can we rename the VERSION env var?

### ISSUE THREAD

**Issue by Qwertie-** [containers/toolbox#708] opened 2021-02-24 00:07 UTC
**Describe the bug**
Inside the fedora toolbox containers, the environment var [VERSION is set](https://github.com/containers/toolbox/blob/f5bbe356ad52576f6429f9864840a732d068cbed/images/fedora/f34/Dockerfile#L3). This is a kind of generic name and other software is using it. Specifically I have found that the rails migration tool breaks until you run `unset VERSION` or it will give the error `No migration with version number 33.`. 

Can we rename this to something more scoped? Like FEDORA_VERSION or TOOLBOX_VERSION? That would avoid any potential clash with existing software.

**Steps how to reproduce the behaviour**
1. run toolbox create/enter
2. see the env var VERSION exists

**Expected behaviour**
The env var is named something less generic to avoid issues with other software

**Screenshots**

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99-1.fc33.x86_64

**Output of `podman version`**
```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Wed Dec  9 01:07:50 2020
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-2.2.1-1.fc33.x86_64`

**Info about your OS**
Fedora Silverblue 33

**Comment by mildred** [comment] 2021-06-07 13:08
See #188 for background about this issue.

> Closing.
> 
> We can revisit this once the Fedora build system no longer needs `NAME` and `VERSION`.

I'd suggest to keep this issue around if it's not yet possible to remove those variables, as not to forget that we can clean it up.

**Comment by debarshiray** [comment] 2021-09-17 11:07
Duplicate of https://github.com/containers/toolbox/issues/188

**Comment by debarshiray** [comment] 2021-09-17 11:08
We can re-open https://github.com/containers/toolbox/issues/188 if you want to. It would be good to keep the discussion consolidated on one issue, instead of having it get scattered across various issues and pull requests.

**Closed by debarshiray** 2021-09-17 11:08 UTC
Labels: 1. Bug, 2. Images, 2. Container Realm
