### ISSUE TITLE
Allow to customize the groups the user will be part of when creating a toolbox

### ISSUE THREAD

**Issue by mildred** [containers/toolbox#785] opened 2021-06-07 14:07 UTC
**Is your feature request related to a problem? Please describe.**

When creating a toolbox Dockerfile for a specific project, installing rvm inside, the toolbox user needs to be in the rvm group. But when building the container, the toolbox is not created yet and the user does not exists. I cannot run `usermod` to ass it to the `rvm` group. 

**Describe the solution you'd like**

When the label `com.github.containers.toolbox.groups` is set on the toolbox image, the toolbox user is created using the groups specified in that label (separated by commas, like `usermod`)

**Describe alternatives you've considered**

Running usermod on first login by having it in /etc/profile or similar. But I would run in the following issue: https://github.com/containers/toolbox/issues/632

edit: another alternative would be to have a hook script in the toolbox that would be invoked by `toolbox init-container` upon toolbox creation. it would have access to the user name, uid, and other related specifics and would be able to customize the toolbox depending on that.

**Comment by mildred** [comment] 2021-06-07 14:10
This can be hooked here:

https://github.com/containers/toolbox/blob/e935ed893d5b72ac9f08987bc2c7ede9f7d506cc/src/cmd/initContainer.go#L379

https://github.com/containers/toolbox/blob/e935ed893d5b72ac9f08987bc2c7ede9f7d506cc/src/cmd/initContainer.go#L398

**Comment by debarshiray** [comment] 2023-09-28 07:42
Duplicate of https://github.com/containers/toolbox/issues/1348

**Closed by debarshiray** 2023-09-28 07:43 UTC
Labels: 1. Feature request
