### ISSUE TITLE
No DNS from within toolbox

### ISSUE THREAD

**Issue by monreal** [containers/toolbox#290] opened 2019-10-09 04:41 UTC
I run toolbox on two systems. First one is running Fedora Silverblue 31 inside gnome-boxes on a system running Fedora 31, second one is running plain Fedora 31. 

On the first system, everything works fine. On the second one I can get into the toolbox and it seems to work fine but there is no DNS resolution:

> [micmon ~]$ toolbox -v enter
> toolbox: running as real user ID 1000
> toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
> toolbox: checking if /etc/subgid and /etc/subuid have entries for user micmon
> toolbox: TOOLBOX_PATH is /usr/bin/toolbox
> toolbox: migration not needed: 1.6.1 is unchanged
> toolbox: Fedora generational core is f31
> toolbox: base image is fedora-toolbox:31
> toolbox: container is fedora-toolbox-31
> toolbox: checking if container fedora-toolbox-31 exists
> toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
> toolbox: starting container fedora-toolbox-31
> toolbox: /etc/profile.d/toolbox.sh already mounted in container fedora-toolbox-31
> toolbox: creating list of environment variables to forward
> toolbox: COLORTERM=truecolor
> toolbox: COLUMNS is unset
> toolbox: DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> toolbox: DBUS_SYSTEM_BUS_ADDRESS is unset
> toolbox: DESKTOP_SESSION=gnome
> toolbox: DISPLAY=:0
> toolbox: LANG=en_US.UTF-8
> toolbox: LINES is unset
> toolbox: SHELL=/bin/bash
> toolbox: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
> toolbox: TERM=xterm-256color
> toolbox: TOOLBOX_PATH is unset
> toolbox: VTE_VERSION=5800
> toolbox: WAYLAND_DISPLAY=wayland-0
> toolbox: XDG_CURRENT_DESKTOP=GNOME
> toolbox: XDG_DATA_DIRS=/home/micmon/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/
> toolbox: XDG_MENU_PREFIX=gnome-
> toolbox: XDG_RUNTIME_DIR=/run/user/1000
> toolbox: XDG_SEAT is unset
> toolbox: XDG_SESSION_DESKTOP=gnome
> toolbox: XDG_SESSION_ID is unset
> toolbox: XDG_SESSION_TYPE=wayland
> toolbox: XDG_VTNR is unset
> toolbox: created options for environment variables to forward
> --env=COLORTERM=truecolor --env=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus --env=DESKTOP_SESSION=gnome --env=DISPLAY=:0 --env=LANG=en_US.UTF-8 --env=SHELL=/bin/bash --env=SSH_AUTH_SOCK=/run/user/1000/keyring/ssh --env=TERM=xterm-256color --env=VTE_VERSION=5800 --env=WAYLAND_DISPLAY=wayland-0 --env=XDG_CURRENT_DESKTOP=GNOME --env=XDG_DATA_DIRS=/home/micmon/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/ --env=XDG_MENU_PREFIX=gnome- --env=XDG_RUNTIME_DIR=/run/user/1000 --env=XDG_SESSION_DESKTOP=gnome --env=XDG_SESSION_TYPE=wayland --env=COLUMNS=156 --env=LINES=24
> toolbox: looking for /bin/bash in container fedora-toolbox-31
> toolbox: running in container fedora-toolbox-31:
> toolbox: /bin/bash
> toolbox: -l
> [micmon ~]$ ping 8.8.8.8
> PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
> 64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=8.52 ms
> 64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=8.79 ms
> ^C
> --- 8.8.8.8 ping statistics ---
> 2 packets transmitted, 2 received, 0% packet loss, time 1002ms
> rtt min/avg/max/mdev = 8.517/8.653/8.789/0.136 ms
> [micmon ~]$ ping google.com
> ping: google.com: Name or service not known

**Comment by monreal** [comment] 2019-10-09 04:43
I also noticed one other detail: on the first system, the terminal prompt is modified (adds the purple diamond shape) but on the second system it does not. The terminal title is changed on both systems, though.

**Comment by debarshiray** [comment] 2019-10-14 17:47
What's the situation of `/etc/resolv.conf` inside the toolbox container without working DNS?
```
$ ls -l /etc/resolv.conf
```

**Comment by debarshiray** [comment] 2019-10-14 17:50
> I also noticed one other detail: on the first system, the terminal prompt is
> modified (adds the purple diamond shape) but on the second system it does
> not.

The shell prompt (ie., `PS1`) is changed through `/etc/profile.d/toolbox.sh`. Do you have that file?

Is that file getting sourced by your shell? Try inserting an `echo Hello world` to the top of the file and see if it's getting printed when you open a new terminal or spawn a new shell. Either way, we should probably be using a different issue for this.

**Comment by debarshiray** [comment] 2019-10-15 17:46
I see; and you don't have `/run/host/etc` inside the toolbox container?

I am puzzled how that could be. I know that there was a bug where containers created by Toolbox < 0.0.11 could have dangling symbolic links for `/etc/localtime` and `/etc/timezone` when entered with Toolbox 0.0.11. However that was [fixed](https://github.com/debarshiray/toolbox/pull/207) in 0.0.12.

However, `/etc/resolv.conf` should be solid.

**Comment by monreal** [comment] 2019-10-15 17:48
> The shell prompt (ie., `PS1`) is changed through `/etc/profile.d/toolbox.sh`. Do you have that file?

Yes, but I noticed I had some PS1 customization for git folders using /usr/share/git-core/contrib/completion/git-prompt.sh - any idea how to get both?

**Comment by monreal** [comment] 2019-10-15 17:52
> I see; and you don't have `/run/host/etc` inside the toolbox container?

I do have that. Broken links are extlinux.conf, favicon.png, grub2-ei.cfg, grub2.cfg, mtab and resolv.conf, which points to /var/run/NetworkManager/resolv.conf and /var/run/NetworkManager does not exist

**Comment by debarshiray** [comment] 2019-10-15 18:16
If `/etc/resolv.conf` on your host points at `/run/NetworkManager/resolv.conf` on a Fedora system, then it means that the user overrode the default handling of `resolv.conf` by creating the symbolic link him/herself. Look at `rc-manager` in the `NetworkManager.conf(5)` manual.

Let's call this a duplicate of https://github.com/containers/toolbox/issues/187

Do you really want it to be a symbolic link? If not maybe just restore the default behaviour for the time being?

I assume that the other broken links that you mentioned are just the ones in `/run/host/etc` inside the container, right? In that case we can ignore them.

**Comment by debarshiray** [comment] 2019-10-15 18:16
Duplicate of https://github.com/containers/toolbox/issues/187

**Closed** 2019-10-15 18:16 UTC
Labels: bug

**Comment by debarshiray** [comment] 2019-10-15 18:21
> I had some PS1 customization for git folders using
> /usr/share/git-core/contrib/completion/git-prompt.sh - any idea how to get both?

We have discussed making the prompt smarter with respect to Git repositories out-of-the-box, but nothing has happened yet.

Anyway, if you look at `/etc/profile.d/toolbox.sh`, you will notice that placing the hexagon is pretty easy - look for `/run/.toolboxenv` to detect if you are inside a toolbox container and then you do your toolbox specific customization. You could just replicate that in your start-up script.

**Comment by monreal** [comment] 2019-10-15 19:24
Thanks for the pointers. I am not aware oft any changes done to the NM config but the system in question has not seen a fresh installation in years, so maybe I forgot or maybe the default changed at some point... I will have a look into this later. Thanks again!

**Comment by ptomato** [comment] 2019-10-24 18:35
See https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/269

**Comment by debarshiray** [comment] 2019-10-29 12:31
Thanks for pursuing this, @ptomato

**Comment by ptomato** [comment] 2019-10-29 23:26
For completeness, `sudo rm /etc/resolv.conf` and a reboot fixed the issue for me.
