### ISSUE TITLE
Add export command

### ISSUE THREAD

**Issue by yajo** [containers/toolbox#1000] opened 2022-01-25 08:25 UTC
**Is your feature request related to a problem? Please describe.**
Writing .desktop files is not nice. Also understanding the XDG paths related is a whole new avenue of knowledge, and the sandboxing quirks and desktop integration of apps...

**Describe the solution you'd like**
Distrobox has the [`distrobox-export`](https://github.com/89luca89/distrobox/blob/main/distrobox-export) subcommand, that exports/destroys desktop apps and systemd user services with simple commands.

**Describe alternatives you've considered**
Of course, handwiring all that stuff.

**Comment by geekgonecrazy** [comment] 2023-01-08 07:12
Seems like in distrobox it was pretty straight forward - https://github.com/89luca89/distrobox/blob/main/distrobox-export

Is there something specific that needs to be taken into consideration when rewriting this functionality to toolbox?  I know the code base here is written in go.  But not sure if there is some intention to implement this a specific way?

**Comment by debarshiray** [comment] 2023-01-18 13:46
The part about handling desktop files was already [covered](https://github.com/containers/toolbox/issues/417#issuecomment-969346719) in https://github.com/containers/toolbox/issues/417

**Comment by debarshiray** [comment] 2023-01-18 13:47
Getting `systemctl(1)` to work sounds like a worthy goal, and we have https://github.com/containers/toolbox/issues/176 for that.

**Comment by debarshiray** [comment] 2023-01-18 13:48
Duplicate of https://github.com/containers/toolbox/issues/417

**Comment by debarshiray** [comment] 2023-01-18 13:48
Duplicate of https://github.com/containers/toolbox/issues/176

**Closed** 2023-01-18 13:48 UTC
Labels: 1. Feature request, Project Pickle 🥒, 2. Host Realm
