### ISSUE TITLE
wishlist: expose the container's name in the environment

### ISSUE THREAD

**Issue by gkiagia** [containers/toolbox#490] opened 2020-07-06 16:21 UTC
It would be nice to be able to access the container's name (the one from `toolbox create -c <name>`) from the environment within the container. It's useful to display it in a custom shell prompt, so that it's easy to tell in which container you are working in... 

The distribution's name / version is not enough. I tend to create multiple toolbox containers based on the same image, installing different packages in each, while working on different projects.

**Comment by HarryMichal** [comment] 2020-07-07 11:25
Hi @gkiagia! This is a duplicate of https://github.com/containers/toolbox/issues/98.

**Closed by HarryMichal** 2020-07-07 11:25 UTC
Labels: duplicate
