### ISSUE TITLE
HOSTNAME is not set on f33 image

### ISSUE THREAD

**Issue by A6GibKm** [containers/toolbox#558] opened 2020-09-19 11:15 UTC
## OS
Fedora Silverblue 33
toolbox 0.0.95

## Issue

The enviromental variable `HOSTNAME` is not being set on toolbox, `echo $HOSTNAME` returns only a new line. This does not correspond to the behaviour in previous images.

Related issue: https://github.com/fedora-silverblue/issue-tracker/issues/84

**Comment by HarryMichal** [comment] 2020-09-22 17:42
Hi @A6GibKm! I quickly tried to reproduce this but could not.

My steps were:

- `toolbox create` (I run Fedora Silverblue 33 -> the `f33/fedora-toolbox` image was used)
- `toolbox enter`
- `echo $HOSTNAME`

The output of the last command was `toolbox` as currently expected. Is there something specific to your use-case I missed? What shell do you run?

**Comment by A6GibKm** [comment] 2020-09-22 18:49
Not that I know of, I removed my `.bashrc` for testing purposes and enter a newly created toolbox. Also,

```
$ podman images
REPOSITORY                                     TAG     IMAGE ID      CREATED       SIZE
registry.fedoraproject.org/f33/fedora-toolbox  33      95dc9d4b0f27  2 weeks ago   327 MB
registry.fedoraproject.org/f32/fedora-toolbox  32      f7cf4b593fc1  6 months ago  360 MB
docker.io/library/fedora                       32      15fd256292f6  7 months ago  206 MB
```

**Comment by garrett** [comment] 2020-09-30 12:16
I don't see it here on my workstation, but I do see the missing `$HOSTNAME` in my test VM, even after a `podman system reset`.

```
$ podman images
REPOSITORY                                     TAG     IMAGE ID      CREATED      SIZE
registry.fedoraproject.org/f33/fedora-toolbox  33      95dc9d4b0f27  3 weeks ago  327 MB
```

The VM is completely vanilla (except for overlaying gitk for testing other toolbox/podman related issues), upgraded to the latest F33 beta Silverblue compose.

```
● ostree://fedora:fedora/33/x86_64/silverblue
                   Version: 33.20200929.n.0 (2020-09-29T08:06:48Z)
                BaseCommit: 215677333515cc11110cf016a4cbb021eb929b552f5ed25bb6d403c9f19c1a4a
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
           LayeredPackages: fedora-workstation-repositories gitk
```

**Comment by A6GibKm** [comment] 2020-10-01 16:48
I also upgraded my second machine to f33, did a `podman system reset` and still the variable `HOSTNAME` is not set.

**Comment by dziq** [comment] 2020-10-28 15:19
I have exact the same issue. Rebased to f33, remove all toolboxes, create new one (f33) but `echo $HOSTNAME` outputs nothing.

**Comment by A6GibKm** [comment] 2020-10-28 15:57
at least it is easy to patch via 
```sh
if [ -f /README.md ]; then
    export HOSTNAME=toolbox
fi
```

**Comment by dziq** [comment] 2020-10-28 16:50
What is more hostid on f33 is 00000000 on f32 I have same numer as on host (a8c0a300) but should be the same. This issue is quite annoying while using mc (midnight commander).

**Comment by debarshiray** [comment] 2022-10-14 01:38
Are you all using Bash?  As per the `bash(1)` manual, `HOSTNAME` is *automatically set to the name of the current host*.

**Comment by debarshiray** [comment] 2022-11-18 07:24
On Fedora, `/etc/profile` contains:
```
HOSTNAME=$(/usr/bin/hostnamectl --transient 2>/dev/null) || \
HOSTNAME=$(/usr/bin/hostname 2>/dev/null) || \
HOSTNAME=$(/usr/bin/uname -n)
```

Then later, it's read in `/etc/bashrc`.  Are those getting set for you?

Note that `/etc/profile` is only read for login shells.  So you got to run it as `bash --login`, which is also what Toolbx does.

**Comment by debarshiray** [comment] 2024-01-18 22:01
Given the timing of this issue and the comments that are able to reproduce it, I am inclined to believe that this was some passing problem during the Fedora 33 development cycle (Fedora 33 was [released](https://fedoramagazine.org/announcing-fedora-33/) in late October 2020) that ended up getting fixed one way or another.

Regardless, just to be sure, I have [added](https://github.com/containers/toolbox/pull/1436) some tests to ensure that `HOSTNAME` is always set inside Toolbx containers.

**Comment by debarshiray** [comment] 2024-01-18 22:02
I am going to close this now.  As always, thanks for the testing.

**Closed by debarshiray** 2024-01-18 22:02 UTC
Labels: 1. Bug

**Comment by debarshiray** [comment] 2024-01-19 19:04
> Given the timing of this issue and the comments that are able to reproduce it, I am inclined to believe that this was some passing problem during the Fedora 33 development cycle (Fedora 33 was [released](https://fedoramagazine.org/announcing-fedora-33/) in late October 2020) that ended up getting fixed one way or another.

This could have been a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1938223
