### ISSUE TITLE
Periodic CI randomly fails on fedora-31 for `Echo 'Hello World' inside of the 'running' container`

### ISSUE THREAD

**Issue by TristanCacqueray** [containers/toolbox#410] opened 2020-04-16 01:20 UTC
From https://softwarefactory-project.io/zuul/t/local/builds?job_name=test-with-podman-stable-f31&pipeline=periodic

The job seems to fail on
````
not ok 13 Echo 'Hello World' inside of the 'running' container
# (from function `die' in file test/system/helpers.bash, line 218,
#  from function `run_toolbox' in file test/system/helpers.bash, line 107,
#  in test file test/system/201-run.bats, line 11)
#   `run_toolbox run -c running echo "Hello World"' failed with status 129
# $ ./toolbox run -c running echo Hello World
# [ rc=129 (** EXPECTED 0 **) ]
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #| FAIL: exit code is 129; expected 0
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Notice that this is only affecting f31, f30 seems to be in the clear: https://softwarefactory-project.io/zuul/t/local/builds?job_name=test-with-podman-stable-f30&pipeline=periodic

**Comment by HarryMichal** [comment] 2020-04-24 09:00
Thank you @TristanCacqueray for reporting this. I, too, noticed that some time ago. I'm not sure what may be causing the issue. I'll try to investigate when I can.

**Comment by HarryMichal** [comment] 2020-07-15 12:05
I finally got to look at this and after a few hours of searching, I still don't know the reason why this is happening. The issue has also evolved and now looks like this:

```
not ok 12 Echo 'Hello World' inside of the 'running' container
# (from function `is' in file test/system/helpers.bash, line 261,
#  in test file test/system/201-run.bats, line 12)
#   `is "$output" "Hello World" "Should say 'Hello World'"' failed
# $ /usr/local/bin/toolbox run -c running echo Hello World
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: Should say 'Hello World'
# #| expected: 'Hello World'
# #|   actual: ''
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The command itself is executed correctly but it seems to me that it either does not wait until the command is done executing or the output is just thrown away. I'm slightly suspicious of some change on Zuul's side...

I could not reproduce the issue locally (Fedora 31 in a VM running in a loop `bats -t 201-run.bats` until it fails). So I believe this has something to do with the environment the tests are run in (Zuul uses Ansible under the hood, right?).

I guess the easiest/quickest solution now is to only look for the return code and not for the string in `$output`.

**Comment by TristanCacqueray** [comment] 2020-07-16 02:22
Zuul runs the test command using Ansible through that playbook: https://github.com/containers/toolbox/blob/master/playbooks/fedora-31/test-with-podman-stable.yaml#L15

Note that the tests are now failing because of `Program(s) ['go'] not found or not executable`.

**Comment by morucci** [comment] 2020-07-17 09:33
Looking at the build history. It seems the last success was a check job on that PR https://github.com/containers/toolbox/pull/438. The go command not found should be fixed by 438 I guess.

**Comment by morucci** [comment] 2020-07-17 09:51
Also note that periodic jobs run on master and harry/update-issue-templates branches. https://softwarefactory-project.io/zuul/t/local/builds?job_name=test-with-podman-stable-f31

harry/update-issue-templates contains a .zuul.yaml that lead to the periodic jobs to run on that branch too.

To avoid this Zuul provides a solution to exclude the unprotected branches: https://softwarefactory-project.io/r/18882/

Let us know if the toolbox master branch is set as protected in the project settings then we could merge the change above.

**Comment by HarryMichal** [comment] 2020-07-17 16:05
@morucci Yes, #438 fixes test being broken in master.

> harry/update-issue-templates contains a .zuul.yaml that lead to the periodic jobs to run on that branch too.

Damn, I did not realize that I created a branch in this repository. Thank you for the heads-up. 

> Let us know if the toolbox master branch is set as protected in the project settings then we could merge the change above.

I'm not sure if the branch is protected or not. @debarshiray can answer that next week.

**Comment by debarshiray** [comment] 2020-07-22 09:00
> Let us know if the toolbox master branch is set as protected in the
> project settings then we could merge the change above.

Yes, the `master` branch is now marked as protected.

Thanks for your help with this issue!

**Comment by morucci** [comment] 2020-07-27 13:11
https://softwarefactory-project.io/r/18882 Is merged. Let's close the issue if that's ok from your side.

**Comment by debarshiray** [comment] 2020-07-27 13:21
Thanks for that change, @morucci 

Do we know why the echoed message from the Toolbox tests started to randomly disappear? It would be nice to know the root cause of it so that we can again start checking the text.

**Closed** 2023-12-03 15:18 UTC
Labels: 2. CI
