### ISSUE TITLE
Python pip module install reflected outside

### ISSUE THREAD

**Issue by amit08255** [containers/toolbox#351] opened 2019-12-18 04:24 UTC
I am using toolbox on Fedora Silverblue. I entered into a toolbox container and installed module using command --
```sh
pip3 install --user openpyxl
```
It was installed successfully and working without issue. Problem is, same library is also installed and working outside toolbox container in python.

**Comment by markstos** [comment] 2019-12-31 13:20
This is expected behavior. This can perhaps be considered a dupe of #353, which is the failure to document exactly how the containers integrate with the host. One way they integrate is by sharing your home directory with the host. If you'd like an option to not sure your home directory with certain containers, that feature is being discussed in #183. 

The `tlbx` fork is [working on implementing an option to not share the home directory](https://gitlab.com/uppercat/tlbx/issues/3, but last time I tested it there was still a bug with it. 

Because the concerns raised in this issue are covered by existing issues, I believe this issue can be closed.

**Comment by juhp** [comment] 2020-01-07 03:30
I think this is a different general use-case and makes sense: having some toolbox-only subspace available under home. Perhaps an overlay in the vain of ~/.local say `~/.toolbox`, with `~/.toolbox/bin` in `PATH` say.

**Closed** 2020-01-07 04:30 UTC

**Comment by markstos** [comment] 2020-01-07 14:57
Why does a development container for work or open source with possibly untrusted code need access to my baby photos or my "Banking" folder or my crypto wallet? 

In section on [Use Cases](https://github.com/containers/toolbox#developer-use-cases), none of the use cases outline there require access to personal files like photos or financial information. 

@juhp Instead of taking a "secure by default" approach of only sharing what's needed, the suggestion of overlay adds more complexity only and only narrows the scope of the problem a little.

As developer ecosystems have become more security conscious, there has been a shift away from installing software as root to installing it in a user's home directory. That seems to be true for Node.js, Python, Perl and I'm sure more. For all those developer use-cases, the shared home directory can be problematic, as modules intended to be isolated in one container appear in all other containers due to the shared home directory that there is no way to turn off! The `tblx` fork demonstrated it can be done and still have the tool function. 

I appreciate the goal of creating a great, convenient development experience but what, exactly, from the user's home directory is so important to share with *every toolbox* container? The only real use-case I see for the share-home-by-default design is for a single top level container that that functions more like the primary operating system and then contains untrusted containers with that are managed more directly by `podman`, `lxd` or another tool.
