### ISSUE TITLE
Add an option to stop or kill the toolbox container (Feature request)

### ISSUE THREAD

**Issue by shuriken1812** [containers/toolbox#1015] opened 2022-02-23 21:32 UTC
Hi toolbox team, 
I use toolbox to test my CI and other automation tests, and it gives me a great root environment that I can create and destroy. However in my use case sometimes I want to delete a container with 

`toolbox rm containername`

However the toolbox container is still running so it is unable to delete that container. I don't think there is any stop or force stop option like `toolbox stop containername` or `toolbox kill containername` maybe we can also add `-f `flag to force. I checked --help and I don't find anything related to this. 

Thanks, I actually love toolbox for my purpose. Despite the fact it is intended for a different purpose as given in the README, I wish you consider this feature request.

**Comment by HarryMichal** [comment] 2022-06-04 21:55
Hi @shuriken1812! The fact that toolbxes remain running after the last session in them has been terminated is [known](https://github.com/containers/toolbox/issues/114). Ideally toolbxes should stop after the last session has been terminated and thus an explicit `toolbox stop` command would have been unnecessary. So, I'll have to decline your request to add the explicit command.

Another matter is that `toolbox rm` does not tell you what to do in the case a toolbx is running when you want to remove it. The way past that is to use the `--force|-f` flag to force remove it. The `toolbox rm` command should suggest that if it encounters a running container.

**Comment by drsh2306** [comment] 2023-01-01 15:14
The bug you are referring to is more than 3 and a half years old.
Pretty much if a sysadmin writes uninstallation script he is left with two options:
- has to hack your software
- request users to reboot their computers before uninstallation

Both of them are a no go, so the suggested workaround would be still better than no fix (current situation).

**Comment by debarshiray** [comment] 2023-01-18 14:08
Duplicate of https://github.com/containers/toolbox/issues/114

**Closed** 2023-01-18 14:08 UTC
Labels: 1. Feature request
