### ISSUE TITLE
Failed to start toolbox

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [containers/toolbox#766] opened 2021-05-11 14:08 UTC
**Describe the bug**
After I upgraded my system I am unable to run toolbox.
```
[~]$ toolbox enter --log-level debug
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user MohamedAmin 
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Toolbox config directory is /home/MohamedAmin/.config/toolbox 
DEBU Current Podman version is 3.2.0-rc1          
DEBU Creating runtime directory /run/user/1000/toolbox 
DEBU Old Podman version is 3.2.0-rc1              
DEBU Migration not needed: Podman version 3.2.0-rc1 is unchanged 
DEBU Resolving container and image names          
DEBU Container: ''                                
DEBU Distribution: ''                             
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'fedora-toolbox-34'               
DEBU Image: 'fedora-toolbox:34'                   
DEBU Release: '34'                                
DEBU Checking if container fedora-toolbox-34 exists 
DEBU Inspecting mounts of container fedora-toolbox-34 
DEBU Starting container fedora-toolbox-34         
Error: failed to start container fedora-toolbox-34
```
```
[~]$ podman start --attach fedora-toolbox-34
Error: unable to start container 1a44fb88ebd4e957db7e49655a7d6eaaf8b5b8b1c47ddff7f62ac31aa1b17903: opening file `` for writing: No such file or directory: OCI not found
```

I created another toolbox and it worked
```
 toolbox create other
Created container: other
Enter with: toolbox enter other
[~]$ toolbox enter other
⬢[toolbox]$ 
logout
```

**Steps how to reproduce the behaviour**
I just tried to run my default toolbox container

**Output of `toolbox --version` (v0.0.90+)**
```
[~]$ toolbox --version
toolbox version 0.0.99.1
```

**Toolbox package info (`rpm -q toolbox`)**
```
[~]$ rpm -q toolbox
toolbox-0.0.99.1-1.fc34.x86_64
```

**Output of `podman version`**
```
[~]$ podman version
Version:      3.2.0-rc1
API Version:  3.2.0-rc1
Go Version:   go1.16.3
Built:        Wed May  5 22:03:46 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
```
[~]$ rpm -q podman
podman-3.2.0-0.1.rc1.fc34.x86_64
```

**Info about your OS**
```
[~]$ cat /etc/*release
Fedora release 34 (Thirty Four)
NAME=Fedora
VERSION="34.20210510.0 (Silverblue)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34.20210510.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='34.20210510.0'
Fedora release 34 (Thirty Four)
Fedora release 34 (Thirty Four)
```

**Comment by HarryMichal** [comment] 2021-05-12 16:32
Duplicate of #760.

**Closed by HarryMichal** 2021-05-12 16:32 UTC
Labels: 1. Bug
